### ISSUE TITLE
Feature request: Log Rotation

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#108]
Need a way to prevent server disk space from fill up with log files from UST.

add log rotation interval of daily, weekly, monthly, yearly, or by # of day would solve this issue.

**Comment by adobeDan** [comment]
@bhunut-adobe Can you be a little more precise on the additional requirements you are asking for beyond what the system already does?  AFAICT, the log files are already "rotated" on a daily basis; that is, the log file that is used is always named containing the day that the session was started.  So no single log file will get too big to fill the server disk, and the admins are free to set up whatever they want in terms of moving older log files to bigger, cheaper storage.

**Comment by bhunut-adobe** [comment]
sorry, I guess what I meant to say is optional Log retention feature to have it automatically archive or delete after a specified period of time.

**Comment by adobeDan** [comment]
Yeah, I think we can just let people use cron jobs for that.  Thanks for the suggestion. -d.
