### ISSUE TITLE
Cannot update country code

### ISSUE THREAD

**Issue by raymond-ensemble** [adobe-apiplatform/user-sync.py#117]
Added more info in my comment below.

**Steps**
1. Set up AD users with country (ie: CA, US or none)
2. In the after_mapping_hook, add: target_attributes['country'] = 'GB'
3. Run the user-sync with **python user-sync.pex --users group "CCE AD Group 1" --update-user-info --process-groups**
4. Go to the dashboard user management and export the user list to confirm the country codes

**Results**
- The country codes for the users remain the same as AD (ie: CA, US or UD)
- In the log, I see that the GB is in the 
*2017-03-27 17:16:47 10648 DEBUG processor - Target attrs, after: {'username': 'CCE4@ensemble.ca', 'domain': None, 'uid': None, 'firstname': '!Custom', 'lastname': 'Tes', 'country': 'GB', 'email': 'CCE4@ensemble.ca'}*

```
extensions:
  - context: per-user
    extended_attributes:
      - sn
      - title
    extended_dashboard_groups:
      - Ensemble Test
      - Ensemble Test 2
    after_mapping_hook: |
      sn = source_attributes.get('sn')
      title = source_attributes.get('title')
      if title is not None:
        target_attributes['lastname'] = title[0:3]
      target_attributes['firstname'] = '!Custom'
      target_attributes['country'] = 'GB'
      if int(sn) > 3:
        target_groups.add('Ensemble Test')
      elif int(sn) <= 3 :
        target_groups.add('Ensemble Test 2')
```

Full config and log:
[user-sync-config.txt](https://github.com/adobe-apiplatform/user-sync.py/files/874148/user-sync-config.txt)
[country code log.txt](https://github.com/adobe-apiplatform/user-sync.py/files/874149/country.code.log.txt)

**Comment by raymond-ensemble** [comment]
It's not just from the custom codes. It doesn't seem to update when I sync from a user file.

**Steps**
1. Sync users from a user-file.csv with --update-user-info
2. In the user-file.csv, change the countries to something else
3. Sync users from a user-file.csv with --update-user-info again
4. Go to the dashboard and export the user list to verify

**Comment by adobeDan** [comment]
Country change is not allowed after creation (either from the console or from the UMAPI or from bulk update) for either Federated or Enterprise ID at this time.  It's on the roadmap for later this year.

When you create a new user account from scratch (that is, first time a user with that email has ever existed), you can set the country code with custom attribute assignment.  But you have to be sure that no user with that email has ever existed in that organization in the past.  Or else you must delete the user account (with `--delete-unmatched-users`) to ensure that your next create on that email creates a new user account.

Have you been unable to create new user accounts with the custom country code?  If so, that would be a bug.  But it looks like this behavior is as designed for now.

**Comment by raymond-ensemble** [comment]
I can create a brand new user (default country as CA) and change the country using custom country code. Say I take NZ010101 from an AD attribute and use the NZ as country.

**Comment by adobeDan** [comment]
Perfect.  So this is as designed for the moment.  Thanks for the update.
