### ISSUE TITLE
too many unused results in debug

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#122]
I have an AD set up with 2 users inside a given group: G1
I have an AC group with 3 users inside ( same name as AD for ease of usage), but these are not same ones as in AD + some 600 others that are not in G1 group.
I am running 1.2rc2 and command line: **user-sync --users group G1 --process-groups**  
Result: there are 600 lines of output of form:
**2017-03-31 03:47:18 4068 INFO processor - Adobe user unmatched on customer side: federatedID,userx@mydoamin.com**

and between these, there are the 3 lines of interest for the existing 3 that need to be removed (below is the pair of console output for 1 user):
**2017-03-31 03:47:20 4068 INFO processor - Managing groups for user key: adobeID,anotheruser@dom.com, added: set([]) removed: set(['G1'])
2017-03-31 03:47:20 4068 INFO dashboard.owning.action - Added action: {"do": [{"remove": {"product": ["G1"]}}], "useAdobeID": true, "requestID": "action_1", "user": "anotheruser@dom.com"}**

Added to these there are also the expected two for user added to group in AC (here is the example of console output for one of them):
**2017-03-31 03:47:23 4068 INFO processor - Adding directory user to Adobe: federatedID,n2@mydomain.com,
2017-03-31 03:47:23 4068 INFO dashboard.owning.action - Added action: {"do": [{"createFederatedID": {"lastname": "n2", "country": "US", "email": "n2@mydomain.com", "firstname": "l2", "option": "ignoreIfAlreadyExists"}}, {"add": {"product": ["G1"]}}], "requestID": "action_4", "user": "n2@mydomain.com"}**

Expected as improvement:
To see in output only the 3 removed users and 2 added users and not all the other users that do not make the object of interest.
Also, if the "group" argument is passed, is it still necessary for the tool to get ALL users from AC when they could only be retrieved from given group, then synced?  I'm thinking that this may also be faster than extracting users from bigger organisations (like +5000 users).

I'll share with you the log file so you can see the details.

**Comment by adobeDan** [comment]
I have created new issues #124 and #129 for the two separable issues reported here.  Closing this as a duplicate.  Thanks for the report, @Luci2015, we will get to these as soon as we can.
