### ISSUE TITLE
.tgz unknown suffix on windows

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#128]
.tar.gz works fine, but .tgz will require users to rename first.  At least for 7zip.
This is in 2.0 alpha build 1

**Comment by adobeDan** [comment]
Fixed in the a1 upload artifacts.  Let's leave this open to remember to get it right in the rc1 build.

**Comment by ianmak** [comment]
ah sorry about that, will remember for next RC

**Comment by adobeDan** [comment]
No worries, this was really my fault, as I set the pattern with that first windows upload to a1. :)

**Comment by adobeDan** [comment]
closing this since we got it right for the rc1 build.
