### ISSUE TITLE
--users-filter is returning 0 users even though users exists in AD.

### ISSUE THREAD

**Issue by raymond-ensemble** [adobe-apiplatform/user-sync.py#135]
**Steps**
1. Step up users in AD. User cce1, cce2, cce3....cce10.
2. Run user sync with **python user-sync.pex --users all --user-filter "cce"**

**Results**
- It says "2017-04-03 15:44:30 8072 INFO processor - Total directory users after filtering: 0"

[user-filter log.txt](https://github.com/adobe-apiplatform/user-sync.py/files/891642/user-filter.log.txt)

**Comment by phil-levy** [comment]
Pattern has to match the entire user name.  This was a bug fix in 2.0.  It was always spec'd for a full match.  So you would need "cce[1-9][0-9]?

**Comment by raymond-ensemble** [comment]
I see. I got it to work when I include the email.
cce[0-9].*
