### ISSUE TITLE
Misleading error message for unrecognized column name in user list

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#141]
Warning cites connector.csv.  The file with the error is users-list.csv

2017-04-04 13:48:05 26392 INFO main - user-sync.pex --users file users-list.csv --process-groups -t
2017-04-04 13:48:05 26392 INFO main - -------------------------------------
22017-04-04 13:48:06 26392 INFO processor - ---------- Start Load from Directory -----------------------
2017-04-04 13:48:06 26392 WARNING connector.csv - Unrecognized column names: ['user']
2017-04-04 13:48:06 26392 INFO processor - ---------- End Load from Directory (Total time: 0:00:00)

**Comment by adobeDan** [comment]
The CSV connector is the module reporting the warning.  I don't think it's a problem saying this comes from the CSV connector, and I don't think you're suggesting that either.  The problem is that we are not mentioning the name of the CSV file that we are loading that has the unrecognized column name.  That's easy to fix.

**Comment by phil-levy** [comment]
The module name is very misleading.  There isn't any file named connector.csv which the message appears to be reporting against.  The customer will not know that is a module name.  The other names like "main" and "processor" and "umapi" are more generic and wouldn't be confused with the file containing the error.

**Comment by adobeDan** [comment]
So there are two issues here:

1. The connector name is misleading, because it sort of looks like a filename.
2. The filename is missing from the error message.

I can fix both, but do we care about the first if I fix the second? :)

**Comment by phil-levy** [comment]
Certainly less so.

**Comment by adobeDan** [comment]
OK, I fixed both :).  csv and ldap now follow the same path as umapi: they just have the connector type without the work "connector.".  Also the filename is printed in the error message.  Also I found another place where we are not properly catching errors: on UMAPI connection errors; we still had a backtrace.  So I fixed that too.
