### ISSUE TITLE
Warning should be given if no valid filter present in file specified using --source-filter

### ISSUE THREAD

**Issue by Metasemi** [adobe-apiplatform/user-sync.py#17]
If the file specified using the --source-filter command line option is valid YAML but contains no valid filter, then no exception is thrown and no warning is given. For example, in one test the command line specified

    --source-filter ldap:filter.yml

where the specified file's content was just

    (cn=Smoke*)

This content is faulty (should have been      all_users_filter: "(cn=Smoke*)"      ) and doesn't define a valid filter. It's valid YAML though, parsing as a single string, so no exception is thrown.

It would be useful to produce a warning in the log for such a case.

**Comment by jamesg123** [comment]
@Metasemi - Hi Mike - I have added validation for this and created a [PR](https://github.com/adobe-apiplatform/user-sync.py/pull/19). I had to make a couple of assumptions about how to deal with the errors as follows, if you want it tweaked at all let me know and I will be happy to update:

* Processing will continue with no filter if an invalid source-filter is found in the filter.yml
* The log message will be at info level
* The log message when will read as follows:

'Ignoring source filter for directory[ldap] as "all_users_filter" was not specified'

note - directory[ldap] would be replaced with the connector_name variable

**Comment by Metasemi** [comment]
@jamesg123 Thanks James. I think this should be at least a warning if not an error. By specifying --source-filter, the user intends to globally influence the user load. If a user mistake prevents that intention from having an effect, surely we want to at least warn. (And if in some crazy scenario someone wants to always --source-filter but only sometimes actually filter, the filter itself can be made a no-op.)

@phil-levy what do you think?

**Comment by Metasemi** [comment]
Ah I see Phil also wanted to bump it to a warn in a comment on the PR itself...

**Comment by phil-levy** [comment]
PR accepted.  This should be fixed in the next release.
