### ISSUE TITLE
Mapping directory group to Adobe admin roles

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#191]
A customer is looking to manage administrators in the admin console via UST.

This will give enterprise customer a more automated way to add and remove administrators from the console.

**Comment by adobeDan** [comment]
This is the start of a proposal about what to do here...

**Comment by adobeDan** [comment]
The design problem here is that, while the `addRoles` and `removeRoles` action commands allow setting users into all kinds of admin roles, the list of users with those roles isn’t available to User Sync as a standard “Adobe group”.

**Comment by Jeff-Jerousek** [comment]
I don't know how reasonable this request is or if its within the goals of the user-sync tool is but what would work for me who is in a smaller organization < 1,000 users. I would not expect to run this more than once a week/occasionally on demand. 

Use a new parameter for an administrative-sync and define a separate administrative-sync groups (roles) in the config file. To avoid confusion I would suggest a 1 to 1, adminRole to ldap group, relationship. 

Dynamically generating "groups" on the Adobe side by iterating over all users and their "adminRoles", only looking for roles defined in the config file. At first I would probably only define a "system Administator" group and a "deployment Administrator" group.

The tool would "generate" two groups for me, all users with Admin: "org" and all users with "deployment".  Once these two groups are established it would then go about syncing the two generated groups with my configured AD groups.

A user in both groups would then have 

 "adminRoles": [
      "org",
     "deployment"
    ]

Removing the user from systemAdmin group, after running would then look like:

 "adminRoles": [
      "deployment"
    ]

**Comment by adobeDan** [comment]
We are working with the back-end UMAPI development team on a UMAPI enhancement that will enable this feature without User Sync having to do a lot of "synthetic" group creation.  As we get clarity on the timing of that enhancement, we will figure out whether it makes more sense to wait for it or to do something more "stop gap" in the mean time.

**Comment by adobeDan** [comment]
Admin group management via the same techniques as regular group management looks imminent, as in within the next few weeks.  So I'm going to take this one off our list.
