### ISSUE TITLE
Getting error 1520 CRITICAL main - ldap configuration: must contain setting for "password" or "secure_password_key"

### ISSUE THREAD

**Issue by Stancicle** [adobe-apiplatform/user-sync.py#196]
Hello,

I'm getting the error:
1520 CRITICAL main - ldap configuration: must contain setting for "password" or "secure_password_key"

I have commented out "password" and uncommented "secure_password_key" in conector-ldap.yml. The problem still happens if I user "password" and input the plaintext password.

Running on Windows 7 64 bit, v2.1 Enhancement Release: unicode and security, and the latest code. 

What I have credential manager. 
![image](https://cloud.githubusercontent.com/assets/28760235/26161797/25c95556-3ae2-11e7-9fb5-74a2912ed9a6.png)

**Comment by bhunut-adobe** [comment]
Hello,
you want to make sure the Internet or network address value equal to the one in the connector-ldap.yml configuration file.

For example:
connector-ldap.yml
`secure_password_key: ldap_password`

Windows Vault:
`Internet or network address: ldap_password`

**Comment by Stancicle** [comment]
Hi Bhunut-adobe,

Same error still occurring.

![image](https://cloud.githubusercontent.com/assets/28760235/26162909/473f04c6-3ae5-11e7-9b3f-f4ed6ed8b6ad.png)

connector-ldap.yml
![image](https://cloud.githubusercontent.com/assets/28760235/26162941/5e48ed26-3ae5-11e7-8843-9308c6e55136.png)

**Comment by bhunut-adobe** [comment]
is the username value in connector-ldap.yml is the same as the one in the windows credential vault?

**Comment by Stancicle** [comment]
Yes, with the exact uppercase and lowercase.

**Comment by bhunut-adobe** [comment]
Is it possible if you can run the sync tool with debug logging?

user-sync-config.yml
```
  log_to_file: True
  file_log_level: debug
  console_log_level: debug
```

can you upload your connector-ldap.yml, user-sync-config.yml, and the log? Just make sure you remove any sensitive information.

**Comment by Stancicle** [comment]
Here you go.
[adobe_user_sync_troubleshooting.zip](https://github.com/adobe-apiplatform/user-sync.py/files/1008561/adobe_user_sync_troubleshooting.zip)

**Comment by bhunut-adobe** [comment]
@adobeDan @phil-levy Have you come across this issue? I wasn't able to replicate the issue. The configuration files look fine.

**Comment by phil-levy** [comment]
I'm in the process of testing that now.  I've already run into problems putting certificate data into the windows credential store.  I haven't tried the LDAP stuff yet.  The file Mr. Stancicle sent looks okay to me also.

**Comment by Stancicle** [comment]
Hi all,

False alarm. Seems like I was configuring the wrong copy of connector-ldap.yml. It is working now. Thank you.

**Comment by phil-levy** [comment]
Thanks.  Closing.
