### ISSUE TITLE
logging: file_log_level is not honored nor validated

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#2]
logging:
    file_log_level: errorx
 -- no error message

logging:
    file_log_level: error
-- still shows debug messages

**Comment by jamesg123** [comment]
Hi Phil,

I have added some validation for the file_log_level as requested (I will push it once I have access).

I think your understanding of how this works is correct, but I just want to run through a couple of examples just so we are on the same page. The valid options for file_log_level are as follows:
"debug"
"info"
"warning"
"error"
"critical"

Selecting a file_log_level of "debug" will output messages from that level down i.e. "debug", "info", "warning", "error". So I would expect "error" (as you say) to output "error" and "critical" and not "debug" messages.

One thing I would like to point out is that there are two settings which are independent of each other:
file_log_level - log file setting
and
console_log_level - output to terminal

Can you confirm that both of these were set to "error"? If file_log_level was set to "error" but the console_log_level was "debug" then we would still see (on the console) debug messages which may explain the issue.

If that isn't the issue, do you have an example of the config/command line options and output produced?

Thanks,
Jim

**Comment by adobeDan** [comment]
@jamesg123 - You now have write access to the repository (so you can push build artifacts), but for code changes please do a local fork, make the changes in the v1 branch, and do a pull request back to the repo v1.  Thanks!

**Comment by phil-levy** [comment]
Could be that the lack of an error message about illegal option values confused me.  I probably set file_log_level to Error instead of error.  I find if I set it to error or info it works properly.

**Comment by jamesg123** [comment]
@phil-levy @adobeDan  Thanks for the access. I have raised the following PR for the log level validation https://github.com/adobe-apiplatform/user-sync.py/pull/15

**Comment by phil-levy** [comment]
PR should address this.  Closing.
