### ISSUE TITLE
Could not deserialize key data.

### ISSUE THREAD

**Issue by chad-fox** [adobe-apiplatform/user-sync.py#209]
2017-06-01 16:44:23 1604 CRITICAL main - UMAPI connection to org id '00000000000

0000000000000@AdobeOrg' failed: Could not deserialize key data.

*org id removed

I receive this error when running user-sync test. I've checked the org id and all sees correct.

**Comment by phil-levy** [comment]
Can you say more about what you are trying to do, what version you are running, perhaps include more of a log?

**Comment by chad-fox** [comment]
I was trying to test a sync (Windows) and received the posted error. I believe it has something to do with the public key, which I'm recreating now.  

I'm running v2.0

**Comment by chad-fox** [comment]
Cert has been recreated and the issue persists. 

I've verified that the information in connector-umami.yml is correct and matches with the Adobe I/O console. 

-

C:\Windows\system32>python "C:\UserSyncTool\user-sync.pex" -t
2017-06-02 09:34:10 3628 INFO config - Using main config file: user-sync-config.
yml
2017-06-02 09:34:10 3628 INFO main - ========== Start Run (User Sync version: 2.
0) ==============
2017-06-02 09:34:10 3628 INFO main - ------- Invocation parameters -------
2017-06-02 09:34:10 3628 INFO main - C:\UserSyncTool\user-sync.pex -t
2017-06-02 09:34:10 3628 INFO main - -------------------------------------
2017-06-02 09:34:10 3628 CRITICAL main - UMAPI connection to org id '00000000000
0000000000000@AdobeOrg' failed: Could not deserialize key data.
2017-06-02 09:34:10 3628 INFO main - ========== End Run (User Sync version: 2.0)
 (Total time: 0:00:00)

**Comment by adorton-adobe** [comment]
@chad-fox  – How did you generate the public/private keys for the API integration?  Did you follow the examples in this document?

https://www.adobe.io/apis/cloudplatform/console/authentication/createcert.html

**Comment by chad-fox** [comment]
I followed the instructions from the Adobe I/O console to create the public/private keys.  

Thanks,
Chad

**Comment by adobeDan** [comment]
This looks to me like you are trying to save and then retrieve the private key data in the Windows credential manager, but that fails because of the length of the private key.  This is already reported as issue #198.

If this is not the same issue, then please post your (non-sanitized) main config file, umapi config file, and a debug log file to my Adobe email address (available from my GitHub profile).  Thanks.

**Comment by chad-fox** [comment]
Files were sent over now.

Thanks,
Chad

**Comment by adobeDan** [comment]
Confirming I got the files.  I'll let you know what I find as soon as I can take a look.

**Comment by adobeDan** [comment]
Hi @chad-fox, it looks like you are putting the path to the public certificate file (`certificate_pub.crt`) into your UMAPI config.  What you need is the private key file (something like `certificate.key` or `certificate.pem`).  The public key is what gets uploaded to your Adobe I/O integration, and then the private key gets sent up by the User Sync Tool.

To confirm, take a look at the first line of each file.  The private key file (in PEM format) should have a first line that looks like this:
```
-----BEGIN RSA PRIVATE KEY-----
```
and the certificate file (also in PEM format) should have a first line that looks like this:
```
-----BEGIN CERTIFICATE-----
```

Hope this helps.

**Comment by chad-fox** [comment]
@adobeDan thank you so much for all your help, I knew I was missing something. 

The test sync ran without issue. 

-Chad
