### ISSUE TITLE
Update Python to 2.7.13 in next builds

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#21]
A number of security vulnerabilities were fixed.
That should say Python in the title.

**Comment by adobeDan** [comment]
@phil-levy Can you clarify what you mean?  The PEX that we build doesn't contain a Python executable; it uses the executable present on the system that runs the PEX.  Building with any version of 2.7 should suffice; it's the people who *run* the PEX that should be running the latest Python.

Perhaps you are talking about the pre-built libraries we use on Windows?  Those also can be for any version of 2.7, or at least 2.7.7 or above.

**Comment by phil-levy** [comment]
The builds we create should be built with 2.7.13 and the embedded version that goes into the non-windows platform builds should be 2.7.13.

**Comment by phil-levy** [comment]
Isn't this done at this point?

**Comment by adobeDan** [comment]
@chesterl86 can you please confirm that the 1.1.1 builds and later are being done with 2.7.13?

**Comment by chesterl86** [comment]
Yup, thats right.

**Comment by adobeDan** [comment]
We have decided to build with the platform python where it exists.  So this only applies to Windows now.
