### ISSUE TITLE
I'm getting a UnicodeDecodeError: 'utf8' even though I have used --config-file-encoding big5 when trying to sync from a CSV file

### ISSUE THREAD

**Issue by raymond-ensemble** [adobe-apiplatform/user-sync.py#213]
**Prerequisite**
- Set up a CSV file, encode it in big5 (I used Notepad++ -> Encoding -> Characters sets ->Chinese -> Big5), and then, add big5 characters into the file.

**Steps**
1. Try to sync by using the big5 encoded CSV file
command used: 
> python user-sync.pex --adobe-only-user-action exclude --users file users-file.csv --process-groups --update-user-info --config-file-encoding big5

**Results**
I get this error:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa4 in position 12: invalid start byte

[2017-06-06.txt](https://github.com/adobe-apiplatform/user-sync.py/files/1056606/2017-06-06.txt)
[csv.txt](https://github.com/adobe-apiplatform/user-sync.py/files/1056607/csv.txt)

**Comment by adobeDan** [comment]
The --config-file-encoding option tells us the encoding of the user-sync-config.yml file, *not* of any CSV file.  To tell us the encoding of your csv file, you need to add
```yml
string_encoding: big5
```
to your `connector-csv.yml` file.  See the example config files for details.

**Comment by raymond-ensemble** [comment]
Ah, I see.

I was able to sync after adding the 
> string_encoding: big5

**Comment by adobeDan** [comment]
Fabulous!  Thanks for confirming that it works as expected - I'm glad we got some Chinese character testing!
