### ISSUE TITLE
Error with keyrings.alt when trying to sync on a non-desktop version of Ubuntu

### ISSUE THREAD

**Issue by raymond-ensemble** [adobe-apiplatform/user-sync.py#218]
**Steps**
1. Use **Putty** to connect to Ubuntu server
2. Use "keyring set umapi_api_key 210DB41957FFDC210A495E53@AdobeOrg" and password to set up the keyring
3. Run the user-sync.

**Results**
I would get this message:
> CRITICAL main - umapi.primary configuration.enterprise: Error accessing secure storage: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.

However, if I use a Ubuntu desktop VM and run user-sync (with identical config files and keyring set command), it would run fine.

[2017-06-07.txt](https://github.com/adobe-apiplatform/user-sync.py/files/1059342/2017-06-07.txt)

**Comment by ianmak** [comment]
oops I might have mislead Raymond here... this was tested on a headless linux server, which doesn't have gnome-keyring-manager if I'm not mistaken, it may work once that installed. I'll try that out and share the results here...

**Comment by adobeDan** [comment]
headless servers never have the credential store installed by default.

**Comment by adobeDan** [comment]
@ianmak did you add gnome-keyring-manager and confirm that the problem was the missing component?  If so please close this bug.

**Comment by adobeDan** [comment]
I have confirmed that Ubuntu LTS Trusty server config doesn't include keyring support, but when added user-sync can use it.
