### ISSUE TITLE
No Such File or Directory Error on Crypto Folders

### ISSUE THREAD

**Issue by ahambidg** [adobe-apiplatform/user-sync.py#229]
Hello!  I'm trying to set up a new installation of 2.1.1 and while I have set the PEX_ROOT variable, could it be that my variable is too long?  I'm receiving this error:

`IOError: [Errno 2] No such file or directory: u'C:\\user_sync\\.pex\\install\\pycryptodome-3.4.6-cp27-cp27m-win_amd64.whl.dfec9ea083dc290e772b10e484883917dbc3683d.252787247f5e42659e04facecfb42ae8\\pycryptodome-3.4.6-cp27-cp27m-win_amd64.whl\\Crypto/SelfTest/PublicKey/test_vectors/ECC/ecc_p256_private_enc_aes128.pem'`

Thank you for your assistance!

**Comment by phil-levy** [comment]
That does look a bit over 256 characters (271 by my count) but is also suspicious with the double back-slashes.  I'll take a closer look.

**Comment by phil-levy** [comment]
Yes, the new pycryptodome library has longer names and really puts us on the edge.  I get the same error you indicated with PEX_ROOT set to the recommended value C:|user_sync\.pex.  I set it to C:\.pex and then things worked so the extra 10 characters made the difference.  If you set

set PEX_ROOT=C:\.pex

it should work.  My comment about the double back-slashes is incorrect; those are okay.

**Comment by adobeDan** [comment]
Sorry, @ahambidg, but as the release notes for 2.1.1 say: this is a known issue and you will have to set your PEX_ROOT to something extremely short.  Both the `C:\.pex` recommended here by @phil-levy and the `C:\pex` (without the leading `.`) recommended by the release note will work.  I am going to make this into a documentation bug so we update the docs to have the shorter recommendation, at least until we work this issue with the PEX folks (who have recently made their temp folders have much longer names).

**Comment by ahambidg** [comment]
Yeah, that did it.  Thank you for clarifying that, and updating the
documentation would be a huge help.  :)

On an unrelated note, have you all thought about turning this into a
container a la Docker or Vagrant?

Thank you for your hard work!

**Comment by adobeDan** [comment]
@ahambidg Thanks for the thanks! - they are always nice to hear.

Yes if you look at #22 you will see our discussion about Docker support.  We're not going that way, but hopefully it will provide you a good start if you want to pursue it.  And we're glad to take contributions if you develope something others can use!

**Comment by adobeDan** [comment]
Hey @phil-levy I just found the most amazing [Microsoft Article](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx) in which it says that Win10 can be set not to enforce the `MAX_PATH` (260 char) limit:

![Enabling long paths in Windows 10](https://user-images.githubusercontent.com/24463201/27258672-a190113e-53b5-11e7-87da-1b7027843239.png)


I believe the docs should tell our users about this, as it obviates the need to set `PEX_ROOT`.  I just tried it with the v2.1.1 release and it works great!

**Comment by jameslockman** [comment]
Win!

James

James Lockman  | Manager, Digital Media Services  |  Adobe
p. 917.934.0849<tel:19179340849>  |  c. 917.284.2268<tel:19172842268>  |  @jameslockman<http://twitter.com/jameslockman>  |  blog<http://blogs.adobe.com/jlockman>  |  jlockman@adobe.com<mailto:jlockman@adobe.com>

**Comment by bhunut-adobe** [comment]
@adobeDan  - Enable Win32 Long Paths only supported on Windows Server 2016 and Windows 10.
