### ISSUE TITLE
Setting users to a known state shouldn't require fetching Adobe users

### ISSUE THREAD

**Issue by adobeDan** [adobe-apiplatform/user-sync.py#236]
If an organization is very, very large, and the customer wants to run a job that creates or updates specific users to have a specific set of known attributes and group memberships (similar to a bulk upload from the admin console), the customer shouldn't have to wait for User Sync to fetch the Adobe-side users (which may take a long time) and to do the sync.  Instead, the customer should be able to "directly populate" the users into the org with those attribute values and group memberships, instructing user sync either to create or update each individual user as necessary.

**Comment by phil-levy** [comment]
Not sure what you are getting at here, but that capability is already present and was designed to support push notifications.  You can set a csv file with the users you want to populate and exclude adobe-only users to leave everyone else alone.

**Comment by adobeDan** [comment]
Yes but such a User Sync job will still fetch all the Adobe users, only to exclude them.  If your organization is very large then fetching all the Adobe-side users could take a very long time and there's no reason to.  This enhancement would be to skip the fetch of the Adobe users completely.

**Comment by phil-levy** [comment]
Got it.  Thanks.
