### ISSUE TITLE
all encodings should default to utf8

### ISSUE THREAD

**Issue by adobeDan** [adobe-apiplatform/user-sync.py#237]
With the introduction of Unicode support in 2.1, all the encodings were defaulted to `ascii`.  With the prevalence of non-Ascii characters worldwide, this will be limiting for most customers, who will be forced to explicitly specific a different encoding.  We should default all encodings to `utf8`, which is fully backward-compatible with `ascii`, and will in fact be the default for almost all customers.

**Comment by adobeDan** [comment]
@phil-levy Any objections to making this change for 2.2?

**Comment by phil-levy** [comment]
No, it sounds like an excellent idea.
