### ISSUE TITLE
Shaun Garcia - Customer Feedback

### ISSUE THREAD

**Issue by shaungarcia** [adobe-apiplatform/user-sync.py#24]
Please provide comment on the below

"In my testing, the only way to get SyncTool to work is to point the connector-ldap.yml config file to the root of our Active Directory so as to encompass both locations (Obviously I could place the Adobe groups in the "accounts" OU with the users but this messes with our structure). With this setup, SyncTool then syncs my entire directory of users, meaning we get generic email accounts, test accounts, service accounts etc, into the Adobe console when they don't really need to be there.
 
The command I've been testing with is the following: (all config files, certs etc are all in the same directory as the user-sync executable and I'm running the SyncTool from that directory)
 
user-sync --users all --process-groups
 
This works perfectly and does what I expect when I have group mappings configured in user-sync-config.yml   
 
Ideally I'd like to know if it's possible that only users that are actually in one of the mapped AD groups to sync to the Adobe Console or to restrict where SyncTool pulls users from. I did note that there is a "—users group group1, group2" switch but that appears to sync users only and does not apply any Adobe user group management which is not really what we're after.
 
For us (and I realise this is a specific use case but I thought I'd run it by you in any case) ideally we'd have some way to specify where to look for users, and some way to exclude some OUs we don't want examined for users.
 
e.g
users: "OU=accounts,DC=domain,DC=com,DC=au"
groups: "OU=Adobe,OU=SecurityGroups,DC=domain,DC=com,DC=au"
exclude:
  - "OU=generic_accounts,OU=accounts,DC=domain,DC=com,DC=au"
  - "OU=generic_emails,OU=accounts,DC=domain,DC=com,DC=au"
 
Some other things we ran into and would like to query is around how SyncTool treats expired users and disabled users.
 
If a user is disabled and SyncTool has not seen it before, that disabled user does not sync to the Adobe Console – perfect and as expected.
If a user is disabled and already exists in the Adobe Console and remains in a mapped AD groups, SyncTool ignores that user account does not remove it from the Adobe User Group.
If a user is disabled and already exists in the Adobe Console and is removed from a mapped AD groups. SyncTool ignores that user account and does not remove it from the Adobe User Group
 
We have lots and lots of freelancers come in and out of the business, we don't necessarily disable their accounts but set the account expiry based on their contract length. Expired users are pretty much treated as active users in that they will Sync to the Adobe Console and be placed in an Adobe User group if they are in a mapped AD group. If we are using the Adobe Console for licensing numbers, the above scenarios could be problematic"

**Comment by phil-levy** [comment]
Thanks for your comments.  You are really giving the tool a run through.

1. If there is an LDAP query that returns the users you want, you should be able to specify it as the all_users_filter in the ldap config file.  Additionally, there is command line parameter --users-filter that may be helpful.

2.  If you use --users group "a,b,c" --process-groups, that should restrict users to just those in the AD groups and also handle adding to groups and PLCs on the Adobe side.

3.  If a user is disabled which takes them out of the directory query results and they are in a mapped group on the Adobe side, when you run with --process-groups, they should be removed from the group on the Adobe side.  If that isn't working, it is a bug.  I'll check in to it.

4. With respect to freelancers, I think you would have to take some action to either disable their accounts or remove them from the directory group.  I don't think there is currently any way to detect a contract expiration.  Is that a directory attribute?  If so, there may be a way using a feature that is in development.

thanks
phil

**Comment by shaungarcia** [comment]
Hi Michael,

I’m replying to all on this email so you can see the format of incoming mail which I cannot respond to.

Best Regards
________________________________
Shaun Garcia | Principal Customer Success Manager | Adobe Systems |  +61 424 980 888 | shaun@adobe.com<mailto:shaun@adobe.com> | www.adobe.com.au<http://www.adobe.com.au/>

[id:image001.png@01D26C5F.4BAE1B00]

**Comment by phil-levy** [comment]
I have verified the problem where users are not removed from groups when they are removed from the directory.  We'll get on fixing that.  I created issue #27 to track it specifically.
https://github.com/adobe-apiplatform/user-sync.py/issues/27

thanks
phil

**Comment by adobeDan** [comment]
@shaungarcia Can you check with the customer as to whether there are issues they have other than #27 which is now fixed?  If not I'd like to close this issue.

**Comment by adobeDan** [comment]
Haven't heard back from @shaungarcia since we fixed #27, so I'm assuming that no news is good news.
