### ISSUE TITLE
When user_domain_format not specified, domain is not taken from the email

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#240]
```
# (optional) user_domain_format (no default value)
# user_domain_format is analogous to user_email_format in syntax, but it
# is used to discover the domain for a given user.  If not specified, the
# domain is taken from the domain part of the user's email address.
#user_domain_format: "{domain}"
```

I could not find anywhere in the code where "the domain is taken from the domain part of the user's email address."

I'm working with a customer who has multiple domains and they are using Username-Based SSO.

I commented out user_domain_format but this cause incorrect # of directory users filtered.

**Comment by Luci2015** [comment]
Hi Kevin, I've searched the same and just found one for the CSV file input:

```
if domain:
     user['domain'] = domain
elif username != email:
     user['domain'] = email[email.find('@') + 1:]
```

**Comment by bhunut-adobe** [comment]
@Luci2015 Look like they forgot to implement it in LDAP connector. I just submitted a pull request with the change.

**Comment by adobeDan** [comment]
Wow!  I love it when a reported bug gets fixed before I even see the report!  Thanks folks!  And this is just in time for the rc1 build of 2.2 - kismet!!
