### ISSUE TITLE
Sync fails to recognize federated users with username-based login and keeps recreating them

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#26]
If a federated domain is set up for username based login (rather than email based), then user sync does not seem to recognize users.  If you run the same sync repeatedly, it creates the same users and adds them to the same PLCs on  every run.

**Comment by adobeDan** [comment]
Good catch, Phil.  Can you attach a log of two successive runs?  That will save some investigation time.
