### ISSUE TITLE
Extension Hook - Unable to pull additional source_attributes - LDAP failure

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#265]
> Unexpected LDAP failure reading group members: All provided fields *must* be text when bytes mode is off; got 'distinguishedName'

I'm trying to pull in additional attribute to extension hook and run into this issue.

I also tested the example extension and running into the same thing.

UST version 2.2

**Comment by adobeDan** [comment]
Kevin, I need more info.  Python 2 or Python 3?  Debug log?  What LDAP server are you running against?

**Comment by bhunut-adobe** [comment]
I'm running on Python 2.7.13 and Active Directory

[2017-08-21.txt](https://github.com/adobe-apiplatform/user-sync.py/files/1243252/2017-08-21.txt)

**Comment by adobeDan** [comment]
Ah!  In py2, the parameter values passed to the LDAP client must be unicode, and we are failing to upconvert the extended attribute names.  Sigh.  This is a nasty bug that I will fix, but in the meantime there may be a workaround: force the attribute value "distinguishedName" in your config to be read as a unicode string by specifying it as:
```
extended_attributes:
  - !!python/unicode distinguishedName
```
Try that and let me know whether that gets you further.

(You might also have to do this with your `extended_adobe_groups`.  And, if you do, you might have to make those group names be unicode strings (`u'Student'`) in your `after_mapping_hook`.)

**Comment by bhunut-adobe** [comment]
Thank Dan. This workaround fixed the issue.

**Comment by adobeDan** [comment]
Extended attribute values are now upconverted to unicode automatically as necessary.
