### ISSUE TITLE
Extension Hook - Multi-value attribute.

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#266]
When extending a multi-valued LDAP attribute such as memberOf UST will only return the 1st value in an array.

**Comment by adobeDan** [comment]
What would you expect to come back?  I'm guessing you want the list of values?

**Comment by adobeDan** [comment]
So an extended attribute value can now be:
* `None` if there was no value
* a string (if there was one value)
* a list of strings (if there was more than one value)
