### ISSUE TITLE
Typo in xenial release filename?

### ISSUE THREAD

**Issue by adorton-adobe** [adobe-apiplatform/user-sync.py#273]
Seems to be a typo in the filename for the 2.2.1 Ubuntu xenial releases.

- user-sync-v2.2.1-ubuntu-xenix-py27.tar.gz
- user-sync-v2.2.1-ubuntu-xenix-py35.tar.gz

Unless we really do intend to target [Xenix](https://en.wikipedia.org/wiki/Xenix) :)

**Comment by adobeDan** [comment]
Ha!  Best laugh I've had all day.  Thanks!

**Comment by adobeDan** [comment]
Fixed by editing the name in the release artifacts.  Thanks Github for making those links like everything else!
