### ISSUE TITLE
version 2.2.1 - test mode

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#276]
running user-sync tool on windows server 64 bit version, python 2.7, in **test mode** 

Result: actions gets through even if command line run with parameter '-t'
Expected: no change Adobe Console side

submitting log file on private

**Comment by adobeDan** [comment]
This looks to be a server-side bug when handling `removeFromOrg` actions with the `{"deleteAccount": true}` modifier.  I have opened a bug with the UMAPI server team internal to Adobe.  Closing here as user-sync does not have an issue.
