### ISSUE TITLE
v 2.2.1 missing modules with python 2.7.14

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#277]
Please update the doc on Python version required for Windows OS, as v 2.7.14 gives an error on launch for missing modules

**Comment by adobeDan** [comment]
Thanks for the report.  Can you submit a comment showing what you saw in the Windows shell or powershell at launch time?

**Comment by Luci2015** [comment]
Customer did it on his machine, then overwrote 2.7.14 with v2.7.9 on new install
I recognised the error output in console as similar to it was the one for Python 3 version, back in the day..
If you are after the missing modules, cannot say if they were the same as for Python 3 back then, nor remember their name, just that there were about 6-7 of them listed.
Sorry!

**Comment by adobeDan** [comment]
No, worries, thanks.  I will repro.

**Comment by adobeDan** [comment]
I fixed the release notes to talk about this issue.
