### ISSUE TITLE
Admin Console allows specifying attributes for Adobe IDs, User Sync should also

### ISSUE THREAD

**Issue by adobeDan** [adobe-apiplatform/user-sync.py#286]
Administrators in the new admin console are allowed to edit attributes (first name, last name, and country) for Adobe IDs.  But this capability is not provided via User Sync.  (reported by customer via @cosmin-balanoiu)

**Comment by adobeDan** [comment]
Created blocking issue adobe-apiplatform/umapi-client.py#54 whose fix this depends on.

**Comment by adobeDan** [comment]
@cosimin-balanoiu I have a fix for this that I'd like your customer to try with a beta build.  What platform do they need the build on?

**Comment by cosmin-balanoiu** [comment]
@adobeDan They are on windows, python 2.7.13.

**Comment by adobeDan** [comment]
@cosmin-balanoiu Thanks! Unfortunately, we have established that, while the UST fix is enough to get the attributes uploaded, there is also a back-end UMAPI fix needed for the products not being assigned.  So I'd rather wait on the beta build until both problems are fixed and the customer can regress all the problems at once.  I will get you an estimate for the back end fix as soon as I have one.  Thanks for updating your customer on the status.

**Comment by cosmin-balanoiu** [comment]
@adobeDan 
Cheers! Just let me know when you have something for me. Thanks.

**Comment by adobeDan** [comment]
@cosmin-balanoiu OK the first release candidate is [posted for all platforms](https://github.com/adobe-apiplatform/user-sync.py/releases/tag/v2.2.2rc1).  The server-side fixes are also in, so things should work nicely.

**Comment by adobeDan** [comment]
I found a spot I missed in the rc1 fix.  Although attributes are set when Adobe IDs are created, they are ignored if Adobe IDs are updated.

**Comment by cosmin-balanoiu** [comment]
Cheers @adobeDan !

**Comment by adobeDan** [comment]
Thanks @cosmin-balanoiu :).  Please note that the already-posted rc2 build has an even better fix of this bug, but I won't have a chance to post a Windows build until later tonight.
