### ISSUE TITLE
pex releases 2.2.2rc1  not working with Win Py2.7.14

### ISSUE THREAD

**Issue by marcocucinato** [adobe-apiplatform/user-sync.py#298]
As in 2.2.1, the  2.2.2rc1 is not working with Windows Python 2.7.14
error is "failed to execute pex file missing compatible dependencies"

**Comment by Jeff-Jerousek** [comment]
2.2.2rc2 works correctly with Python 2.7.14 (64-bit)

I had the same issue when using the the 32-bit version of Python instead of the 64 bit version. I also needed the Microsoft Visual C++ Compiler Package for Python 2.7 installed.

**Comment by adobeDan** [comment]
Actually the 2.2.2 final build will be built with 2.7.14 on Windows, and that should resolve this as well.
