### ISSUE TITLE
Allow specification of command-line values using config file

### ISSUE THREAD

**Issue by lhoekenga** [adobe-apiplatform/user-sync.py#299]
The default user population is "all" (which is every user that user-sync can find in the local user source).

It would be helpful if it were possible to change the default population in the config file, in addition to the existing command line option.

**Comment by adobeDan** [comment]
Since almost all user-sync runs need some arguments, and most runs are scripted, can you provide a little more motivation for this enhancement request?  Why is it desirable to override the default in the config as opposed to the invocation script?

**Comment by Jeff-Jerousek** [comment]
Not OP, but if I had run my first few attempts without the initial -test parameter. I would have had a few hundred extra accounts I needed to remove from Adobe. I then made documenting this a priority.

As a windows admin. I think it runs counter to the typical windows admin experience. I can also imagine scenarios in the future where my team doesn't know how it works and runs it without parameters before reading documentation. I also looked for this configuration to prevent what I thought might be a very annoying accident in the future.

Windows admins generally expect a 1 user sync scenario or an error to --help without parameters.  I think it just comes down to preference.

**Comment by adobeDan** [comment]
So perhaps the problem is that we default the `all` value rather than having no default and warning when `--users` is not specified?  Sadly, that would be a backward-incompatible change.

**Comment by lhoekenga** [comment]
> Not OP, but if I had run my first few attempts without the initial -test
parameter. I would have had a few hundred extra accounts I needed to remove
from Adobe. I then made documenting this a priority.

This was what I ran into.   I was debugging an issue and didn't look
closely enough at the parameters I used to run user-sync out of cron.  I
ended up with about 10k more users than I intended.

There is precedent for providing config file settings / environment
variables for options you can set on the command line.  I could envision
not having to provide any of the command line options (side from the top
level config file) if the config file was fully configured.

**Comment by adobeDan** [comment]
OK, so what I'm hearing is: 

> It's always better to have one place to configure things rather than two, because that makes one fewer place you have to check to be sure you get them right.  But right now there are always two for User Sync: the config file _and_ the command line.  Can't we just have one?"

So how about a single, new, top-level config file section `invocation-defaults` with the following sub-settings and default values:
```yaml
invocation-defaults:
  test-mode: NO
  users: all
  process-groups: NO
  update-users: NO
  adobe-only-user-action: preserve
  adobe-only-user-list:
  user-filter:
  strategy: sync
```
This allows setting the values for all command line parameters which don't control the reading of the configuration file.  These default values are backward-compatible.  And any values specified for one of these on the command-line will override its values in the configuration file.

Thoughts?  Does this provide what you are looking for?

**Comment by adobeDan** [comment]
Phil, what do you think?

**Comment by adobeDan** [comment]
This looks like a good feature add.  We will pick it up in the next full dot, not the current double-dot.
