### ISSUE TITLE
file paths in config files should be interpreted relative to the file in which they appear

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#30]
If there is an entry in the dashboard-config.yml file like this:

   priv_key_path: private.key

then the file should be interpreted as relative to the directory containing the dashboard-config.yml file.  Now it appears it is relative to the current directory so that if there is a -c option for the config file location, this file ends up not being found unless it is fully qualified.

**Comment by phil-levy** [comment]
I believe this error also occurs for other file references.  All unqualified file references in the configuration files should be relative to the file containing them.  Otherwise, you can't really use the -c option to point to a set of files outside of the current directory.

**Comment by adobeDan** [comment]
@ianmak A more limited version of this is to take all pathnames relative to the location of the main configuration file.  Let's go with this version first, because it's a simpler change for 1.2rc1, and then we will look at making the full change for 1.2 GM.
