### ISSUE TITLE
User Sync fails when adding more than 10 groups to a user

### ISSUE THREAD

**Issue by adobeDan** [adobe-apiplatform/user-sync.py#301]
Reported from the field: when trying to add more than 10 groups to a user, User Sync runs up against a UMAPI limit on the number of groups that can be added in a single action step.

**Comment by adobeDan** [comment]
This is actually due to adobe-apiplatform/umapi-client.py#58, so integrating v2.9 of the umapi-client should fix it.  Thanks @adorton-adobe for the umapi-client fix.

**Comment by adorton-adobe** [comment]
@adobeDan - do split actions impact the "Number of UMAPI actions sent" in the summary? (the split when actions have more than 10 "do" commands)  If so, then very large group lists (>100) will inflate that number.  Would that be a concern?

**Comment by adobeDan** [comment]
@adorton-adobe Yes, if a UMAPI gets split into multiple commands, that might cause the action containing it to be split into multiple actions, in which case the 'Number of UMAPI actions sent" in the summary might increase.  I don't see why this would be a concern, since it's already the case that the UMAPI consolidates and splits commands into actions so as to minimize the number of server calls, and thus the number of actions sent doesn't really correspond to anything else in those statistics.
