### ISSUE TITLE
Build Pex without dbus

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#318]
The build instruction stated that

> You don't need the python-dbus package to build user-sync, but you will need it to run user-sync if you use the dbus secure store for your credentials.

However, when I attempted to build UST, I got an error for dbus which it normal for Centos 6. It seems like dbus is still required to build.

> pex: Failed to install package at /tmp/tmp6o6pfowi/dbus-python-1.2.4: Failed

OS: Centos 6.7
Python: 3.6.3
Using virtualEnv.

[pex.log](https://github.com/adobe-apiplatform/user-sync.py/files/1549367/pex.log)

**Comment by adorton-adobe** [comment]
I've been unable to build it in 6.7  If you build it in 7, you should be able to run the pex in 6.7.

**Comment by bhunut-adobe** [comment]
@adorton-adobe Yeah in rhel/centos 6 it usually errors out because of dbus. But the documentation now said dbus is optional from the build process.

**Comment by adobeDan** [comment]
I'm investigating.  I haven't done much in centos6.  But I will take a look over the next few days.

**Comment by adobeDan** [comment]
Haven't had any time to look at this.  Still trying.

**Comment by adobeDan** [comment]
OK, so dbus-python *is* required for builds; that was an error in the README.  Further, the latest version of dbus available on CentOS 6 is 1.2 but user-sync requires 1.6 or later to build.  So you cannot build user-sync on CentOS 6, but you can run the CentOS 7 build on CentOS 6 (as long as you are using the same version of python 3).  But I doubt it will work if you try to use the keyring.

**Comment by adobeDan** [comment]
Marking this bug as wontfix, because there's no way to build on CentOS6.  Closing.
