### ISSUE TITLE
Ability to pull alternative LDAP/Okta attribute for givenName, SurName, Email, Country Code

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#322]
Customer requested for UST to pull alternative field for givenName.

**Comment by adobeDan** [comment]
Let's try to get your PR for this into 2.3.

**Comment by bhunut-adobe** [comment]
@adobeDan - When do you expect to release 2.3?

**Comment by adobeDan** [comment]
end of Jan, with another RC beginning of next week.
