### ISSUE TITLE
MemberOf or IsMemberOf is not available on LDAP server

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#323]
We have a couple of customers whose LDAP directory does not have MemberOf or IsMemberOf or similar virtual attribute enabled or supported on the LDAP server.

For UST to work for these customers, We will need to do 2 steps lookup.

We will need to look for Group object for group membership then take group membership DN and do a second lookup for Person object.

I believe pre UST 2.0 didn't utilize memberOf attribute. Is there a way to do this for the current version?

**Comment by bhunut-adobe** [comment]
@adobeDan  I added a feature to UST to support two-steps lookup. What do you think?
https://github.com/bhunut-adobe/user-sync.py/commit/3520590294a66a80c9c4050e19701d080ed884b2

**Comment by adobeDan** [comment]
Yes, this is worth doing for those few people who don't have the memberOf extension loaded.  Look at the comments I left on your commit and make those changes before you create a PR.  Also you'll need to update the actual docs; work with Phil on that.

One of the issues here is that some systems don't put the dn in the attribute, they put the oid (especially for uniqueMemberOf).  We don't collect or keep OIDs anymore, so there's no way to look up by that.  You might want to think about whether there's an easy way to go from the OID to the DN.

**Comment by phil-levy** [comment]
For documentation, you can add a section to the chapter on random topics (in the User Manual, section Advanced Configuration).  Just add a section at the end called "Special Configuration If IsMemberOf Is Not Available on Your LDAP Server".  The file is 
https://github.com/adobe-apiplatform/user-sync.py/blob/v2/docs/en/user-manual/advanced_configuration.md
(but in your fork).

**Comment by adobeDan** [comment]
@bhunut-adobe I'd like to get 2.3 out sometime in the next week or two.  Do you think you'll have a chance to get this done?  If not it will have to wait for 2.3.1.

**Comment by tobiasbp** [comment]
@adobeDan : Any news on a 2.3 release with this feature added?

**Comment by thong1github** [comment]
Is this feature still under development, or will it remain unsupported?  @adobeDan @bhunut-adobe
