### ISSUE TITLE
Adding '--process-groups' doesn't override the default

### ISSUE THREAD

**Issue by madumro** [adobe-apiplatform/user-sync.py#325]
If 'process-groups' is set to 'No' inside 'user-sync-config.yml' file, adding '--process-groups' to the command line doesn't override the default value. (v2.3.rc3)

**Comment by adobeDan** [comment]
Certainly sounds like a bug.  Thanks for the report!

**Comment by adobeDan** [comment]
Yikes!  The same is true of --update-user-info!
