### ISSUE TITLE
Build Pex Error - The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by bajwa-adobe** [adobe-apiplatform/user-sync.py#331]
I am getting following error when i am making pex (windows 10). Odd enough it still create user-sync.pex with this error.

I am running as administrator and no other python process running. I checked C:\\Users\\user\\AppData\\Local\\Temp\\tmpcjmbyavj\\ was created by this build and was not used by any other process. Any Idea!

```
pex: Building pex: 32232.6ms
pex:   Resolving distributions: 31394.7ms
pex:       Packaging user-sync: 9276.8ms
pex:       Packaging pywin32-ctypes: 1823.8ms
pex:       Packaging PyYAML: 838.4ms
pex:       Packaging pycparser: 1283.0ms
Saving PEX file to dist/user-sync.pex
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\proj\github\user-sync.py\venv\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpcjmbyavj\\chardet-3.0.4-py2.py3-none-any.whl'
```

**Comment by adobeDan** [comment]
Yeah, this is actually a known issue with Windows builds, where the temporary directories are removed before the file references into them are closed.  It doesn't always happen, especially with the first build after boot.  It's harmless, and the pex files are always fine.  I might experiment with adding a delay in the build script to see if we can avoid it completely.

**Comment by bajwa-adobe** [comment]
Thanks, the user-sync.pex seems to work ok.

**Comment by adobeDan** [comment]
Reopening this so we don't lose track of it.

**Comment by adobeDan** [comment]
After investigation this has to do with the innards of pex and we can't do anything about it.
