### ISSUE TITLE
users deleted in AD Groups aren't deleted in Management Console

### ISSUE THREAD

**Issue by Whitebeer1337** [adobe-apiplatform/user-sync.py#341]
at the moment there is an issue when a user is deleted from the corresponding AD Group the user-sync.py doesn't delete him from Management-Console even the assigned products persists and count as a used license.

**Comment by Luci2015** [comment]
What version of the tool are you using and what command line did you use?
You should also check if that being excluded (check log file for 'excluding' keyword) if you're using debug mode.

**Comment by Whitebeer1337** [comment]
we use the version 2.2.1 along with Powershell.
python user-sync.pex --users mapped --process-groups --adobe-only-user-action exclude
the problem was the last param within an compiled .exe file.
Sorry for any inconvenience - the issue can be closed :(
