### ISSUE TITLE
I want to select users in a nested group.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#344]
I would like to link users associated with nest groups to product profiles, but it will not work.

You might have a group nesting structure like this:

Group shiten
  Group oosaka
         User1@aooo.online

The configuration file is described as follows.

・connector-ldap.yml
group_member_filter_format: "(memberOf:1.2.840.113556.1.4.1941:=cn=shiten,dc=aooo,dc=online)"

・user-sync-config.yml
  groups:
    - directory_group: "shiten"
      adobe_groups:
        - "UST Test"

Run command
↓
python user-sync.pex --users all --user-filter User1@aooo.online --process-groups --adobe-only-user-action exclude

But User1@aooo.online not added to adobe group UST Test.

Could you please confirm it?

**Comment by bhunut-adobe** [comment]
@Tomomi99145  please set group_member_filter_format to 
`group_member_filter_format: "(memberOf:1.2.840.113556.1.4.1941:={group_dn})"`

UST will automatically fill {group_dn} with the group dn by doing a lookup of the CN from  directory_group in user-sync-config.yml


`

**Comment by Tomomi99145** [comment]
Thank you for your reply.
group_member_filter_format is set.

・connector-ldap.yml
group_member_filter_format: "(memberOf:1.2.840.113556.1.4.1941:=cn=shiten,dc=aooo,dc=online)"

But The user is registered, but it is not added to adobe group.
Is the Described contents incorrect?

**Comment by Tomomi99145** [comment]
I tried again and added it.
thank you for your advice.
Please close this Case.
