### ISSUE TITLE
Disable User Account in Enterprize AD.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#346]
Will it be synchronized when I disable a user account in Enterprise AD?

**Comment by Luci2015** [comment]
yes, with the next run of the script

**Comment by Tomomi99145** [comment]
Will disabled users be deleted with the next run of the script?

**Comment by bhunut-adobe** [comment]
@Tomomi99145  - No, not with the default UST parameter. See --adobe-only-user-action parameter for more details on the available actions. https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/command_parameters.html

**Comment by Tomomi99145** [comment]
thank you for your advice.
Please close this Case.
