### ISSUE TITLE
extension-config.yml requiring optional fields

### ISSUE THREAD

**Issue by Donrwalsh** [adobe-apiplatform/user-sync.py#348]
When running UST with the extension file, I am unable to proceed if either the extended_adobe_groups or extended_attributes fields are omitted. These fields are labeled as optional and the file gives every indication that UST should be able to run without them. 

I have included example output for when either field is omitted after which the UST will immediately end its run.

2018-03-30 12:52:27 2704 CRITICAL main - Value not found for key: extended_adobe_groups in: extension

2018-03-30 12:54:03 1196 CRITICAL main - Value not found for key: extended_attributes in: extension

Thanks!

**Comment by adorton-adobe** [comment]
You'll need to set them to empty lists.

```yaml
extended_adobe_groups: []
extended_attributes: []
```

**Comment by adorton-adobe** [comment]
@adobeDan Should we treat this as a bug?  If these fields are optional, we should set their defaults (either None or empty list objects) in the config module so they can safely be commented out.

**Comment by adobeDan** [comment]
The intent was for the extension: field in the main file to be optional, rather than fields in the extension spec.  I'm fine treating this as a bug, however, please go ahead and updated the parser to specify default values.
