### ISSUE TITLE
Admin Console User Sync Tool - VM sizing recommendations required for 8K concurrent users and 40K users overall

### ISSUE THREAD

**Issue by herminator2008** [adobe-apiplatform/user-sync.py#349]
Hi,

What are the Admin Console - User Sync Tool recommendations for a sizing a new VM Server running Windows Server 2016 for RAM/CPUs/Disk Space (for log files, etc) for 8K concurrent users and 40K total users so there are no performance issues when synching users on a daily basis.

**Comment by bhunut-adobe** [comment]
User Sync Tool is very lightweight. The tool it self is less than 20MB. I would say the minimum OS requirement with 4 GB of ram should be more than enough.
