### ISSUE TITLE
UST gets stuck to "Building work list..."

### ISSUE THREAD

**Issue by madumro** [adobe-apiplatform/user-sync.py#350]
Hi,

After the LDAP connection is established, the UST gets stuck to "Building work list...". The tool worked properly until 2 weeks ago. 
There is no error message, the log ends with these lines:
2018-04-30 08:32:22 2986 INFO processor - ---------- Start Load from Directory -----------------------
2018-04-30 08:32:22 2986 DEBUG processor - Building work list...

I can't figure out what could be the issue.  I tried:
./user-sync --process-groups --users mapped
./user-sync --process-groups --users group group_name

The LDAP queries are the default ones:
all_users_filter: "(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))"
group_filter_format: "(&(|(objectCategory=group)(objectClass=groupOfNames)(objectClass=posixGroup))(cn={group}))"
group_member_filter_format: "(memberOf:1.2.840.113556.1.4.1941:={group_dn})"

Can anyone suggest a possible reason for this issue?

Thanks!
Madalina

**Comment by bhunut-adobe** [comment]
Madalina,

Can you try group_member_filter_format: "(memberOf={group_dn})" and see if it will go through? I have seen AD query get hang up when using this filter "(memberOf:1.2.840.113556.1.4.1941:={group_dn})"

**Comment by madumro** [comment]
Thank you, @bhunut-adobe! That was the issue indeed, but it was in 2.2.1 version, so we'll upgrade the tool and test it again. I'll update this issue afterwards. Thanks again!

**Comment by bhunut-adobe** [comment]
@madumro If you are still having the issue, please feel free to reopen this issue.
