### ISSUE TITLE
Pex upgrade to 1.4.0 breaks build script

### ISSUE THREAD

**Issue by Donrwalsh** [adobe-apiplatform/user-sync.py#354]
About 14 hours ago pex released an upgrade to 1.4.0 from 1.3.2. The makefile does not specify a version of pex, and so it downloads the new version which is breaking. Making a fresh pex build on Windows 10 results in a pex file that will run, but fails immediately with the following output:

```bash
$ python user-sync.pex -t
Failed to execute PEX file, missing win_amd64-cp-36-cp36m compatible dependencies for:
pywin32-ctypes
keyring
user-sync
```
A similar issue is happening when we try to build it on Linux.

We were able to fix this by modifying the makefile to specifically call out version 1.3.2 for pex:

<code>pip install --upgrade 'wheel<0.30.0' requests pex==1.3.2</code>

Thanks!

**Comment by janssenda-adobe** [comment]
For reference, here is a link to the release notes for 1.4.0.  It's not clear what the root issue is based on them:
https://github.com/pantsbuild/pex/releases/tag/v1.4.0

**Comment by adorton-adobe** [comment]
@janssenda-adobe @Donrwalsh Is this still an issue?  It seems like pex got a recent update - did that resolve the issue?
