### ISSUE TITLE
Groups not found on Adobe side?

### ISSUE THREAD

**Issue by tobiasbp** [adobe-apiplatform/user-sync.py#358]
I can not look up memberships of groups on my openLDAP-server, because i do not have the needed overlay installed. As a hack, I keep the users' adobe license to be granted in the field (l) (The location field).
The possible values are:
adobe-acrobat-pro-dc
adobe-creative-cloud-all-apps

To read the field (l) and map it to group (licenses) I have added the following to extension-config.yml:

```
extended_attributes:
  - l
```

Here, I'm using the product names as they appear in the Adobe Console GUI
```
extended_adobe_groups:
  - Acrobat Pro DC
  - Creative Cloud All Apps
```

```
after_mapping_hook: |
  adobe_group = source_attributes.get('l')
  if adobe_group == 'adobe-acrobat-pro-dc':
    target_groups.add('Acrobat Pro DC')
  if adobe_group == 'adobe-creative-cloud-all-apps':
    target_groups.add('Creative Cloud All Apps')
```

Running user-config with:
process_groups: yes

When I run user-sync, I get errors like these for alle users:
```
2018-05-28 11:16:40 1 INFO processor - Managing groups for user key: adobeID,tbp@example.com, added: {'acrobat pro dc'} removed: set()
2018-05-28 11:25:45 1 ERROR umapi.action - Error in requestID: action_52 (User: {'user': 'tbp@example.com', 'useAdobeID': True, 'requestID': 'action_52'}, Command: {'add': {'product': ['acrobat pro dc']}}): code: "error.group.not_found" message: "Group acrobat pro dc was not found"

```

I don't understand what the problem is. user-sync seems to pick up my configuration, but the Adobe side does not appear to know the license group.

I have nothing configured under "groups:" in user-config.yml.
I have nothing configured for "group_filter_format:" in connector-ldap.yml

I'm unsure what role the above plays, since I don't use the groups in LDAP at all.

Any suggestions?

**Comment by Luci2015** [comment]
I think you picked up the names from the left-most menu, not the actual name of the PLC.

This would be the direct way to entitle users, but you can do it through user-groups too:
Go users -> user-group 
create there a group or two (like  "acrobat" and "cc all apps") then use these exact names in your config file
If you want to get users entitled to PLCs, you just need to add the PLC to the user-group itself via Assigned Product Profiles menu .

**Comment by tobiasbp** [comment]
I think you are right. However, I can not find any 'real name' for 'products'. I can click 'details', and the I get a list which Adobe products can be used with the license.

I have created a new group. I can add users, but I see no way to add licenses to the group?

**Comment by Luci2015** [comment]
when you click Products, you have on the left side the names of the available ones. When you click on one of them on the right side of the  screen you could see details of available Product Profiles. Use the exact name from there, either to map the LDAP group to it, either to add it to the user-group to entitle everyone there.

To add to user-groups: click the user-group name, then click Assigned Product Profiles, then Assign Product Profile button to the right, then click the product on the left side (ex: Acrobat Pro DC), then from the drop-down of "Add product profiles to user group" select the available one you wish to add to everyone.

**Comment by Luci2015** [comment]
Note: if you do not have any product profile associated, you need to create one or more, depending on your needs. If you need help with that I think opening a ticket with Enterprise Support would be best.

**Comment by tobiasbp** [comment]
> when you click Products, you have on the left side the names of the available ones.
Yes, a list of products on the left side. One is "CREATIVE CLOUD ALL APPS".

>  When you click on one of them on the right side of the screen you could see details of available Product Profiles.

Clinking on "CREATIVE CLOUD ALL APPS" on the left side of the screen does nothing. The only things I can do are:

- Add licenses
- Add user

I do not have an enterprise account. Is it needed?

**Comment by Luci2015** [comment]
Maybe yours is a product admin account and not a system account, can't say for sure.
Check if you have a support menu in Admin console and follow through with Adobe support for more help on creating product profiles or assign them to groups, or find someone in your organisation that can do that for you.
Looks like this is no longer an issue related to this tool's functionality.

**Comment by tobiasbp** [comment]
> Looks like this is no longer an issue related to this tool's functionality

Agreed. But, maybe the documentation should mention what naming to use when referring to products?

**Comment by tobiasbp** [comment]
Enterprise account is needed for synchronization of groups as mentioned (hinted to?) in the[ documentation](https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/setup_and_installation.html#create-corresponding-groups-in-your-enterprise-directory).

> Before you start configuring User Sync, you must know what Adobe products your enterprise uses, and what product configurations and user groups are defined in the Adobe User Management system. For more information, see the help page for configuring enterprise services.
