### ISSUE TITLE
Include jpegPhoto or thumbnailPhoto field from LDAP in sync

### ISSUE THREAD

**Issue by wesleyan-ablackburn** [adobe-apiplatform/user-sync.py#359]
I wasn't sure where to post this. This is more of a feature request than an issue.  Our organization uses the jpegPhoto and thumbnailPhoto attributes in our AD to store user photos.  This ends up with nice photos in our Office 365 infrastructure, most importantly in our email.  Right now, we just have the generic gray and white silhouette for our users in Creative Cloud. Would it be possible to sync one of those fields to the Adobe UMAPI for the account's photo?

I believe both fields are base64 encoded JPEGs. I was thinking about potential issues... If implemented, this could potentially increase the time it would take to sync large amounts of users.  I am also unsure of the requirements on the user-side of Creative Cloud for profile photos.  I know that Microsoft recommends a 24-bit JPEG and a 1:1 ratio (~648x648) on the photo for Office 365.

**Comment by adobeDan** [comment]
There are no UMAPI server-side APIs for managing user profile information for federated accounts other than the user's name, email, username, and country.  But there may be Adobe APIs other than the UMAPI that you could access to do this.  I will send a separate email referencing this issue to the product management that handles the Admin Console and the UMAPI.  They may reach out to you directly for more information.

**Comment by NealMirchAdobe** [comment]
@wesleyan-ablackburn - The Adobe Admin Console product management team would like to learn more about your AD setup and the feature request for Adobe User Profile photo management in the Admin Console/Create Cloud.  Please reach out to me via email at mirchand@adobe.com or let me know the best way to contact you.  

Thank you,
Neal Mirchandani

**Comment by wesleyan-ablackburn** [comment]
Thanks, @adobeDan.  I appreciate the quick response.

@NealMirchAdobe, I will reach out to you via email.  Thank you!

**Comment by Kromatix1987** [comment]
Just wondering if anything came of this? Is there a suitable solution for syncing photos?

Thanks in advance =D

**Comment by jameslockman** [comment]
There remains no way to push avatars to the Adobe Admin Console.

**Comment by Kromatix1987** [comment]
Ok, thanks for the update!
