### ISSUE TITLE
Please tell me the information on the endpoint.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#361]
I am considering using UserSyncTool via proxy.

Please tell me the information on the endpoint which is necessary to allow communication.

**Comment by adorton-adobe** [comment]
Some proxy types are supported using the HTTP_PROXY and HTTPS_PROXY environment variables.  This is a feature of the Python requests library, and not the umapi-client or User Sync Tool.  See the [requests documentation](http://docs.python-requests.org/en/master/user/advanced/#proxies) for more information.

**Comment by bhunut-adobe** [comment]
@Tomomi99145  - Endpoint are https://ims-na1.adobelogin.com and https://usermanagement.adobe.io
