### ISSUE TITLE
using adobe-only-user-list does not work

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#365]
tried it on version 2.3rc4.
I think it stopped working since the invocation_defaults got added.
The invocation_defaults also provides this option, but it keeps the 'users' argument as well, so it conflicts.

In v2.2.2 this works.

**Comment by adorton-adobe** [comment]
Thank you for the report.  I will take a look.

**Comment by adorton-adobe** [comment]
Fixed by #370
