### ISSUE TITLE
Disable error No country code 

### ISSUE THREAD

**Issue by perris-king** [adobe-apiplatform/user-sync.py#380]
It would be great to be able to stop these warnings when the User Sync Tool runs:

5416 WARNING ldap - No country code attribute (c) for user with dn: 

I would like to continue running UST with file_log_level set to info. My company's AD doesn't fill in a country code. This information doesn't provide any insight and just fills up the logs.

**Comment by Luci2015** [comment]
I guess you don't have other option than to clone the source code locally and modify the user-sync/connector/directory_ldap.py to no longer log this to file, then build your own .pex using 'make' after setting up your environment.

There might be a way to mass update the country code in your AD, using PS scripts. 
Found one [here](https://social.technet.microsoft.com/Forums/en-US/150efc60-0565-4a57-a48a-45140f9fc2a3/updating-country-in-active-directory?forum=winserverDS), using a CSV file as input that contains all your users to be updated.

**Comment by perris-king** [comment]
In user-sync-config.yml I set:
`default_country_code: US`

**Comment by adorton-adobe** [comment]
I think it could be very useful to have a generic, configurable way to suppress certain warnings.  I'm closing this issue and tracking that feature in #388.

**Comment by adorton-adobe** [comment]
@perris-king - I have a solution you can try while we figure out how we want to move forward with warning suppression.

In `connector-ldap.yml`, set `user_country_code_format` to "US".  It's normally set to "{c}" which inserts the value of the "c" attribute from the directory.  You can find it on line 167 in the example config.

https://github.com/adobe-apiplatform/user-sync.py/blob/v2/examples/config%20files%20-%20basic/3%20connector-ldap.yml#L167

**Comment by perris-king** [comment]
That worked great. The logs still captured the INFO messages without the unnecessary country code warnings. Thanks!
