### ISSUE TITLE
Create messages ids for UST messages/error strings

### ISSUE THREAD

**Issue by bajwa-adobe** [adobe-apiplatform/user-sync.py#391]
Currently the User Sync tool has hard-coded message strings which need be assigned message ids and then these message ids can be used for localization or suppress certain warnings or print part of log output.  

I had collected list of warning/error/critical strings which will be assigned message ids and used for localization. [UST Errors Conditions.pdf](https://github.com/adobe-apiplatform/user-sync.py/files/2345190/UST.Errors.Conditions.pdf)

#388 Suppress certain warnings by message ids

**Comment by adorton-adobe** [comment]
Let's shelve this for now. Message IDs aren't necessary for localization as far as I know, and there is probably a simpler way to address log message suppression.
