### ISSUE TITLE
missing win_amd64-cp-37-cp37m

### ISSUE THREAD

**Issue by trevorsmith99** [adobe-apiplatform/user-sync.py#395]
What is causing this error.

C:\pex>python ./user-sync.pex
Failed to execute PEX file, missing win_amd64-cp-37-cp37m compatible dependencies for:
pyyaml
psutil
cffi
cryptography
umapi-client
pycryptodome
pyldap
user-sync

**Comment by adorton-adobe** [comment]
We don't provide a Windows build for Python 3.7 at this time - see #376.  The latest stable Windows Python 3.6 release was built on 3.6.5, but 3.6.6 ought to also work.  You can find older versions here: https://www.python.org/downloads/

You can also use our [quick install script](https://github.com/adobe/UST-Install-Scripts), which will download and install the required Python release.  If you want to install it manually, make sure you get the win64 release.
