### ISSUE TITLE
LDAP error when running user-sync-v2.4rc1-win64-py2715 

### ISSUE THREAD

**Issue by madumro** [adobe-apiplatform/user-sync.py#396]
Hi,

I've tested the new pre-release (2.4rc1) on Windows, with Python 2.7.15 and 2.7.13 and got this error:
"Unexpected LDAP failure reading group members: All provided fields *must* be text when bytes mode is off; got ‘memberOf’".
The version for Python 3.6 runs without issues, with the same configuration files.
Is this a known issue?

Thanks!

**Comment by adorton-adobe** [comment]
This is a bug introduced in 2.4rc1.  Use Python 3.6 for now.  It will be resolved in the next 2.4 release.
