### ISSUE TITLE
Wewants to map email from "Other Email " under organization Tab under user profile in AD.

### ISSUE THREAD

**Issue by gasingh02** [adobe-apiplatform/user-sync.py#399]

**Comment by gasingh02** [comment]
When we are using the default command , it is giving error . Log file shows the error ( Empty email Attributes) . It seems that api is trying to map the attributes from Email section under the user profile which is blank in our case . 
We need that the api should pull up the email from other email section under Organization Tab in User profile on AD.

**Comment by adorton-adobe** [comment]
Just override the `user_email_format` option in `connector-ldap.yml` with the field you want to use for the primary email identifier.  Make sure you leave the curly braces in place so the field value can be dynamically inserted into the string.

https://github.com/adobe-apiplatform/user-sync.py/blob/v2/examples/config%20files%20-%20basic/3%20connector-ldap.yml#L118

**Comment by adorton-adobe** [comment]
@gasingh02 Were you able to update the config to pull in a different email ID attribute?  Am I OK to close this issue?

**Comment by gasingh02** [comment]
Hi Andrew ,

Yes , thanks a lot , it worked .


Thanks and Regards
Gaurav Singh | Senior Technical Support Consultant, Customer Care | Customer & Employee Experience | Adobe Systems |
gasingh@adobe.com<mailto:gasingh@adobe.com>
