### ISSUE TITLE
Please tell me about the execution environment.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#404]
Is there a limitation that User Sync tool does not work with 32 bit?
The following error occurred when executed.

>python user-sync.pex -v
Failed to execute PEX file, missing compatible dependencies for:
pyldap
pycryptodome
cryptography
cffi
pyyaml
psutil
umapi-client
user-sync

**Comment by adorton-adobe** [comment]
Python 64bit (2.7 or 3.6) is required on Windows.  We don't provide builds for win32.
