### ISSUE TITLE
error.user.belongs_to_another_org" message

### ISSUE THREAD

**Issue by Olivier75016** [adobe-apiplatform/user-sync.py#407]
Hello,

I am implementing user-sync and I encounter this error while processing tests to create an user:

"error.user.belongs_to_another_org" message: "Illegal to invite user from another organization's owned auth src"

In the logs, I can see that the system finds users correctly in Active Directory and Adobe Console (users have an AdobeID account).

Thanks for help.

**Comment by bajwa-adobe** [comment]
As per [documentation](https://adobe-apiplatform.github.io/umapi-documentation/en/api/ErrorRef.html), the error indicates the specified user belongs to a different organization and cannot be accessed.

If you are adding the user as Enterprise or Federated ID, you need to have the user's email domain claimed & configured in your Adobe Admin Console.

**Comment by Olivier75016** [comment]
Hi,

Thanks for you answer. I am adding the user as Enterprise ID, but where can I configure the domain in the Adobe Admin Console ? Is there a specific license level to access this feature?

**Comment by bajwa-adobe** [comment]
Yes, you would need to claim & configure the domain in the Adobe Admin Console. Please read more documentation from [here](https://helpx.adobe.com/enterprise/using/set-up-identity.html#Setup-domains).

**Comment by Olivier75016** [comment]
![settings](https://user-images.githubusercontent.com/43536579/45959169-c90ace00-c008-11e8-9e91-5274ca7f12ea.png)

I started to read the doc but I am stopped at first step because I do not have the ability to create the directory as shown in the doc.

**Comment by jameslockman** [comment]
Do you have an Enterprise Admin Console? If you have Teams or VIP (without Enterprise products), then you will not have access to the necessary controls.

**Comment by Olivier75016** [comment]
It seems I have a VIP account with Acrobat Pro DC. How can I verify if it an Enterprise Admin Console or standard.
Do you know if it is possible to migrate to an Enterprise account ?

**Comment by jameslockman** [comment]
Yes, but you’ll need to talk with your reseller about adding Enterprise licenses to your VIP agreement.

**Comment by Olivier75016** [comment]
I had a feedback from my reseller, we can upgrade our licences only at the anniversary date. So we have to wait some months to do  that and after I will be able to configure the domain in the console interface.

Thanks all.
