### ISSUE TITLE
Please tell me about using G Suite.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#408]
Can I sync users from G Suite using user sync tool.
Also, are there usecases?

**Comment by cosmin-balanoiu** [comment]
The tool supports an LDAP or an Okta Directory connection. AFAIK G-Suite does not provide an LDAP service so there is no direct way of connecting the tool to G-Suite to pull the users.
The option would be to connect G-Suite to a third party LDAP service and connect the tool to that or export the users from G-Suite to csv and feed the tool the csv file as the user source - the tool can handle that.

HTH!

**Comment by phil-levy** [comment]
Another thing to consider is driving UST from a file.  You would need to export the G Suite data into a file of appropriate format and then run UST using that file as input.  You would have to decide if that is an acceptable and useful workflow for your situation.

**Comment by Tomomi99145** [comment]
@cosmin-balanoiu @phil-levy 
Thank you for answering my question.
I understand.

**Comment by Tomomi99145** [comment]
Please tell me about using G-Suite again.

>The option would be to connect G-Suite to a third party LDAP service and connect the tool to that or export the users from G-Suite to csv and feed the tool the csv file as the user source - the tool can handle that.

Is there a usecase to connect G-Suite by connecting to a third party LDAP service.
Also, is it free to use third party LDAP service?
I would like to know if there are usecase using it for free.

regards,
