### ISSUE TITLE
Command for Proceed when errors occur?

### ISSUE THREAD

**Issue by RocRaider** [adobe-apiplatform/user-sync.py#411]
Is there a switch that will allow the script to continue to run when an error occurs creating a single account? I have around 50,000 users that need to be synced. I am finding issues here and there with some of the user accounts but to find the accounts with issues I have to run the tool and then wait for several thousand to process until it finds a user with an error and then fails. I then make changes to the account and run it again. I would like to be able to identify all accounts at once that are going to have issues instead of one by one. I am looking here [Link](https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/command_parameters.html) but am not able to find anything to that effect.

Also, the error that I am getting is the following. I have compared the users attributes in Active Directory and nothing seems to be jumping out that would make this account different than the rest. 

**Command:** c:\Scripts\Adobe_Sync>"C:\Program Files\Python36\python.exe" "C:\Scripts\Adobe_Sync\user-sync.pex" -t --users mapped --process-groups --adobe-only-user-action remove

**Error:** Error creating umapi Action: "USERNAME001" Illegal email format (must be ascii, unquoted, with no comment part)

Any thoughts??? 

I appreciate any input.

**Comment by bajwa-adobe** [comment]
I have encountered same error when an Active Directory user object was not configured with correct UserPrincipalName. Please check user's identity (UPN or email) format is ok.

Following is how it appeared incorrect in my AD, the UPN was BLANK:
![image](https://user-images.githubusercontent.com/28625684/46352595-1bc03780-c652-11e8-82d3-27e84b39baf3.png)

I fixed it by supplying correct value of UPN to the user in AD's attribute editor. 

This is CRITICAL error, illegal format error might indicate bigger issue with Enterprise Directory setup than simply an issue with some users.

**Comment by RocRaider** [comment]
Agreed on the cause of the error. I had a coworker correct the error before I got to it so I was under the assumption it was a false positive. Thank you for you comment. 

Still am wondering if there is a way to suppress the errors until the end and give a report of accounts with issues? Just a wish.

**Comment by bajwa-adobe** [comment]
Glad to be of help. 

I am working on similar but not fully relevant feature (#388) to suppress warnings such as skipping user with empty email attribute.

**Comment by adorton-adobe** [comment]
This isn't an issue of warning suppression.  The issue is related to how certain UMAPI action errors are reported.  It's something we're looking into.

**Comment by adorton-adobe** [comment]
We've got a fix that will resolve this issue.

https://github.com/adobe-apiplatform/user-sync.py/pull/421
