### ISSUE TITLE
Failed to authenticate provided token

### ISSUE THREAD

**Issue by tsenesi** [adobe-apiplatform/user-sync.py#412]
We have a script for managing our user and our licenses, but we recently encountered a new error that was not happening before.
The script start with a request to generate a new access token for the next api calls, this succeed and we receive an access token. But when we use our fresh access token to retrieve information from the api, like groups or users, we have a '401 Unauthorized' error with the body '{"lastPage":false,"result":"error.unauthorized","message":"Failed to authenticate provided token"}'.
The token provided for the request is the token we retrieve just before, with no alteration between the two api calls. I would like to know what could cause that error, if something changed recently with the api to cause this comportment since this script worked before ?
We are not using "user-sync.py" but directly the REST user management API described here: https://adobe-apiplatform.github.io/umapi-documentation/en/

**Comment by adorton-adobe** [comment]
This is a known issue with older integrations.  You will need to create a new integration with a new keypair.  You should not experience this issue again with the new integration.
