### ISSUE TITLE
How to set different values for "email address" and "SSO Username"

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#419]
I want to sync Active Directory "UPN" to Admin Console "SSO Username" and Active Directory "mail" to Admin Console "email address".
How do I configure it?

**Comment by adorton-adobe** [comment]
You can currently only set both the Adobe username (email ID) and the email address to the same field (`user_email_format` in the LDAP config).  There is a pending update that will allow users to have different email IDs and email addresses.  See #385.
