### ISSUE TITLE
About specifiy of users to select for sync.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#420]
I want to specify the users to be selected for sync. 
For example,
Can I sync only users seted as "1" in attribute value "Department".
Best regards.

**Comment by adorton-adobe** [comment]
You should be able to add any additional LDAP filters to the `all_users_filter` field in `connector-ldap.yml`.

It might look like this:

`all_users_filter: "(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(Department=1))"`
