### ISSUE TITLE
Support for gMSA service accounts

### ISSUE THREAD

**Issue by SotoDucani** [adobe-apiplatform/user-sync.py#424]
Will be getting this setup in the next week or so for our environment. Planning on using following versions:
- Python 3.6.7
- v2.3 release of the User Sync Tool
- Setup on Server 2012R2

Is it known already if the tool is able to authenticate with Microsoft gMSA accounts? The account type does not use an explicitly typed or stored (credential manager) password, so I'm thinking that it will error out on the lack of both a password and secure_password_key in the connector-ldap.yaml file. Confirmation either way would be great if it's known, otherwise I'll report back after I give it a shot.

Thanks!

(See https://blogs.technet.microsoft.com/askpfeplat/2012/12/16/windows-server-2012-group-managed-service-accounts/ for a quick reference on gMSA accounts if needed)

**Comment by Luci2015** [comment]
AFAIK, the tool uses Keyring module to retrieve the pass. 
From PyPi, [these](https://pypi.org/project/keyring/#what-is-python-keyring-lib) are currently supported by Keyring. So, for Windows you get Windows Credential Locker support, ([here](https://docs.microsoft.com/en-us/windows/uwp/security/credential-locker))
It does not look like it supports extracting pass for gMSA accounts, so it will likely happen what you thought.
You can wait for some other opinions, in case someone else bumped into this; I, for one, never saw such a config.

On the other hand, the ldap requirement from the config file is just to have an account that can connect to the LDAP and make an extraction of all users from given base_dn, in read-only mode. 
Can't this be set up to create such an account to do the extraction and have the gSMA account only to run the task scheduler?

my two cents...

**Comment by SotoDucani** [comment]
That was my fear, haven't been able to find any indications of gMSA account support.

While technically your suggestion would still be beneficial where the account with actual service-running privs would be the gMSA account, there would be the added administrative overhead of a second normal domain user account that needs to be treated like a service account. I'm still debating with myself if that's a big enough security difference to be worth it.

**Comment by Luci2015** [comment]
It's good to have this confirmation! Now there's a documented case for this situation, thanks to you.

**Comment by adorton-adobe** [comment]
We need to ensure that LDAP access is generic and works for a wide variety of LDAP systems.  I also don't see any support in the python-ldap or ldap3 libraries for gMSA accounts.  Thank you the report, but I am going to close this issue.
