### ISSUE TITLE
python user-sync.pex results in No such file or directory:

### ISSUE THREAD

**Issue by rxscorp** [adobe-apiplatform/user-sync.py#427]
IOError: [Errno 2] No such file or directory: u'D:\\LocalApp\\PEX\\install\\pycryptodome-3.4.7-cp27-cp27m-win_amd64.whl.c20a228544d59e16340bfd63bc777419e4da04ff.9ce25fe6dd504fb5870dfad545e3e38d\\pycryptodome-3.4.7-cp27-cp27m-win_amd64.whl\\Crypto/SelfTest/PublicKey/test_vectors/ECC/ecc_p256_private_ enc_aes128.pem'

Now if you drill down the folder path the file ecc_p256_private_ enc_aes128.pem does not exist. 
Only below files exist
ecc_p256
ecc_p256_private
ecc_p256_private.pem

I have tried several python versions (3.7, 3.6 and 2.7) and user-synx.pex versions (relation to python version) all giving the same/similar error

**Comment by bhunut-adobe** [comment]
@rxscorp Due to windows file path length limit of 260 characters you will need to shorten the file path.  Set your System Environment Variable for PEX_ROOT to D:\PEX

**Comment by adorton-adobe** [comment]
If you're running Server 2016, you can also override the 260 character limit with a group policy update.

https://www.saotn.org/ntfs-long-paths-windows-server-2016-gpo/
