### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED ... (_ssl.c:748)')

### ISSUE THREAD

**Issue by HUKJXG01** [adobe-apiplatform/user-sync.py#433]
While trying to execute the Adobe user sync tool, i came across the above error.
My installation:  python 3.6.2,   User Sync version: 2.3rc4 on Windows server 2012

Having checked the suggestion from Adobe (https://helpx.adobe.com/enterprise/kb/UMAPI-UST.html), i had created the environment variable REQUESTS_CA_BUNDLE and placed the .pem file in the same location in the user_sync_tool folder.
Sequence of events:
1.  initially getting https://usermanagement.adobe.io/v2/usermanagement failed
: HTTPSConnectionPool(host='ims-na1.adobelogin.com', port=443).  Routed via a proxy to overcome this issue
2. then the next error that occurred was ERROR main - Unhandled exceptionTraceback ... ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748) and a whole string of messages, so i applied the "fix" and created the environment variable REQUESTS_CA_BUNDLE as mentioned above with the .pem file.  After running it again, the error messages were a lot less, as shown below, but i'm still getting the SSL: CERTIFICATE_VERIFY_FAILED ... (_ssl.c:748)')

**Logs below**
C:\Users\<userID>\user_sync_tool>python user-sync.pex -t --users mapped --process-groups --adobe-only-user-action exclude
2018-12-07 15:38:05 8052 INFO config - Using main config file: user-sync-config.yml (encoding utf8)
2018-12-07 15:38:05 8052 INFO main - ========== Start Run (User Sync version: 2.3rc4) ===========
2018-12-07 15:38:05 8052 INFO main - ------- Command line arguments -------
2018-12-07 15:38:05 8052 INFO main - -t --users mapped --process-groups --adobe-only-user-action exclude
2018-12-07 15:38:05 8052 INFO main - -------------------------------------
2018-12-07 15:38:06 8052 CRITICAL main - Connection to org <ID>@AdobeOrg at endpoint https://usermanagement.adobe.io/v2/usermanagement failed: HTTPSConnectionPool(host='ims-na1.adobelogin.com', port=443): Max retries exceeded with url: /ims/exchange/jwt (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)'),))2018-12-07 15:38:06 8052 INFO main - ========== End Run (User Sync version: 2.3rc4) (Total time: 0:00:00)

Apparently it is getting to the Adobe server, but it's in a "tunnel" and can't see much else

**Comment by Luci2015** [comment]
Hello again!
This is because your proxy does SSL inspection. 
The cert that your proxy is using can't be resolved with existing bundle, so I think you can do 2 things:
1) have your proxy not to inspect the traffic generated on the two endpoints we use for UM API: usermanagement.adobe.com:443 and ims-na1.adobelogin.com:443 
OR
2) obtain the CA cert in pem format that the proxy is set up with and use REQUESTS_CA_BUNDLE environment variable, giving it as value the path to that cert file, so it gets to be "trusted". You can use same "set" keyword you used for the http_proxy env variable so you'd not impact activity for others. Be sure the cert is in PEM format.

**Comment by Luci2015** [comment]
PS: I saw that you used point 2) from the above description, but I'm pretty sure the cert you are using is not the right one or is not in PEM format.

**Comment by HUKJXG01** [comment]
@Luci2015 - many thanks for the prompt replies!  i have checked the cert file - it was sent to me as .CRT, and on inspection of the contents (via notepad), it is not binary, so the file must be PEM.  I had renamed it to .PEM and placed it in the path defined in REQUESTS_CA_BUNDLE. I will check the file format again.

**Comment by HUKJXG01** [comment]
i have run openssl x509 -in <cert name>.pem -text -noout and the contents look OK - it is a PEM file.

**Comment by Luci2015** [comment]
I also use a proxy and the REQUESTS_CA_BUNDLE points to the proxy's  root CA cert. I don't have intermediate certs, but I think you need the those as well, if any.
All-in-all, this is can be fixed via setting this env variable -> it only depends on the right cert to use here, so start with your proxy's root one, in pem format

**Comment by HUKJXG01** [comment]
Thanks Luci2015!
i will check with network in case of other intermediate certs, and look at option 1 above as well.

**Comment by HUKJXG01** [comment]
i have added the root CA and all intermediate certs with REQUESTS_CA_BUNDLE pointing to them, and i have verified via OpenSSL that all the certs are indeed in PEM format. i have checked via MMC that all the root certs are covered, none excluded.  i have run the python SET command again, just to be sure REQUESTS_CA_BUNDLE is properly set.
Unfortunately, the error message is the same.
i wonder now if it is a matter of updating pip, as someone else on the forum had the SSL: CERTIFICATE_VERIFY_FAILED with c748, but it was on a MAC, but i am loathe to mess up my python set up if this was not the case.
I would not have the proxy not inspect the traffic, as this would not be permitted by security anyway.
Is there a possibility it may be the Adobe I/O API was not set up properly?
