### ISSUE TITLE
About the case when the  OU with the same name exists in AD.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#434]
Please tell me about the action of group mapping when the OU of AD is configured as below.

![image](https://user-images.githubusercontent.com/35795898/50126492-73189000-02b0-11e9-92ab-ee85cf47973b.png)

 When an OU with the same name exists in AD in Layered structure,Can I specify the group to be mapped?

I want to specify EEEEE(2nd level) and AAAAA(3rd level) recursively.

Please tell me the solution.
Reagrds,

**Comment by adorton-adobe** [comment]
The sync tool doesn't directly look at the OU.  Having a group name that shares the same common name of an OU shouldn't be a problem to my knowledge.  There isn't a way to use the OU to govern Adobe group or product profile assignment.  If the customer can't use directory groups or attributes (using the extension config), they would need to write their own script to query users belonging to various OUs and dump them to a CSV file that the sync tool could read (the OU would go into the Groups column and the sync config would map the "group" name to Adobe groups or profiles).
