### ISSUE TITLE
Runtime error with 2.4rc3-win64-py365

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#437]
I've tried the zip file for Windows and Python 3.6.5 from the latest pre-release 2.4.rc3: [user-sync-v2.3rc3-win64-py365.zip-2](url
https://github.com/adobe-apiplatform/user-sync.py/releases/download/v2.4rc3/user-sync-v2.3rc3-win64-py365.zip).
When run, it ends up in with this message:
<img width="664" alt="screenshot 2019-01-15 at 17 35 04" src="https://user-images.githubusercontent.com/14054859/51190906-f3e89d00-18eb-11e9-89cb-d96679ce2626.png">

**Comment by adorton-adobe** [comment]
I'm getting the same error as you in 3.6 and a similar error in 2.7.  Looks like it might be a bug in the pex build tool.

**Comment by adorton-adobe** [comment]
The issue is that we were using the latest version of pex to build the sync tool, which was 1.6.0 at the time.  I've set the makefile to request 1.5.3 specifically, which is the version used to build 2.4rc2.  Issue should now be resolved.
