### ISSUE TITLE
"error.internal.exceptionflys" message: "Severe exception: null" When creating new EnterpriseID user

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#44]
This error occurs when creating a new EnterpriseID user in the stage environment. I was not able to replicate this with FederatedID or in the production environment.

`ERROR dashboard.owning.action - Error requestID: action_3 code: "error.internal.exceptionflys" message: "Severe exception: null"`

The users were created successfully regarding the error message.

![image](https://cloud.githubusercontent.com/assets/26125757/23487368/6a340468-fe9a-11e6-87a2-dbaa8304abbb.png)

I ran the following command:

`./user-sync --process-groups --users group "SG-Adobe-All-App"`

[user-sync-config.txt](https://github.com/adobe-apiplatform/user-sync.py/files/812394/user-sync-config.txt)
[2017-03-02.txt](https://github.com/adobe-apiplatform/user-sync.py/files/812393/2017-03-02.txt)

**Comment by phil-levy** [comment]
Looks like this is not related to user sync.  It is a data issue with the organization on the stage environment.  Closing.
