### ISSUE TITLE
Processing time at UST execution.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#440]
Hi Team.
When registering 10,000 users at once, how long will it take for processing to complete.
Please tell me the reference time or achievement.
Best regards,

**Comment by adorton-adobe** [comment]
Assuming that these are all new users and are each being assigned to 10 or fewer groups -

The documented API throttling limit for UMAPI user actions is 10 calls per minute.  10 actions may be specified per call, giving you a throughput of 100 new users a minute or about 6,000 calls per hour.  I would expect 10,000 users to take 1.5 - 2 hours.

https://adobe-apiplatform.github.io/umapi-documentation/en/api/ActionsRef.html#actionThrottle
