### ISSUE TITLE
No OSX build for v2.4

### ISSUE THREAD

**Issue by asemak** [adobe-apiplatform/user-sync.py#445]
No OSX build for v2.4 is available from the releases page

**Comment by asemak** [comment]
Yes, but my plans could change if there are no new builds planned.

**Comment by asemak** [comment]
I ended up writing a Dockerfile and ruunning the sync tool in a container so no longer require the macOS build.

Feel free to close.

**Comment by nealdav** [comment]
I'd love to see the macOS builds return as it makes local development much easier.

**Comment by adorton-adobe** [comment]
I think the best we can do at this point is ensure the documentation contains up-to-date build instructions for MacOS as well as a guide to set up the UST for development.  I'll add a note to do this to the manual overhaul tracking issue.
