### ISSUE TITLE
Unexpected LDAP failure reading all users: iter_users() takes exactly 4 arguments (3 given)

### ISSUE THREAD

**Issue by tpegues2** [adobe-apiplatform/user-sync.py#450]
We are running 2.2.1 on RHEL7 and were testing 2.4.1 and ran into the error below in **BOLD**.  We kept most of the information in the configuration files the same.  Does the connector-ldap.yml need to be modified in some way very different than the 2.2.1 version?

2019-02-08 14:11:33 2750 INFO processor - ---------- Start Load from Directory --------------------
2019-02-08 14:12:34 2750 CRITICAL main - **_Unexpected LDAP failure reading all users: iter_users() takes exactly 4 arguments (3 given)_**
2019-02-08 14:12:34 2750 INFO main - ========== End Run (User Sync version: 2.4) (Total time: 0:01:01)

**Comment by adorton-adobe** [comment]
There are a couple of different places this error could be occurring, so I'll need your help to pinpoint it.

Are you running the sync tool with `--users all`?  (or omitting the `--users` option?)

**Comment by tpegues2** [comment]
Hi Andrew,
Here is the command we are running for our test.  It works perfectly fine for our early version (2.2.1) of user-sync.py but not for 2.4.
#/srv/adobe/user-sync -t --users all --process-groups --adobe-only-user-action exclude
Thanks,
Tpegues2

**Comment by adorton-adobe** [comment]
Thanks.  I found the issue.  An update included in 2.4 introduced a bug when invoking `--users all`.  If you run with a different `--users` option such as `mapped`, you won't get the error.  If you need to keep pulling all users, I recommend trying v2.3.

I'll prioritize the bugfix for v2.4.1.

**Comment by tpegues2** [comment]
Thank you Andrew!!!

**Comment by vossen-adobe** [comment]
This is almost definitely the same thing, but here's a different error for it:

 CRITICAL main - Unexpected LDAP failure reading all users: iter_users() missing 1 required positional argument: 'extended_attributes'

**Comment by adorton-adobe** [comment]
@vossen-adobe did you mean to close this?  We need to keep it open as a tracking issue for the bug.

**Comment by vossen-adobe** [comment]
Sorry - it looked like it was closed already!

**Comment by adorton-adobe** [comment]
fixed by #470
