### ISSUE TITLE
Critical error : No config found

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#455]
Error is occured when executing UST.
Error is below:

--------------------------
root@pc:~/Adobe# user-sync -t --adobe-only-user-action exclude 
--users all 2019-02-13 13:52:11 27134 INFO config - Using main 
config file: user-sync-config.yml (encoding utf8) 2019-02-13
13:52:11 27134 CRITICAL main - No config found.
--------------------------

Please tell me the reason of error occured.

Best Regards,

**Comment by adorton-adobe** [comment]
Are you sure your `user-sync-config.yml` is in the same directory as the sync tool?

Please provide the following information:

* Sync Tool version
* Operating system (and release/version)
* Python version

**Comment by Tomomi99145** [comment]
Thank you for your reply.
Yes,`user-sync-config.yml` is in the same directory as the sync tool.
I will comment the answer below when confirmed it.
* Sync Tool version
* Operating system (and release/version)
* Python version

**Comment by adorton-adobe** [comment]
Also, remember that you can also explicitly point to the config file.

`-c /path/to/user-sync-config.yml`

If you're still seeing an error, ensure that the config files are in the correct format and contain all expected keys.

**Comment by Tomomi99145** [comment]
If the config file can not be found a different error will be issued.
Error is below:

2019-02-13 16:19:05 29675 
CRITICAL main - No such configuration file: /root/Adobe/logs/user-sync-config.yml

Replacing only the config file with the Server where the UST is working correctly will work correctly.
Threfore, I think the config file are in the correct format and contain all expected keys.

**Comment by adorton-adobe** [comment]
Will you please email me the config files, with sensitive credentials stripped out (replace with empty strings)?  My email address is adorton@adobe.com

**Comment by adorton-adobe** [comment]
Closing since this ticket has been inactive for more than a year.
