### ISSUE TITLE
How to configure TLS security on RHEL

### ISSUE THREAD

**Issue by pnbevan** [adobe-apiplatform/user-sync.py#456]
Our organisation requires the use of TLS security to access our LDAP.  I've been furnished with the required certificate.  How do I configure User Sync to use that certificate with require_tls_cert set to true?  I'm using the user-sync-v2.4-centos7-py367 release on RHEL 7.5 with Python 3.6.7.

**Comment by vossen-adobe** [comment]
@adorton-adobe @bhunut-adobe is this addressed by the ldap changes for 2.6?

**Comment by adorton-adobe** [comment]
This should work better in 2.6.0.
