### ISSUE TITLE
Add ability to skip users from extension config

### ISSUE THREAD

**Issue by vossen-adobe** [adobe-apiplatform/user-sync.py#465]
I've had this come up a lot of times - the extension config would be greatly more useful if we had the ability to drop users from the sync conditionally.  Normally, I'd have to change a user's email to bogus values in order to prevent them from synching, but it would be great to be able to do this cleanly.

An example case:
Filtering by OU.  The LDAP syntax is not sophisticated enough to do this, but it's a breeze with regex in the extension.  The only trouble is that you still can't stop non-matching users from being pushed without the hack I mentioned above.

I can think of numerous other benefits for this as well!

**Comment by adobeDan** [comment]
Why do you want to do this in the extension code, as opposed to just using the existing "exclude_users" config option (which allows for regular expressions)?  Are you trying to provide for more sophisticated logic than just an OR of regular expressions?

**Comment by vossen-adobe** [comment]
@adobeDan Yes - more sophisticated logic, but also the fact that exclude_users is applied on the UMAPI side, whereas this change would allow filtering based on AD conditions/extended attributes.  The other choice, --users-filter option, seems not to handle attribute comparison and requires an exact match  according to the documentation:

--user-filter
"Limit the set of users that are examined for syncing to those matching a pattern specified with a regular expression."

**Comment by adorton-adobe** [comment]
Closing since the related PR is closed.
