### ISSUE TITLE
G Suite Secure LDAP service - Authenticate with client certificate

### ISSUE THREAD

**Issue by RCCSDTech** [adobe-apiplatform/user-sync.py#483]
G Suite for Enterprise and Education supports connecting through a [secure LDAP Service](https://support.google.com/a/answer/9048516). It uses a client certificate for authentication, which doesn't seem to work in the user sync tool. I was able to get it to work by using [stunnel as a proxy](https://support.google.com/a/answer/9089736#stunnel).

Is it possible to authenticate with a client certificate directly in the user sync tool?

**Comment by adorton-adobe** [comment]
After the 2.5.0 release, we plan to add some new options for managing TLS functionality, including the ability to specify the location of a client certificate for verification.  I can't guarantee it will solve the problem, but it may make things easier.

**Comment by RCCSDTech** [comment]
Great to hear that the functionality will be added in a future version. For now, I will use the stunnel solution and look forward to a future release with certificate authentication built-in. Thanks.
