### ISSUE TITLE
user-sync-v2.5.0rc2-win64-py368.zip

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#486]
Did not had time to look thoroughly on it, but I've had a test with this version today (user-sync-v2.5.0rc2-win64-py368.zip)  and it did not process the groups (and maybe missing warnings about country code).

**Comment by Luci2015** [comment]
So, I've investigated a bit further and it seems that if I run the tool with the invocation defaults where I have **Yes** or **True** for  process_groups, update_user_info, test_mode
=> these are all ignored and it used False by default for all, including test_mode, which has potential to do some serious damage on run
This needs a fix asap.

**Comment by adorton-adobe** [comment]
Please post your user sync config and the CLI parameters that your are using.

**Comment by Luci2015** [comment]
I'll do a PR in a few minutes. Stay tuned.

**Comment by Luci2015** [comment]
Can you please review this?

**Comment by bajwa-adobe** [comment]
The version cmd also seems broken on new build 

`python user-sync.pex --version` results in error `RuntimeError: Could not determine version`
