### ISSUE TITLE
User-synch.py (How To Disable A User)

### ISSUE THREAD

**Issue by tpegues2** [adobe-apiplatform/user-sync.py#488]
Is there a way to disable a user versus deleting/removing them?  There are times when a user needs to be simply disabled and deleted at a later time. This would keep their data in tact during a grace period and then they could be removed later.

**Comment by adorton-adobe** [comment]
It depends on whether or not you want the user to remain in the organization user list.  The simplest thing to do is always run sync with `--process-groups` and the default Adobe-only action will remove any Adobe-only user from the groups they were assigned when they were initially synced.

Also - removing a user is different from deleting a user.  User removal is a potentially viable option for you.

* Remove - remove a user from the organization user list, but keep the user record in the underlying Admin Console directory.  This does not affect any of the user's data stored in any Adobe Creative or Document cloud storage system.

* Delete - remove the user from the underlying directory and delete all stored cloud data associated with the account

**Comment by tpegues2** [comment]
Thanks!  That did the trick!!
