### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by AsakaOkuyama** [adobe-apiplatform/user-sync.py#490]
A customer got an error when he configured the initial settings for 2.5.0rc2, and the message was like as "The specified path could not be found (this message is not exactly since the language was Japanese) ."
I need below information for him;
1. which version is supportable and capable with an operational test. 
2. why this issue has happened
3. the return value of the command, is it listed and can we deliver it?

--------------------------------
　Python:python-3.6.8
　UserSyncTool:2.5.0rc2
--------------------------------
C:\UserSyncTool>python user-sync.pex -v
Traceback (most recent call last):
  File "C:\UserSyncTool\user-sync.pex\.bootstrap\_pex\pex.py", line 347, in execute
  File "C:\UserSyncTool\user-sync.pex\.bootstrap\_pex\pex.py", line 90, in _activate
  File "C:\UserSyncTool\user-sync.pex\.bootstrap\_pex\environment.py", line 163, in activate
  File "C:\UserSyncTool\user-sync.pex\.bootstrap\_pex\environment.py", line 217, in _activate
  File "C:\UserSyncTool\user-sync.pex\.bootstrap\_pex\environment.py", line 152, in update_candidate_distributions
  File "C:\UserSyncTool\user-sync.pex\.bootstrap\_pex\environment.py", line 122, in load_internal_cache
  File "C:\UserSyncTool\user-sync.pex\.bootstrap\_pex\environment.py", line 109, in write_zipped_internal_cache
  File "C:\UserSyncTool\user-sync.pex\.bootstrap\_pex\util.py", line 178, in cache_distribution
  File "C:\UserSyncTool\user-sync.pex\.bootstrap\_pex\common.py", line 140, in safe_open
  File "C:\UserSyncTool\user-sync.pex\.bootstrap\_pex\common.py", line 128, in safe_mkdir
  File "C:\Python37-32\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Python37-32\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Python37-32\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Python37-32\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] 指定されたパスが見つかりません。: 'c:\\user-sync.pex\\install'

**Comment by cosmin-balanoiu** [comment]
Hi Asaka san,

First. I recommend using a stable version for production environments, so you may replace the pex file with the 2.4.3 version.
As for the error, this is thrown because by default Windows has a setting to limit the paths to 256 chars unless overridden.
To go around this inconvenience you should create an environment variable named "PEX_ROOT" with the value: "C:\pex".
Or you can type the following command in command prompt each time before you run the tool:
set PEX_ROOT=C:\pex

**Comment by AsakaOkuyama** [comment]
Hi @cosmin-balanoiu san,
Thank you for replying to me! I'll ask the customer to try a stable version. Please let me ask one more thing, could you tell me is there a list about a return value list?

**Comment by adorton-adobe** [comment]
The process should return 0 when it terminates without any unhandled exceptions.  That doesn't always mean a sync ran successfully.  It just means that if there was an error, the error handler caught it and terminated the process gracefully.

If an unhandled exception does occur, it will terminate with a non-zero return value.  We can't provide any specific information on what different return codes signify.

**Comment by AsakaOkuyama** [comment]
Hi @adorton-adobe san,
Thank you for providing the answer, I can tell him as you mentioned.

**Comment by adorton-adobe** [comment]
We probably should have the sync tool return a non-zero status for critical errors that we handle.  I'll create an issue to track this feature.  One thing the customer can do in the meantime is check the tool's output for critical errors.  (typically the word CRITICAL is enough)

**Comment by AsakaOkuyama** [comment]
Hi @adorton-adobe san,
Thank you for the update information. Let the customer taking a log as CRITICAL by running the command.

**Comment by AsakaOkuyama** [comment]
Please let me ask a couple of question.
Are we able to support Python 3.7.3 and 3.6.8 embeddable with UST stable version, and verified?

**Comment by vossen-adobe** [comment]
@AsakaOkuyama 
We don't current;y support 3.7 - but may in the future.  I don't see why 3.6.8 embeddable wouldn't work.  Our installer installs the full version, but as long as you have a valid x64 3.6 environment the tool will run fine.

**Comment by AsakaOkuyama** [comment]
Hi, @vossen-adobe  san
Thank you for the prompt answer. I think that the 3.6.8 embeddable version showed the error due to the character number limitation as @cosmin-balanoiu told me, so it wasn't depended on the version. If so, can we support embeddable version too?

**Comment by vossen-adobe** [comment]
Did you try adding the pex_root variable? And also - which platform is this on? If it's win10 or 2016 there's a registry fix that can also enable long file paths, assuming that is the issue here..

**Comment by adorton-adobe** [comment]
The embeddable version probably isn't going to run the sync tool.  It doesn't appear to contain the full Python standard library.

**Comment by AsakaOkuyama** [comment]
Hi @vossen-adobe @adorton-adobe 
Thank you for replying and answer to me. We tried to add the pex_root and configure, but the embeddable version didn't work. Also, I told the customer to use the stable version.

**Comment by adorton-adobe** [comment]
What prevents the customer from using one of the standard Python builds?  If they can't, they may need to figure out an alternate user sync solution.  The standalone executable version of the sync tool may work, but we can't guarantee we'll maintain it in the long term at this point (although early work on it is very promising)

**Comment by AsakaOkuyama** [comment]
Hi @adorton-adobe 
I'm not sure why he thought using not a stable version, but I confirmed that he tried and succeeded to test with the stable version. 

Thank you very much for you guys for answering my question!
