### ISSUE TITLE
I want to put "cn" in "firstname" and "lastname".

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#491]
I tried to put "cn" in "firstname".
script is below,

extended_attributes:
  - cn
extended_adobe_groups: []
after_mapping_hook: |
  cn = source_attributes.get('cn')
if cn is not None:
    target_attributes['firstname'] = cn

However,"firstname" was synced as null.
Please tell me the solution.
Thank you,

**Comment by Tomomi99145** [comment]
"cn" is an attribute value of Active Directory.
My customer doesn't want to sync value of "sn"and "givenName".
I think "Custom Attributes and Mappings"(extension-config.yml) will solve it.
Is it correct?

**Comment by vossen-adobe** [comment]
You can just set this in connector-ldap.yml instead of given name.  Is this what you want? That will also allow for update user info to work.

In the above, you can print can to make sure it's getting pulled correctly.

**Comment by Tomomi99145** [comment]
Thank you for your answer.
I will try it.

**Comment by Tomomi99145** [comment]
Then I also want to set fixed value(for example "A Company") to firstname.
Is this possible?

**Comment by Tomomi99145** [comment]
The above question succeeded by set the fixed values into the connector-ldap.yml.
Thank you for your support.

**Comment by adorton-adobe** [comment]
If this is resolved, I'm going to close the issue
