### ISSUE TITLE
feature request: SQL data source

### ISSUE THREAD

**Issue by lhoekenga** [adobe-apiplatform/user-sync.py#496]
It would be fantastic if we could define / use sql data sources to provide the group data.
Maybe the entries in user-sync-config.yml would look like..

    - sql_group: "select username from users where department = 'marketing'"
      adobe_groups:
        - "Marketing Users"

**Comment by adorton-adobe** [comment]
This seems like a useful feature, but I don't know if we have enough user demand to justify the effort it would take to implement it.  It wouldn't be a huge feature in terms of effort, but there's enough complexity that we would need sufficient demand.

Here are some items we'd need to consider (off the top of my head):

* Create a new directory connector type
* Decide which DB servers to support
* Define a configuration format to specify credentials, query, field mappings, etc
* Support credential storage backends currently supported by LDAP and UMAPI connectors
* Enforce schema constraints on query result to ensure consistency
* Test on all supported DB backends
* Ensure the sync tool doesn't become a vector for SQL injection

For now I recommend connecting directory to an LDAP system or setting up a process to dump users from your database to a CSV file.

**Comment by adorton-adobe** [comment]
Closing this since it hasn't had any activity in a long time and isn't a feature that we're currently working on.
