### ISSUE TITLE
Syncing all AD users to adobe group

### ISSUE THREAD

**Issue by trecakov** [adobe-apiplatform/user-sync.py#498]
Is there a way to sync all users from AD into the adobe group, but without mapping the groups?
For example, I would like to sync all users that have certain base_dn to an Adobe group. However, I do not have users I want to sync in a group.

**Comment by vossen-adobe** [comment]
Sure - just use --users all  and set the target group in extension-config.  See the documentation here:

https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/advanced_configuration.html#custom-attributes-and-mappings

**Comment by adorton-adobe** [comment]
I recommend also modifying the `all_users_filter` in `connector-ldap.yml` if possible to query only users that have your desired base_dn.  You may not need the extension config if you are not assigning users to groups.

The sync tool doesn't assign users to groups by default, so just make sure you don't invoke the tool with `--process-groups`.

**Comment by trecakov** [comment]
Sounds good. Will try that. However, I am getting an error "Value not found for key: extended_attributes in: extension". Do you know what might be causing this error?
In my extension-config.yml I have:

`extended_attributes:
     - distinguishedName
  extended_adobe_groups:
     - AdobeGroupForOUUsers
  after_mapping_hook: | 
     if "Specific OU" in source_attributes.get('distinguishedName'):
         target_groups.add('AdobeGroupForOUUsers')`

**Comment by vossen-adobe** [comment]
is this gituhub or does the formatting look like this?

**Comment by trecakov** [comment]
its the github. I just figured out what i was doing wrong. Thanks for the help!
