### ISSUE TITLE
No error for illegal command line options

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#5]
Should be an error if unrecognized stuff on the command line.  eg

python user-sync.pex --users file example.users-file.csv --process-group

**Comment by jamesg123** [comment]
Hi Phil,

We are using argparse to handle the command line options. Argparse defaults to accepting abbreviations. 'process-group' was accepted, as it is an abbreviation of the valid option 'process-groups' (with the additional s). An invalid command line option such as --invalid produces an error such as this:

usage: app.py [-h] [-v] [-t] [-c path] [--config-filename filename]
              [--users [all|file|group [arg1 ...]]] [--user-filter pattern]
              [--source-filter connector:file] [--update-user-info]
              [--process-groups] [--remove-nonexistent-users]
              [--generate-remove-list output_path] [-d input_path]
app.py: error: unrecognized arguments: --invalid

There is an option for argparse to disable abbreviations, but unfortunately not in python 2.7 (it is in 3.2). To disable the abbreviations for 2.7 would require us to extend the functionality of argparse.

Please let me know if this should be left as is or if a code change is required.

Thanks,
Jim

**Comment by phil-levy** [comment]
If you are saying that any of our command line options can be abbreviated as long as the abbreviation is unambiguous, that is probably okay.  We just need to document that.  Let me know.

**Comment by adobeDan** [comment]
That’s what he is saying, yes. :)  We should document it. –d.

**Comment by phil-levy** [comment]
Documentation updated.
