### ISSUE TITLE
Extension-added groups are not removed

### ISSUE THREAD

**Issue by adobeDan** [adobe-apiplatform/user-sync.py#50]
If you use an extension to add a group to a user, then that group is not removed on later runs if the user is removed or if the extension changes to no longer add that group.

**Comment by adobeDan** [comment]
fixed in v1, waiting for next merge to main.

**Comment by adobeDan** [comment]
Reopening until we merge to main.

**Comment by bhunut-adobe** [comment]
@adobeDan does this fix issue #42  also?

**Comment by adobeDan** [comment]
@bhunut-adobe Not sure, I am planning to investigate #42 today or tomorrow.

**Comment by adobeDan** [comment]
Closing as fix is in v1 branch and will be included in 1.1.2 build.
