### ISSUE TITLE
LDAP bind error

### ISSUE THREAD

**Issue by astrugatch** [adobe-apiplatform/user-sync.py#501]
Going through my test run and i get this error:

`LDAP connection failure: automatic bind not successful - confidentialityRequired`

**Comment by astrugatch** [comment]
Well changing ldap host to ad d :636 fixed this but now I get:
 CRITICAL main - LDAP connection failure: index out of range

**Comment by adorton-adobe** [comment]
If you want to use ldaps, you need to change the protocol e.g. `ldaps://example.com`.  You can then omit the port if the server is listening on 636 since that is the standard ldaps port.

**Comment by astrugatch** [comment]
ldaps:// actually still gives them the connection failure. But specifying the port doesn't but i am still getting the index out of range error

**Comment by adorton-adobe** [comment]
Will you please provide the following information:

1. UST version
2. OS
3. Python version
4. LDAP system details (e.g. directory platform name, version, etc)

**Comment by astrugatch** [comment]
I am going to close the issue. We decieded that there are few enough users that change that making changes via CSV is no more difficult than making them in our directory. 

But for completeness:

UST 2.5
ubuntu server lts 18.04
3.6.8
Syncing to GSuite LDAP. (was starting to work on using stunnel as an intermediary when the decision was made to use the CSV uploads.)
