### ISSUE TITLE
Occurrence of exception

### ISSUE THREAD

**Issue by AsakaOkuyama** [adobe-apiplatform/user-sync.py#504]
Hello folks,

My customer faces an exception after every command execution as below. What does it mean and how should he correct?
--
python : c:\pex\install\user_sync-2.4.3-py3-none-any.whl.1c05209bb7835026761c4d6bd54d6eba23e6e900\user_sync-2.4.3-py3-none-any.whl\user_sync\config.py:957:
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
発生場所 C:\Adobe\UserSyncTool\Run_UserSync.ps1:31 文字:9
+         python $USR_SNC_TOOL_PATH -t --users all --user-filter usmbd5@ono.co.jp  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (c:\pex\install\...r full details.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

  yml = yaml.load(byte_string.decode(cls.config_encoding, 'strict'))

**Comment by adorton-adobe** [comment]
This was fixed in v2.5.0 - see #476
