### ISSUE TITLE
ERROR umapi.action - Error in requestID:

### ISSUE THREAD

**Issue by RocRaider** [adobe-apiplatform/user-sync.py#505]
We are running into issues when processing group memberships. We are trying to map a Active Directory group and several nested groups to a single Adobe user group. It works on other groups but for some reason it is failing on new group creations. 

Here is a sample of the error output from the logs when I am trying to get a test group to work. I have remarked out the user and domain for privacy. 

7288 INFO processor - Managing groups for user key: federatedID,TESTUSERS@MY.DOMAIN.COM, added: {'test'} removed: set()

7288 ERROR umapi.action - Error in requestID: action_1 (User: {'user': 'TESTUSERS@MY.DOMAIN.COM', 'requestID': 'action_1'}, Command: {'add': {'product': ['test']}}): code: "error.internal.add" message: "Failed to add users to user group"

Here is a sample from the user-sync-config-config.yml file under the section groups. 

- directory_group: "Adobe_All_Apps_for_K-12"
      adobe_groups:
        - "TEST"  

A few questions I have. 

1. Is there any issues with syncing groups from active directory that are nested? I have the correct LDAP filter setup " (memberOf:1.2.840.113556.1.4.1941:={group_dn})" but I just want to be sure. 

2. Is there any issues with users getting licensed for the product multiple times? Basically if a user is in a group that is provisions them for a certain Adobe product and we create a new group that also provisions that user for the same product is there conflict? The only reason I ask is because we are doing a migration and consolidating groups. To avoid impact to the users in case of issues (like this one) we are doing some product provisioning  overlap until the migration is done. 

3) Is there a limit to the amount of syncs that can process. Is there a max number of users that you can have in your organizations sync setup? 

I hope this makes sense and any input is appreciated! 

Thanks in advance.

**Comment by RocRaider** [comment]
We have self resolved this issue. It was due to having the a product profile configuration set to NA. The users were being added to a group and then being removed because without a product profile quota set it was rejecting any users that were being added. We upped the quota and the issues seems to have resolved itself.  In summary even though you are not forced to add a quota, and nowhere in the adobe verbiage does it say it is required, it is required,

**Comment by adorton-adobe** [comment]
@RocRaider - how the quota is handled depends on what type of Admin Console you have.  I'm not super knowledgeable about that side of things, so I can't go into detail.  Reach out to your Adobe Customer Success Manager - they can provide details on what type of console your organization has and how the user quotas are handled.

**Comment by RocRaider** [comment]
Thanks.
