### ISSUE TITLE
adobe-only-user-action write-file also creates/synchronizes new users to console. Is that intended behavior?

### ISSUE THREAD

**Issue by bajwa-adobe** [adobe-apiplatform/user-sync.py#507]
I noticed that “--adobe-only-user-action write-file” command which create CSV of user accounts to remove, can also synchronizes new users to console. Is that intended behavior?

**Comment by brotskydotcom** [comment]
Yes, it is.  The `--adobe-only-user-action` is a modifier and doesn't affect any behavior of the sync other than what happens to adobe-only users.

**Comment by adobeDan** [comment]
Yes, it is.  The `--adobe-only-user-action` is a modifier and doesn't affect any behavior of the sync other than what happens to adobe-only users.
