### ISSUE TITLE
how long it takes to sync

### ISSUE THREAD

**Issue by AsakaOkuyama** [adobe-apiplatform/user-sync.py#509]
My customer asks how long it takes to sync about 70,000 newly users. Do you have any case-based reasoning?

**Comment by Luci2015** [comment]
I would estimate like this:
There are about 25 API calls per minute for create actions, of 10 users each => 250 users/min;
70000/250  = 280 minutes just to create all of them
Every 25 API calls you get a timeout for up to a minute => ~1 min delay between each 25 batch
roughly = 280 min just waiting for the timeout to pass
=> 280 *2 = 560 min ~ 9 hours

It will take hours, maybe 9 maybe less...

**Comment by AsakaOkuyama** [comment]
Thanks, @Lucian. I'm going to say this to the customer.
