### ISSUE TITLE
The behavior of assigning the license

### ISSUE THREAD

**Issue by AsakaOkuyama** [adobe-apiplatform/user-sync.py#510]
What messages are logged when I synchronize more users than eVIP subscriptions?
The customer concerns about the possibility that he can't recognize the user who can't be assigned the license. So could you give me the error message of logs or the status of the CLI? ETLA contract doesn't happen this situation since no limit in it.

**Comment by adorton-adobe** [comment]
The error would come from the UMAPI. I don't know which error it would report specifically, but all UMAPI errors are documented here:

https://adobe-apiplatform.github.io/umapi-documentation/en/api/ErrorRef.html

If you need more information, I recommend opening an issue on the UMAPI documentation repo:

https://github.com/adobe-apiplatform/umapi-documentation/issues
