### ISSUE TITLE
user-sync should work in Python 3 as well as Python 2

### ISSUE THREAD

**Issue by adobeDan** [adobe-apiplatform/user-sync.py#52]
As Python 2 end-of-life is approaching, we need to port user-sync to Python 3 for customers who are transitioning.  As with [umapi-client](https://github.com/adobe-apiplatform/umapi-client.py), we should support both Python 2 and 3.

**Comment by adobeDan** [comment]
@ianmak I'd like you to take a shot at this.  First look at the sources for the [umapi-client](https://github.com/adobe-apiplatform/umapi-client.py), where I did this conversion a while ago.  The key is to use the `six` module, which is a shim layer that maps both the 2.7 and 3.x modules to the same namespace.  Then you find all the places where 2.7-isms are used, and you convert them to be the `six`-compatible version which also run in 3.x.  Do some research and then tell me what you think; I think this could be right up your alley.

**Comment by ianmak** [comment]
sure thing I will take a shot at this.
