### ISSUE TITLE
Email address updating failing when changing email domains with federatedIds

### ISSUE THREAD

**Issue by ericallen** [adobe-apiplatform/user-sync.py#531]
When a directory has multiple domain names associated with it and a user's email changes from one domain to the other, the sync with not match the users but then fail when trying to create the user.   When it tries to create the user with the updated email address, umapi will fail because the username already exists.  

The umapi allows for email address updates and switch between the domains. The the user sync it is matching the adobe users and the directory users (in this case AD)  but when the email address changes in AD, user-sync sees it as a new account. To create the user_key for each account, it uses rules.py RuleProcessor.get_user_key which will build a key of type,username,domain.   It gets the domain from the email address, so if the domain of the email address changes in AD it will not match the adobe account even though the username is correct.  

For example the user_key for adobe would be `federatedId,A12345678,school.edu' but the email address has changed on the directory side and it has a user_key of `federatedId,A12345678,email.school.edu`.  The sync sees these two accounts as two different users.  

The umapi documentation has an example to update the username when needed with the update action.  https://adobe-apiplatform.github.io/umapi-documentation/en/api/ActionsCmds.html

`[
  {
    "user": "joesmith@mycompany.com",
    "do": [
      {
        "update": {
          "email": "joesmith@gmail.com"
        }
      }
    ]
  }
]`

The reason behind why there is the email address change between domains.  We are a university which has different email domains for students and staff.  A domain email address can change when a student becomes staff and gaining a staff email address.  Since we only have one domain and one adobe cc instance we update the email address in the adobe account for the individual.

**Comment by adorton-adobe** [comment]
This is something we're investigating.  I will create a bug report and link it here.

**Comment by J-Camping** [comment]
Was there any update to to this? I can open a new issue, but when changing email addresses for users, they are seen as different user.
