### ISSUE TITLE
User Sync and ADFS

### ISSUE THREAD

**Issue by itintern1** [adobe-apiplatform/user-sync.py#534]
Can I install User Sync on the same server that I use for Microsoft syncing processes (ADFS)?
Our ADFS is PowerShell based while User Sync is based on Python.

**Comment by zuboje** [comment]
Yes you can. User sync works on any machine (it could be client). As long as you have all dependencies installed it will work and as long as user executing sync have appropriate AD permissions

**Comment by adorton-adobe** [comment]
We generally recommend installing the sync tool on a standalone server, but it can technically be installed anywhere as long as the server can talk to your directory system and our User Management API.  Make sure the server or VM has at least 4GB memory.

**Comment by itintern1** [comment]
Thank you
