### ISSUE TITLE
Add TEST MODE notification to beginning of run

### ISSUE THREAD

**Issue by n8felton** [adobe-apiplatform/user-sync.py#535]
Just to be double sure that you're running with Test Mode enabled, it'd be nice if this was noted at the start of the run.

Perhaps something like
```
INFO main - ========== Start Run (User Sync version: 2.5.0) ============
```
could become something like this
```
INFO main - ========== Start Run (User Sync version: 2.5.0) (TEST MODE) ============
```

**Comment by adorton-adobe** [comment]
Related to #595
