### ISSUE TITLE
About add AD user to "Product Profiles" or "User Groups".

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#545]
Hi Team,
I want to know how to add all user to "Product Profiles" or "User Groups" without security group in AD.
Would that be possible?

Regards,
Tomomi

**Comment by vossen-adobe** [comment]
Certainly - you can do this by filtering in extension-config.yml:

e.g.: 
https://github.com/vossen-adobe/example_ust_config/blob/master/simple_add_user.yml
https://github.com/vossen-adobe/example_ust_config/blob/master/employee_type.yml

basically target_groups.add('name')

**Comment by Tomomi99145** [comment]
Hi vossen,

Thank you for your answer.
I'll try it.

Thanks!!
Tomomi
