### ISSUE TITLE
Sync via CSV

### ISSUE THREAD

**Issue by AsakaOkuyama** [adobe-apiplatform/user-sync.py#546]
A customer plans to sync via CSV in initial sync and with each change in users. Is there any restriction on the number of users in a csv file, or capacity size?

**Comment by vossen-adobe** [comment]
There should not be any issue with the sync tool relative to the admin console. The upper functional limit of the admin console is around 300k users - this is the only *real* user limit that I am aware of, because it pushes the sync over 24 hours and the oauth token expires.  The sync tool would continue working far beyond that number in theory.

**Comment by AsakaOkuyama** [comment]
Hi @vossen-adobe, Thanks for replying, I can see the article which says the limit of the csv for Admin Console is 5000users, so the customer worried about the upper limit. But I will say to the customer, as you mentioned. Thanks!
--
https://helpx.adobe.com/enterprise/using/bulk-operations.html
You can add multiple users to your organization and provision them to product profiles at the same time by uploading a comma-separated list. You can download a sample CSV file from the Import Users dialog and then fill the details and upload the file. You can import up to 5,000 users at a time.

**Comment by vossen-adobe** [comment]
That limit is for the csv upload - using sync tool it doesn't apply!

**Comment by AsakaOkuyama** [comment]
@vossen-adobe I understand it. Thank you again!

**Comment by adorton-adobe** [comment]
@AsakaOkuyama - you may already be aware, but please note that the CSV must contain all users that should be considered for sync.  This includes new users to add and users that need updates, but also users that may not need any changes.

**Comment by AsakaOkuyama** [comment]
Hi @adorton-adobe , Is it for initial adding the users, as you mentioned? If the users some need to be updated, and some are deleted, have all the same domains, or in the same OU, how can it be detected?

**Comment by adorton-adobe** [comment]
We handle it the same way we handle new users, updates and Adobe-only users in any identity source type (LDAP, Okta, or Admin Console).  We assume we are getting a model of all of the users that should have an identity and product entitlements in the admin console when the sync is run.  Some of those users may be new to the console, some may need group membership updates, and others may need user information updates.  If the tool finds a user in the Admin Console that isn't found in the CSV, then the tool will handle it as an Adobe-only user and take the appropriate action.

**Comment by AsakaOkuyama** [comment]
I understood it. Thank you, @adorton-adobe !
