### ISSUE TITLE
OpenSSL version?

### ISSUE THREAD

**Issue by aryaxo** [adobe-apiplatform/user-sync.py#549]
Running User-Sync 2.5.0 on CentOS 8
OpenSSL latest version 1.1.1

Running a test sync using:
```
./user-sync -t --users all --user-filter test.user@#######.###.## --adobe-only-user-action exclude
```

Results in the following:
```
CRITICAL main - Connection to org #######################@AdobeOrg at endpoint https://usermanagement.adobe.io/v2/usermanagement failed: libssl.so.10: cannot open shared object file: No such file or directory
```

I can symlink my current versions to the requested directories using:
```
ln -s /usr/lib64/libssl.so.1.1 /usr/lib64/libssl.so.10
ln -s /usr/lib64/libcrypto.so.1.1 /usr/lib64/libcrypto.so.10
```

Which then results in:
```
CRITICAL main - Connection to org #######################@AdobeOrg at endpoint https://usermanagement.adobe.io/v2/usermanagement failed: /lib64/libssl.so.1.1: version `libssl.so.10' not found (required by /root/.pex/install/cryptography-2.7-cp36-cp36m-linux_x86_64.whl.073aaa5ccb57df850174b9229a9e9e9d6333d518/cryptography-2.7-cp36-cp36m-linux_x86_64.whl/cryptography/hazmat/bindings/_openssl.abi3.so)
```

Is there a way to get around this? Or is there a specific older version of OpenSSL I should be attempting to use?

Thanks in advance!

**Comment by vossen-adobe** [comment]
It hasn't been compiled for Centos8 yet - 7 is the supported platform.  One thing you might be able to do is install the libssl dependencies from the centos7 repository - similar manipulations have worked for me between suse and opensuse, but no guarantees.  It's probably easier to just build it on centos8.

**Comment by aryaxo** [comment]
Resolved by using CentOS 7, thanks!
