### ISSUE TITLE
Support syslog logging

### ISSUE THREAD

**Issue by cadegenn** [adobe-apiplatform/user-sync.py#550]
Hi,

The log file is good. Howerver in most enterprise, the logs are sent to a centralized location using some syslog mechanism. It would be great if UserSync could send its log (already in a syslog format for what I can see) to a syslog server.

The executable name is "processor", it could be usefull to change it to a more human guessable (and machine parseable) thing like "adobe-user-sync"

Thank you.

**Comment by adorton-adobe** [comment]
We don't have any plans for adding that support at this time. Our approach to the logs is to make them reasonably parseable by other processes that handle things like notifications or hooks into external logging systems. There might be more we can do around that like making log fields tab-delimited but that is something we would need to look into.

And we probably won't be changing the identifiers in the log such as "main" or "processor" - those identify components of the sync tool that are generating the logs. Not the application as a whole.
