### ISSUE TITLE
How to use https_proxy

### ISSUE THREAD

**Issue by norihiroGitHub** [adobe-apiplatform/user-sync.py#554]
Windows Server 2016.

The customer has an authentication proxy and they cannot bypass UST's 2 endpoints. 
Their proxy must need ID and PASSWORD for authentication. In Adobe help page said, "https_proxy" will help, but I don't know how. Please teach me that how to use it.

**Comment by cosmin-balanoiu** [comment]
HI Norihiro,
This is the format for the environment variable using a username and password: 
http_proxy=http://USERNAME:PASSWORD@SERVER:PORT/
This is the format without:
http_proxy=http://SERVER:PORT/

**Comment by norihiroGitHub** [comment]
Hi @cosmin-balanoiu 

Like this?

 in comand prompt;
set http_proxy=http://USERNAME:PASSWORD@SERVER:PORT/
set https_proxy=http://USERNAME:PASSWORD@SERVER:PORT/
python user-sync.pex -t --users mapped --process-groups --adobe-only-user-action exclude

**Comment by cosmin-balanoiu** [comment]
Hi Norihiro,

That looks about right. You can either set them up in command line or fully as environment variables.

**Comment by adorton-adobe** [comment]
Since there have been no new comments on this one for a while, I'm closing this issue.
