### ISSUE TITLE
Python 3.8+ Compatibility

### ISSUE THREAD

**Issue by JMiller-Disco** [adobe-apiplatform/user-sync.py#557]
Hi,

I can't find an old copy of Python 3.6.X on my existing computer/VMs.
Are there any plans on updating the script's compatibility to Python 3.8.X+ in the near future or will I need to build the older version of Python?

Thank you for your help.

**Comment by vossen-adobe** [comment]
You can just download the older version: https://www.python.org/ftp/python/3.6.8/python-3.6.8-amd64.exe

But that said, in the near future we hope to package the tool such that python is not required on the host machine.

**Comment by JMiller-Disco** [comment]
That'd be awesome, and you guys are doing a great job!

Also, thank you for the link.
Python.org doesn't do a great job of pointing to the old executables.

**Comment by latif2** [comment]
pyton super in future....

‫في الأربعاء، 15 يناير 2020 في 7:08 م تمت كتابة ما يلي بواسطة
‪JMiller-Disco‬‏ <‪notifications@github.com‬‏>:‬

**Comment by adorton-adobe** [comment]
The next UST release will very likely be released in as a self-contained executable, and won't require a specific Python to be installed on the system.

**Comment by belacs** [comment]
> The next UST release will very likely be released in as a self-contained executable, and won't require a specific Python to be installed on the system.

Any timeline on when this will be happening?

**Comment by cbalanoiu** [comment]
@belacs 
The latest release, 2.6.0, is already an executable running on Python 3.6.8 which is built in.

**Comment by belacs** [comment]
> @belacs
> The latest release, 2.6.0, is already an executable.

the documentation is not very clear then as it sure seems to be telling me to setup python to get started.

**Comment by cbalanoiu** [comment]
That is still valid for the previous version. For this one Python is not required neither to be installed nor passed when running the tool.

**Comment by adorton-adobe** [comment]
@belacs Can you please provide links to the parts of the documentation you find confusing?
