### ISSUE TITLE
I want to know add one user to multiple groups.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#558]
I want to know how to add one user to multiple groups using 4 connector-csv.yml(input users-file.csv).
Please tell me how this is done specifically?
Regards,
Tomomi

**Comment by Tomomi99145** [comment]
Can someone answer to this question?
Have you no method to try it?

**Comment by adorton-adobe** [comment]
At this time, you can't read from more than one identity source. If you need to read from more than one CSV file, a separate process would need to be developed to combine and de-duplicate the files. You can however map one source group to multiple Adobe groups.

**Comment by Luci2015** [comment]
When you sync based on csv input and have that connector-csv.yml file enabled in the user-sync-config, you'll notice it has `groups_column_name: groups`. 
This makes the tool look inside your user-list.csv for the 'groups' column and use it as input. 
If you specify more group names inside that field, inside quotes and separated by comma, you will get the user assigned to those groups on Adobe side (as long as the same mapping is declared in the user-sync-config.yml file, 'groups:' section).

example of csv input, in email based user login set Directory:
```
firstname,lastname,email,country,groups,type,username,domain
John,Doe,mail@domain.com,US,"group 1, group 2",federatedID
```

and the mapping in user-sync-config to match the input:
```
groups:
  - directory_group: group 1
  - adobe_groups:
      - adobe group name 1
  - directory_group: group 2
  - adobe_groups:
      - adobe group name 2
```

As result, John Doe is added to both `adobe group name 1` and `adobe group name 2`

**Comment by Tomomi99145** [comment]
@Luci2015 
Thank you for your support.
I will try it!
Thank you!!!
Tomomi
