### ISSUE TITLE
 Unexpected LDAP failure reading group members: invalid attribute type BE

### ISSUE THREAD

**Issue by dvdborn** [adobe-apiplatform/user-sync.py#573]
Hi,

I've upgraded from v2.4.3 to v2.5.
V2.5 gives the following error message:

 CRITICAL main - Unexpected LDAP failure reading group members: invalid attribute type BE

If I revert back to v2.4.3 everything works as expected. I'm located in Belgium and are users have the country code BE assigned to them.

David

**Comment by adorton-adobe** [comment]
Will you please post your LDAP config (with credentials stripped). If you don't want to post it here, you can email me at adorton@adobe.com.

Also - are you using an extension config? If so, can you send me that as well?

**Comment by dvdborn** [comment]
We're not using an extension config.

Here's the contents of our connector-ldap.yml file, without all the comments:

username: "user@mydomain.local"
host: "ldaps://mydomain.local:3269"
base_dn: "DC=stud,DC=mydomain,DC=local"
secure_password_key: ldap_password
search_page_size: 1000
require_tls_cert: False
all_users_filter: "(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))"
group_filter_format: "(&(objectCategory=group)(cn={group}))"
group_member_filter_format: "(memberOf:1.2.840.113556.1.4.1941:={group_dn})"
user_email_format: "{userPrincipalName}"
user_username_format: "{sAMAccountName}"
user_country_code_format: "{BE}"

**Comment by adorton-adobe** [comment]
I think I see the issue. Just remove the curly braces from `user_country_code_format`. The braces are used for attribute names, so you are telling the LDAP connector to look for an attribute called "BE". If you want to hard-code the country to always be "BE" then do this instead:

```yaml
user_country_code_format: "BE"
```

**Comment by dvdborn** [comment]
Thanks! That was indeed the cause. v2.5 now functions properly.
