### ISSUE TITLE
NOT syncing with 500 error

### ISSUE THREAD

**Issue by AsakaOkuyama** [adobe-apiplatform/user-sync.py#574]
The customer saw the 500 error, and users are not syncing correctly. The Python is 64 bit.

[2020-02-26.log](https://github.com/adobe-apiplatform/user-sync.py/files/4258529/2020-02-26.log)

It seems the POST reply 500 when access to https://usermanagement.adobe.io:443. In the past, he could see the result 200, and syncing was working. What's the problem with that?

**Comment by vossen-adobe** [comment]
I get this error from time to  time on my clever sync server, which is running 40 or so times a day with long syncs.  Usually it's just a hiccup and most runs are successful.  Does this happen every time?

**Comment by AsakaOkuyama** [comment]
One day there was a turning point; the error happens with each cycle, but we don't know why it happens without any changes.

**Comment by bhunut-adobe** [comment]
This issue is related to username != email address. UMAPI Engineering team have identified the issue on the backend and planning to push the fix to production sometime next Tuesday.

**Comment by adorton-adobe** [comment]
Closing this as it is a UMAPI issue and not a UST issue and there is a fix pending.

**Comment by bhunut-adobe** [comment]
Just to update on this. Bug fix have been deployed to Production. It should work as usual now
