### ISSUE TITLE
How to filter using Extension Attribute.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#577]
I want to know how to filter using Extension Attribute.
I know to be able to add any additional LDAP filters to the all_users_filter field in connector-ldap.yml.
Can I switch from LDAP filter to  Extension Attribute.

for example:
all_users_filter: "(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))("Extension Attribute name"=1))"

Other solution?

Regards,
Tomomi

**Comment by adorton-adobe** [comment]
Hi Tomomi - I'm sorry, but I don't think I understand your question. If you want to limit what the User Sync Tool sees as "all users", then you can use the `all_users_filter` to do that. Your example would include only users that have a specific attribute value.

You can also get additional user attributes using the [Extension Config](https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/advanced_configuration.html#custom-attributes-and-mappings) functionality and write sync logic around that.

**Comment by Tomomi99145** [comment]
@adorton-adobe 
Thank you for your response!!!

Yes, I want to know  how to limit what the User Sync Tool sees as "all users".
If I want to include only users that have a specific attribute value, can I specify custom attributes as the that attribute?
Only default attributes on AD?
Customer says want to filter using Extension Attribute.
I think the Extension attribute is theCustom Attribute in the link below.

https://docs.microsoft.com/en-us/exchange/recipients/mailbox-custom-attributes?view=exchserver-2019

Or before installing UST, can I use command(or other) to verify that the attributes can be specified?

Regards,
Tomomi

**Comment by adorton-adobe** [comment]
You can include any valid attribute. As long as the query is valid, it ought to work. The customer can test the query using `Get-ADUser` (using the `-LDAPFilter` paramater).

**Comment by Tomomi99145** [comment]
@adorton-adobe 
Thank you for your support!
Is "-LDAPFilter" an option for "Get-ADUser"?
I'm sorry for not knowing this.
Would you please give me a command example...

**Comment by adorton-adobe** [comment]
Here is some documentation. It's just an optional utility that the customer can use if they want to test the query.

https://social.technet.microsoft.com/wiki/contents/articles/28485.powershell-filter-results-with-active-directory-module-cmdlets.aspx

**Comment by Tomomi99145** [comment]
@adorton-adobe 
Thank you for your support!!
I'll try it.
Best Regards,
Tomomi

**Comment by adorton-adobe** [comment]
Closing this since there haven't been any comments for several months.
