### ISSUE TITLE
two-steps lookup - Unexpected LDAP failure reading group members: empty dn

### ISSUE THREAD

**Issue by bajwa-adobe** [adobe-apiplatform/user-sync.py#582]
When I set empty/blank base_dn for my customer environment and two-steps-lookup is enabled. UST fails with error `Unexpected LDAP failure reading group members: empty dn`.

- UST v2.5.0/Windows
- NetIQ eDirectory 9.1

```
base_dn: ''
...
two_steps_lookup:
  group_member_attribute_name: "member"
```

Here is output
```
2020-03-12 17:47:32 5536 INFO processor - ---------- Start Load from Directory -----------------------
2020-03-12 17:47:33 5536 CRITICAL main - Unexpected LDAP failure reading group members: empty dn
2020-03-12 17:47:33 5536 INFO main - ========== End Run (User Sync version: 2.5.0) (Total time: 0:00:10)
```

**Comment by adorton-adobe** [comment]
What happens when you set the `base_dn` to the root domain?

I'm also not sure if this is a UST issue or some limitation of the LDAP server. Or if it is necessarily related to two-step lookup. If you disable two-step lookup do you get the same error if you also specify a blank `base_dn`?

**Comment by bajwa-adobe** [comment]
I found it fails on NetIQ eDirectory which require `base_dn: ''` (empty/blank) and it fails on `ldap3.utils.dn.parse_dn` (LDAP3 parse) in `is_dn_within_base_dn_scope` which is called when two-steps lookup is enabled.  The function is as follows

```
    def is_dn_within_base_dn_scope(base_dn, dn):
        split_base_dn = ldap3.utils.dn.parse_dn(base_dn.lower())
        split_dn = ldap3.utils.dn.parse_dn(dn.lower())
        if split_base_dn == split_dn[-len(split_base_dn):]:
            return True
        return False
```
Adding a check to return true if base_dn is empty string fix the UST:
```
    def is_dn_within_base_dn_scope(base_dn, dn):
        # return true if base_dn is empty string such as global scope and no need to check user_dn is part of base_dn
        if base_dn is '':
            return True

        split_base_dn = ldap3.utils.dn.parse_dn(base_dn.lower())
        split_dn = ldap3.utils.dn.parse_dn(dn.lower())
        if split_base_dn == split_dn[-len(split_base_dn):]:
            return True
        return False
```

**Comment by adorton-adobe** [comment]
@bhunut-adobe can you please look at this and see if it makes sense to return `True` when the base DN is blank?
