### ISSUE TITLE
Error occurs when registering 6000 users.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#587]
Hi team,

Error occurs when registering 6000 users.
With 100 users it does not occurs.

Environment:
 OS→Linux
 Directory→Open LDAP

Error:
2020-03-14 15:02:14 22928 CRITICAL main - Unexpected LDAP failure 
reading group members: LDAPNoSuchObjectResult - 32 - noSuchObject - 
ou=XXXXX,dc=sss,dc=bbb,dc=ac,dc=jp - None - searchResDone - None

User schema example:
dn: cn=testgroup,ou=Group2,dc=sss,dc=bbb,dc=ac,dc=jp
objectClass: groupOfNames
member: uid=test20082,ou=XXXXX,dc=sss,dc=bbb,dc=ac,dc=jp

Why do I get an error when increasing to 6000 users?

Regards,
Tomomi

**Comment by Tomomi99145** [comment]
Does anyone have a solution?

Added information,

・UST version 
2.5
・command
./user-sync -t -c ./user-sync-config.yml --users all --adobe-only-user-action exclude

・connector-ldap.yml 
-----------------
username: "xxxxxxx"
password: "xxxxxxx"
host: "ldap://xxxxxx"
base_dn: "dc=sss,dc=bbb,dc=ac,dc=jp"
authentication_method: Simple
user_identity_type: federatedID
search_page_size: 1000
require_tls_cert: False
all_users_filter: "(objectClass=SFCLocalClass)"
group_filter_format: "(&(objectClass=groupOfNames)(cn={group}))"
two_steps_lookup:
   group_member_attribute_name: "member"
user_email_format: "{uid}@sss.bbb.ac.jp"
user_given_name_format: "Blank"
user_surname_format: "Blank"
-----------------

**Comment by Tomomi99145** [comment]
Does anyone have any solution?
Is ”search_page_size” involved?

**Comment by Luci2015** [comment]
search_page_size is not involved here.
before thinking about limits imposed on LDAP side, can you send over a custom openLDAP query  that the sys admin would use to extract all the users of interest locally and also what is the number of users you obtain with it when run directly on LDAP side? are there any errors when running it?

**Comment by Tomomi99145** [comment]
@Luci2015 
Thank you for your response!!

・Custom openLDAP query

a. Query to extract users to be synchronized
ldapsearch -h localhost -x -W -D "cn=XXXX,dc=XXX,dc=xxx" -b 
"dc=XXX,dc=xxx" "(objectClass=SFCLocalClass)"

b. Query to extract group members to be synchronized
ldapsearch -h localhost -x -W -D "cn=XXXX,dc=XXX,dc=xxx" -b 
"dc=XXX,dc=xxx" '(&(objectClass=groupOfNames)(cn=adbgroup))'

The number of users you obtain with it when run directly on LDAP side

a. users: 6074

b.group members: 6074

>are there any errors when running it?
nothing

**Comment by Luci2015** [comment]
hmm, template looks ok, not sure about the values, since they are obfuscated. 
could be nothing, but there is a slight difference to what you sent previously in your first message:
-> base_dn was obfuscated to: 'dc=sss,dc=bbb,dc=ac,dc=jp'
-> the ldapsearch in your second message has just 2 'dc=' values: 'dc=XXX,dc=xxx'
Can you try to use a broader range on the base_dn, maybe even an empty one.
I mean:
base_dn: ""

**Comment by Tomomi99145** [comment]
@Luci2015 
I confirmed that v2.5.1 has been released.
Want to know if this version could help this trouble.
Does this version help this issue?

**Comment by adorton-adobe** [comment]
Closing this since there have been no comments since March.

@Tomomi99145 please let us know if you are still experiencing this issue.
