### ISSUE TITLE
”ModuleNotFoundError” is occurred.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#605]
Hi team,
I tried new feature by v2.6.0.
The new feature I tried is "New directory connector: Admin Console".
But the execution failed with an error.
Do you know the solution?

Error is below;
--------------
2020-05-13 10:37:13 2244 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "user_sync\app.py", line 186, in sync
  File "user_sync\app.py", line 372, in begin_work
ModuleNotFoundError: No module named 'user_sync.connector.directory_adobe_console'

**Comment by vossen-adobe** [comment]
Oops - looks like we forgot to add
import user_sync.connector.directory_adobe_console  to app.py when building the standalone
dynamic import doesn't work correctly otherwise.

Will do a PR for this tomorrow

**Comment by Tomomi99145** [comment]
@vossen-adobe 
Thank you for your support!
Is this already fixed to work correctly?
Tomomi
