### ISSUE TITLE
error decrypting private key

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#610]
last version I tested (2.6.0) still uses an outdated cryptography module causing an error on attempt to decrypt private keys encrypted with openssl versions higher than 1.1
I do remember having a side test with the latest available module, some time last year, and I was able to decrypt so wondering when UST will pack it as well.

**Comment by vossenv** [comment]
I believe we can update this now that we have dropped PEX.  See:

https://github.com/adobe-apiplatform/user-sync.py/issues/484

**Comment by adorton-adobe** [comment]
I've bumped the version to 3.9.7, the latest release.

**Comment by Luci2015** [comment]
I can try to build it for a Mac or Linux by the end of the week or just run it from source with the dependencies from the setup file.

**Comment by Luci2015** [comment]
I've build a binary for Win, enventually, and it does not seem to be working. Still getting the same error as before.
I used openssl v. 1.1.1d to encrypt.
Can you please have a test on your end as well? 
I don't remember if pycryptodome was used at that time or something else. Need to dig in the archives to see what I did back then..

**Comment by Luci2015** [comment]
the standalone function works OK with decrypt if the right data is being used as input.
gave it a quick look and I think the error lies here:
- line 42 in [here](https://github.com/adobe-apiplatform/user-sync.py/blob/65e34cc789ee9991c18d83c9108ae6fc0f6376bf/user_sync/encryption.py#L40) expects that data be the result of file.read()
- while line 32 in [here](https://github.com/adobe-apiplatform/user-sync.py/blob/v2/user_sync/connector/umapi_util.py) inserts the file path instead of the data

**Comment by vossen-adobe** [comment]
Not sure how that slipped through - it was introduced in february.  I've added a quick PR to resolve.  You can also now use UST to do the encryption instead of openSSL and it should with 

`user-sync.exe encrypt`

This will give you an appropriately encrypted cert which is guaranteed to work correctly.

**Comment by Luci2015** [comment]
Thanks! In the use-case I have I'm should not generate the pair, rather decrypt an existing one.
I'll do another .exe build over the next few days and test this fix.
Thanks again!
