### ISSUE TITLE
 Is it possible to register the Enterprise ID and Federated ID at the same time using a CSV file, and does Admin Console have a problem?

### ISSUE THREAD

**Issue by takasead** [adobe-apiplatform/user-sync.py#625]
The ID type when User Sync Tool is executed by LDAP communication is only the ID type specified in user-sync-config.yml can be set.
However, in the case of csv files, when the user Sync Tool was run in test mode with the ID type specified for each user in the csv file, it was possible to set each ID type for each user.
So, is it okay to actually use the CSV file to perform user registration to the Admin Console with different ID types such as Enterprise ID and Federated ID?
Also, if you do not set any ID type information in the CSV file, it will be registered with the ID type specified in user-syn-config.yml. 
Is my understanding okay with this?

**Comment by adorton-adobe** [comment]
`directory_users.user_identity_type` in `user-sync-config.yml` specifies the default identity type. The identity type can be overridden in the identity connector config file in some cases. For example, in `connector-ldap.yml` it can be overridden for all users from the source.

CSV files can set any valid identity type and that type will be used for that user. If the field is blank, the tool will use the default specified in the main config.
