### ISSUE TITLE
User Sync tool is no longer processing Product Profiles

### ISSUE THREAD

**Issue by cbalanoiu** [adobe-apiplatform/user-sync.py#626]
Hi guys,

I just discovered this today with a customer and tested on 2.6.0 and 2.4.3.
If a user is entitled to both a group and directly to a separate product profile and based on the group mapping he should only be a member of the group, the tool completely ignores the direct product profile entitlement. 
This is a big issue as the users no longer get stripped of their entitlements and customers have to manually revert to updating user intitlements via CSV in Admin Console.

**Comment by adorton-adobe** [comment]
I've tested this pretty thoroughly, but I can't reproduce it. Let me know if this issue persists.
