### ISSUE TITLE
The tool does not accept encrypted keys - always throws an error

### ISSUE THREAD

**Issue by cbalanoiu** [adobe-apiplatform/user-sync.py#627]
The tool just does not work with an encrypted key. it always throws an error when configuring one:
"Error decrypting private key, either the password is wrong or: RSA key format is not supported - Error while processing encrypted data. Data may not be in RSA format or is corrupt."

Tested this with three keys in two environments.

**Comment by adorton-adobe** [comment]
How are you encrypting the key?

**Comment by cbalanoiu** [comment]
using the standard openssl command provided in the config file:
openssl pkcs8 -in private.key -topk8 -v2 des3 -out private-encrypted.key

I used a self signed key generated with openssl that I've been using for a good while.

**Comment by adorton-adobe** [comment]
What OS are you using to run the openssl command? If you're using Windows, are you using WSL, Cygwin, or a native Windows build of OpenSSL? What OS are you using to run the UST?

What version of the sync tool are you running?

**Comment by cbalanoiu** [comment]
UST 2.6.0 
Everything was done on a Windows Server 2012 R2 Standard.
The commands were run through Cygwin. 

I used the same setup in the past and this worked just fine.

The customer's env was still Windows server, not sure which version and they encrypted the files on linux directly via an openssl instance.

**Comment by adorton-adobe** [comment]
What version of openssl?

**Comment by cbalanoiu** [comment]
openssl 1.0.2k

**Comment by adorton-adobe** [comment]
There are a couple of things you can try:

1. Upgrade openssl on Cygwin or try a newer openssl on WSL, Linux or macOS. We had to upgrade our cryptography dependency to maintain compatibility with newer versions of openssl (see #610). My guess is the newer cryptography build isn't compatible with encrypted files created in older versions of openssl.

2. Use the UST's native cert encryption tool (new in v2.6.0). See [the docs](https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/additional_tools.html) for more information.

If you to use the UST's native cert encryption tool, please be aware of some issues in v2.6.0 with the encrypt/decrypt CLI - when you encrypt, the tool will encrypt the key file and replace it with the encrypted version. There currently isn't a way to specify a different filename for the encrypted key. It also will not prompt you to confirm that is overwriting the file. These issues will be addressed in v2.6.1 (the PR has already been merged to `v2`).

I also just noticed we need to update the usage examples to use the executable build and not the pex file.

**Comment by adorton-adobe** [comment]
@cbalanoiu did you get a chance to try either of the things I suggested?

**Comment by adorton-adobe** [comment]
I'm closing this since it does not appear there is anything to do but ensure the key is encrypted with a sufficiently recent version of OpenSSL.
