### ISSUE TITLE
About UST synchronization error for users in different domains with groups in LDAP

### ISSUE THREAD

**Issue by takasead** [adobe-apiplatform/user-sync.py#629]
I received a question from a customer at a Japanese university. I have to answer in the near future, so please tell me about the operation below.

Different domains are registered for the email (LDAP attribute is mail) of the user information associated with the group registered in the LDAP database to be synchronized with the User Sync Tool.

If a user in that domain who has an email in a domain that is not registered in the Admin Console is associated with the group, the User Sync Tool behaves as a registration error for all associated users in the group.

According to the UST log, if [success] is [0], even a user with a domain registered in Admin Console cannot perform group mapping or register a user in Admin Console.

Is my perception correct?

Also, if there are the following methods, please tell me how.
Of the users to be synchronized registered in the LDAP group, users with domains not registered in Admin Console are not registered, and only users with domains registered in Admin Console are registered.

For example, I want to realize something like this

"Ust.aooo.online" has been registered in Admin Console. "Shiodeji.lan" has not been registered. If users with each domain are registered in the LDAP group, execute UST with that group as the synchronization target.
sync0004@shiodeji.lan is not newly added because the domain is not registered in Admin Console. sync0003@ust.aooo.online and sync0002@ust.aooo.online are domains registered in Admin Console, so users can be added.

Thank you and best regards,

**Comment by vossen-adobe** [comment]
I'm not sure what you mean about the log, but yes - users with unclaimed domains will trigger an error from umapi along the lines of "illegal to invite user from another organization".  It doesn't really matter how they are grouped in ldap - this will always be the case.

**Comment by takasead** [comment]
[UST_log.txt](https://github.com/adobe-apiplatform/user-sync.py/files/5192659/UST_log.txt)
Thank you for your answer.
I attached log of UST which I carried out in inspection environment.
Explanation of the inspection environment
There are three users in the "ust" group.
sync0004,sync0003,sync0002
The domain 'shiodeji.lan' has not completed domain validation in the Admin Console.
From the log results, it appears that these three people are not registered to the Admin Console.I understood from the log that
sync0002 and sync0003 failed to map the Admin Cosole user group, but the user registration was completed.
Do you agree with me?
Also, is there a way to register that user registration and user group mapping succeed?

**Comment by Luci2015** [comment]
From your log, only the action_1 presents an error that tells you the domain used for that account is not claimed in Admin Console, however there is no sspecific error present for actions 2 and 3. 
This happens only when you run the tool in test-mode. 
There was a single call to the API endpoint that contains a batch of 3 actions. Unfortunatelly for test mode runs, if at least one action has an issue, all the others will show that "No valid users were found in the request" message, even the ones that would work outside test-mode.

If you were to run this in production, this will happen:
-> an error for the account sync0004@shiodeji.lan because 'shiodeji.lan' is not a validated domain in Admin Console
-> a successful creation for the accounts sync0003@ust.aooo.online and sync0002@ust.aooo.online and an add to group 'ust group' in Admin Console after creation.

Presence of the {'add': {'product': ['ust group']}} in your log shows the mapping works, otherwise you'd only have the create action.

**Comment by takasead** [comment]
thank you for your answer.
I got it、The fact that the other two registrations appeared to be in error means that they were in test mode.
So, I'd like to quit the test mode and actually submit to the Admin Console with the registration command, is there any bad effect on the Admin Console?

**Comment by Luci2015** [comment]
If you did no other change to the setup, what you see in the log output would happen as well outside test-mode.

**Comment by takasead** [comment]
@Luci2015
Thank you for your answer.

I synced a group in LDAP using the User Sync Tool.

As you answered, only the email address of the domain registered in the management console was registered as a user. The mapping was also successful for the admin console user groups.

I also found that if you specify an attribute in the "all_user_filter" item in "connector-ldap.yml", you can filter the users you want to register.
I also found that using this, I could avoid the error by filtering the users when registering a group with a mixture of different domains.

It was helpful! Thank you!

**Comment by adorton-adobe** [comment]
It looks like we have a solution. Is it OK if I close this?

**Comment by takasead** [comment]
@adorton-adobe

Thank you very much for contacting me.
Thanks to everyone, the problem has been resolved.
Please close this thread.
Thank you very much.
