### ISSUE TITLE
Error decrypting private key, either the password is wrong or: RSA key format is not supported - Error while while processing encrypted data. Data may not be in RSA format or is corrupt.

### ISSUE THREAD

**Issue by petersseth86** [adobe-apiplatform/user-sync.py#633]
User Sync Tool v2.6.0
I am getting the following: "Error decrypting private key, either the password is wrong or: RSA key format is not supported - Error while while processing encrypted data. Data may not be in RSA format or is corrupt." when trying to run UST on Server 2012 R2 or Windows 10. I created a new public/private key pair at Adobe.io under Service Account Credentials (the old one had expired). I downloaded the private.key file and used OpenSSL 1.1.1f (Cygwin), 1.1.0 (Ubuntu) ,1.0.2u (Windows-compiled Binary) with the following command "openssl pkcs8 -in private.key -topk8 -v2 des3 -out private-encrypted.key" to create an encrypted private key file. None of those could be decrypted by running UST with the passphrase (priv_key_pass) straight in the config file or with the config file setup to use 'Windows WinVaultKeyring' credential from Credential Manager (secure_priv_key_pass_key), both end in the above error...it's pulling the passphrase ok. I also tried using UST to create the encrypted private key file "user-sync encrypt" on Windows Server 2012 R2, Windows 10 and Linux...still none of them can be decrypted by UST. I'm at a loss here, honestly...any assistance would be greatly appreciated. It was all working just fine less than a month ago, when the certificate expired.
![Adobe_UST_Github_Issue](https://user-images.githubusercontent.com/28606874/93267652-9caa6800-f771-11ea-8cb6-442cf4b42756.png)

**Comment by vossen-adobe** [comment]
Open SSL has known issues with pycryptodome depending on the versions of both.  I suggest using the build in encryption:

https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/additional_tools.html

It is the same type of encryption, but since it is done using cryptography it is able to be decrypted successfully.

**Comment by petersseth86** [comment]
When I upgraded the UST version to 2.6.0, I noticed that it now has built-in encryption ability (which is awesome), but using that functionality gives the same error.

From original comment [ I tried using UST to create the encrypted private key file "user-sync encrypt" on Windows Server 2012 R2, Windows 10 and Linux...still none of them can be decrypted by UST. ]

**Comment by vossen-adobe** [comment]
Ah yes - I remember, there was a typo which had actually broken this in 2.6 release.  If you're able to build from the current code, that should fix any such issues.

**Comment by adorton-adobe** [comment]
Fixed in #611
