### ISSUE TITLE
Typo in connector-umapi.yml ?

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#639]
**Description**
the current connector-umapi.yml file contains for the secure version of the client_id the reference:
`secure_client_id: umapi_client_id`

I think the expected string value should be:
`secure_client_id_key: umapi_client_id`

(because [here](https://github.com/adobe-apiplatform/user-sync.py/blob/v2/user_sync/connector/umapi_util.py) the 
`api_field = 'client_id' if 'client_id' in config or 'secure_client_id_key' in config else "api_key"`
expects `secure_client_id_key` and also because 'secure_' and '_key' are defined prefix and suffix when used with keyring.

**Environment**
 - UST version: 2.6.1
 - OS type and version: all

**Comment by vossen-adobe** [comment]
@mbonish can you look at this?

**Comment by mbonish** [comment]
yes, I will create a new PR with the fix
