### ISSUE TITLE
Allow to disable admin roles syncing

### ISSUE THREAD

**Issue by kingsuk248** [adobe-apiplatform/user-sync.py#648]
**Is your feature request related to a problem? Please describe.**
All admins in Sign must be appropriately grouped and mapped in the admin console and/or directory source. Any admins who are not mapped are reset to normal user status by the sync.

Link to any relevant bugs (e.g. "Relates to bug #xxx")
https://jira.corp.adobe.com/browse/DMESVCS-248

**Describe the solution you'd like**
As a <user> I should be able to <manually assign admins> without creating groups.

**Describe alternatives you've considered**

**Additional context**

**Comment by adorton-adobe** [comment]
This appears to be related to Sign phase II
