### ISSUE TITLE
Change SSL cert verify reference from class to invocation_defaults

### ISSUE THREAD

**Issue by shasibhusanJena** [adobe-apiplatform/user-sync.py#652]
Pass Boolean as a configuration option instead of a class property

**Describe the solution you'd like**
Find the reference for ssl_cert_verify which are currently class [roerpties in below-listed classes
Remove reference from classes like

- directory_adobe_console.py
- umapi.py
- app.py

**Comment by adorton-adobe** [comment]
These changes need to merged to Danimae's branch in PR #608
