### ISSUE TITLE
Synchronize user information between Admin Consoles

### ISSUE THREAD

**Issue by takasead** [adobe-apiplatform/user-sync.py#660]

**Comment by takasead** [comment]
In order to use the domain claimed in the Admin Console in another Admin Console, trustee settings have been made between the Admin Consoles.

I would like to register the set Admin Console user information in the Admin Console for which trustee settings have been made.
By using "connector-adobe-console.yml" in User Sync Tool, I think that user information can be synchronized between Admin Console.
I specified connector-adobe-console.yml in "user-sync-config.yml" and set the UMAPI connect information of the sync source Admin Console in "connector-adobe-console.yml".
I ran the following command.
"User-sync.exe -t adobe-only-user-action exclude"
However, I got an error. The message is as follows.
"CRITICAL main --Config file must be specified for connector type ::'ldap'"

I think the settings are different somewhere, but I don't know.


I would appreciate it if you could tell me.
Thank you.

**Comment by Luci2015** [comment]
What if you replace the invocation_defaults that contains:
`  connector: ldap`
with:
`  connector: adobe_console`

**Comment by takasead** [comment]
@Luci2015

Thank you for answering.


I commented out "ldap: connector-ldap.yml" in "connectors:" in the "user-sync-config.yml" file.
After that, "adobe_console: connector-adobe-console.yml" was enabled by removing the "#".


In the "connector-adobe-console.yml" file, the information obtained from the technical account of Admin Console, which is the synchronization source, is already registered.

I ran the following command.
"User-sync.exe -t adobe-only-user-action exclude"
However, I got an error. The message is as follows.
"CRITICAL main - Config file must be specified for connector type ::'ldap'"

Is there any other possible setting change?


I would be happy if you could tell me.

Thank you.

**Comment by takasead** [comment]
@Luci2015



Succeeded！


Thank you for providing the information.
I found "invocation_defaults:" in the "user-sync-config.yml" file!
I changed from "connector: ldap" to "adobe_console" and it worked!

By the way, I added the "--users mapped" option to the command to be executed. Then I got an error.

"WARNING connector -No group found for: mapped"

I ran the following command without the "--users mapped" option.
"User-sync.exe -t --adobe-susers mapped adobe-only-user-action exclude"

Only the target user group of the Admin Console to be synchronized has the user information synchronized to the user group of the destination Admin Console.

I was able to do what I wanted to do.

Thank you for your help.

**Comment by Luci2015** [comment]
Your command line looks malformed if used just like that.
All you need is just `user-sync.exe` and control everything else from the `invocation_defaults`. For the 2 options you mentioned above, the invocation settings would be:
```
test_mode: Yes
users: mapped
```
When you sync from a different console to another, `directory_group` is the source group name from the source Console, and `adobe_groups:` contains the name of the target Console user-group or PLC.
