### ISSUE TITLE
Please tell me how to solve the error when synchronizing users using UST.

### ISSUE THREAD

**Issue by takasead** [adobe-apiplatform/user-sync.py#671]
I received a report from a Japanese customer that I received the following error message. (Excerpt from the log file given by the customer)
code: "error.internal.create_failed" 
message: "Could not create person of type createFederatedID"

From HELPX, I thought that it could be solved by "complaint of domain to register", "setting of Azure or Google", etc. But I wasn't sure.
https://helpx.adobe.com/enterprise/kb/UMAPI-UST.html
"COULD NOT CREATE PERSON FOR TYPE 2 OR 3 [...]"？

What measures should I take to resolve this error?

It would be very helpful if you could tell me!

**Comment by Luci2015** [comment]
please read [this](https://github.com/adobe-apiplatform/user-sync.py/issues/664#issuecomment-738786486) thread.

**Comment by takasead** [comment]
Thank you for your reply!

You have read the specified page.
Ask the customer to check the following:
・"Synchronize" settings in the directory to be synchronized
・ If it is as shown in the image posted by jli-alt, delete the setting.

By the way, when I intentionally ran UST in the Admin Console directory with halfway sync settings, I got the same error (UST 2.6.0).
The UST version of the customer inquired this time is 2.5.0.


The "verification screen" I went to.
Admin Console -> Settings -> under the Sync tab/menu,
![image](https://user-images.githubusercontent.com/70120450/104279106-1ae30500-54ed-11eb-8340-532dad62858d.png)
error log
![image](https://user-images.githubusercontent.com/70120450/104279391-8fb63f00-54ed-11eb-8e95-aa792b259305.png)


We will report after the confirmation is completed.

**Comment by takasead** [comment]
I got the current information of Admin Console sync settings from a customer.
It will be in Japanese, but I will submit the image.
![image](https://user-images.githubusercontent.com/70120450/104547519-172cbb00-5672-11eb-8eb5-ff811cadf805.png)
In the "Sync not set up" state, I found that the synchronization was not set.

![image](https://user-images.githubusercontent.com/70120450/104547565-30ce0280-5672-11eb-87f1-a3412cedc842.png)
Also, paste a part of the log submitted by the customer. (User name is * 3. Company name is converted to * 4.)

Is there any other solution?

**Comment by Luci2015** [comment]
Is the tas.****.co.jp under the influence of an Azure or Google connector setup? If the domain is claimed in current Org, does it have its own Directory and the Sync Source card present?
Is this domain claimed in a different Org and only trusted in this one? If that is the case, in the main org that has the claim on this domain, is there an Azure or Google connector set up or it presents that Sync Source not started card in Settings? 
What are the OrgIDs in question?

**Comment by takasead** [comment]
Thank you for contacting us!
I am always grateful for the opinions of Luci2015.

However, I am aware that my knowledge is overwhelmingly insufficient.
This is a confirmation item that I received, but I could not understand it accurately.
I think you gave me a hint to ask the customer who is having the error about the setting information, but please tell me more about how to get the setting information to the customer.

1.Is the tas.****.co.jp under the influence of an Azure or Google connector setup? 
> What kind of settings and situations does "under the influence of an Azure or Google connector setup?" For example, does it mean that the "tas.****. Co.jp" domain is registered in "Custom domain nemes" of the Azure portal? (My experimental environment uses UST to sync users with domains registered in "Custom domain nemes", so I don't think this is the case, but otherwise I didn't think of it)

2.If the domain is claimed in current Org, does it have its own Directory and the Sync Source card present?
> The customer has a Federated ID directory in the Admin Console. I suspect you are using SAML. I don't think that user synchronization uses "Azure Sync" like the previous image. Now, where should I check the settings for "Does the domain have its own directory and sync source card?" Do you want to check the directory and domain settings of Admin Console?

3.Is this domain claimed in a different Org and only trusted in this one? 
> When registering a domain in Admin Console, register a token issued by Admin Console in the TXT record of the DNS server. Is this question to check "Is tas.****. co.jp registered on another DNS server (DNS service such as Azure or Google?)?"

4.If that is the case, in the main org that has the claim on this domain, is there an Azure or Google connector set up or it presents that Sync Source not started card in Settings?
> Does it mean to check "Is Admin Consle and Azure or Google working together using a connector?" Or "Is the directory for Federated ID set to sync users?"

5.What are the OrgIDs in question?
What is "OrgID"? Should I check the character string on the upper right of Admin Consle? Where should I ask the customer to check?

Sorry for the annoying question.
We look forward to hearing from you.

Thanking you in advance.

**Comment by Luci2015** [comment]
I took a look on the provided org and there are about 20 domains claimed there, including the *tas. one. 
The Sync Source card of the connector is missing in Settings menu for the AD- Directory, therefore you should not have any issues in syncing federatedIDs with using this domain, via the UMAPI /UST.
Now, I see users have Username and Email different in the Admin Console. In this situations, both domains used for mail and username should be claimed in Admin Console, just like @tas.* one.
You need to get in touch with developer support (wwds@adobe.com) and share with them the debug level log file for further troubleshooting, if the error is still present.
At first glance, the sync should work fine now.

**Comment by takasead** [comment]
Thank you for contacting us!

I checked the log again for the domain of the user ID that caused the error.

It seems that there are no domain claims for "tas.^^^^. Co.jp" in the email domain and "^^^^ gr.com" in the username domain.
![image](https://user-images.githubusercontent.com/70120450/105028560-851f1b00-5a94-11eb-9a74-0a530649cf28.png)
Ask the customer to confirm the registration status of the domain.

So I came up with a hypothesis.

I thought that user synchronization would fail if both the username domain and the email domain were not registered in the Admin Console.
But,
I saw the log of another time zone.
User synchronization was successful when the domain ID of the username domain was "^^^^gr.com" and the email domain was the "@ pub.^^^^. Co.jp" domain.
The "@ pub.^^^^. Co.jp" domain seems to be registered in the Admin Console.
![image](https://user-images.githubusercontent.com/70120450/105028719-bac40400-5a94-11eb-962c-6a77b4118e19.png)

From the above results, I thought that user synchronization would fail if the email domain was not registered in the Admin Console. (The username domain is the same domain as the one that caused the error)
Is my idea wrong?

**Comment by Luci2015** [comment]
You're not wrong -> any domain you use in the synchronization process, be it for Email or for Username, has to be claimed in Admin Console first and moreover, they have to be linked to same Directory in Admin Console.

**Comment by takasead** [comment]
Thank you for contacting us!

When I checked the customer's directory and domain settings in-house, the "@ tas. ^^^^.co.jp" domain was registered and associated with the directory.
I would like to consult with the development support (wwds@adobe.com) that I was taught the last time.

Thank you for your support.
