### ISSUE TITLE
Removing more than 10 group membership

### ISSUE THREAD

**Issue by madumro** [adobe-apiplatform/user-sync.py#672]
Hi,

Does the tool have a rule in case users need to be removed from more than 10 groups? UMAPI doesn't allow this, but I think UST throws a throttling action and it doesn't seem to do anything else. 
Is it possible this to stop the script after 3 "UMAPI timeout...service unavailable (code 504)"?

Thank you!

**Comment by adorton-adobe** [comment]
Yes - if a list of groups to assign/remove exceeds 10 at a time, the UST will split the list and create more user update commands.
