### ISSUE TITLE
User Sync Tool Certificate Expired

### ISSUE THREAD

**Issue by takasead** [adobe-apiplatform/user-sync.py#678]
Hello, expert of everyone.

please tell me!
I was contacted by a Japanese customer who is using the User Sync tool.
The message is "User Sync Tool certificate has expired".
I think that the problem will be solved if you renew the certificate by following the steps below.
1. Log in to the developer portal (console.adobe.io/home) as an Admin Console administrator.
2. Click Service Account (JWT) in the left pane of the previously created Project
3.Click the Generate a public / private keypair button to create a new key. And it downloads automatically
Four.
4. Unzip the downloaded [config.zip] file
5. Take out the new [private.key] in the unzipped [config] folder and replace the old [private.key] used by UST.
![image](https://user-images.githubusercontent.com/70120450/108477558-b595e700-72d6-11eb-971a-76de5fc104e6.png)

What do you think?
Is the procedure I thought of correct?

Thank you.

**Comment by cbalanoiu** [comment]
Hi Taka-san
Yes those are the correct steps.
Alternatively the customer can bring in their own SSL certificate and associated private key. In this case both certificates should in pem format with the private key having a .key or .pem extension and the public certificate having a .cer or .crt or .pem or .pfx extension.

**Comment by takasead** [comment]
@cbalanoiu

Thank you for your reply!
Thank you for the correct information.

Can I ask additional questions?

The Japanese customer who received the inquiry has been using UST for two years, and I imagine that the administrator portal site was set up with the previous UI.
The site that renews the certificate this time has a new UI, so it seems to be in trouble.

Should I tell the customer that the "project name" of the new UI is the same as the information set in the Name of Integration Details?
![image](https://user-images.githubusercontent.com/70120450/108644132-17ca3400-74f1-11eb-8848-2153eebe1ae3.png)
　Thank you.
