### ISSUE TITLE
Dynamic/wildcard groups support for UST Adobe Sign Connector - dynamic adobe sign group management

### ISSUE THREAD

**Issue by JonasTusar** [adobe-apiplatform/user-sync.py#679]
**Is your feature request related to a problem? Please describe.**
Dynamic/wildcard groups support is available on UST but not available on current Adobe Sign Connector.  Without that customers have to mention each of sign groups full name to Adobe Sign Connector configuration in addition to it, in order to assign Adobe Sign specific rights such as group admin etc.

**Describe the solution you'd like**
Include dynamic/wildcard group support for the Adobe Sign connector to enable dynamic adobe sign group management

**Describe alternatives you've considered**
None available

**Comment by adorton-adobe** [comment]
We are in the process of revamping the Sign connector functionality to expand its capabilities. Once we make the initial release of that feature, we'll look at introducing dynamic group management.
