### ISSUE TITLE
Please tell me the procedure for upgrading the User Sync Tool from 2.5.0 to 2.6.2.

### ISSUE THREAD

**Issue by takasead** [adobe-apiplatform/user-sync.py#680]
Hello, expert of everyone.

please tell me!
This is a question from a Japanese customer who uses the User Sync Tool.
The customer is using version "2.5.0".
Is the following recognition correct about how to upgrade to the latest version "2.6.2"?

1. Uninstall Python that was used at the time of "2.5.0". Then delete the "C: \ Program Files \ Adobe \ Adobe User Sync Tool" directory (private.key is available in 2.6.2, so make a backup)

2. Download the latest version "2.6.2" from the following URL "user-sync-v2.6.2-win64.zip".
https://github.com/adobe-apiplatform/user-sync.py/releases/tag/v2.6.2

3. Unzip the ZIP file and run "user-sync.ext" at the command prompt

I want to know the most!
Is it necessary to do the work of "1."?
In fact, I was able to use it in my verification environment by simply adding 2.6.2 with 2.5.1 installed.
So, is the version upgrade work of User Sync Tool correct in the procedure starting from "Step 2"?

Thank you.

**Comment by adorton-adobe** [comment]
The customer does not need to uninstall Python if they don't want to. They just need to extract the 2.6.2 executable to their user sync directory and run it from there.

**Comment by takasead** [comment]
Thank you for your response.
 First of all, I would like to propose 2 and 3. I would like to propose 1 after the operation is stable.

It was helpful!
Thank you for your kind input.
