### ISSUE TITLE
Adobe Sync task is now failing

### ISSUE THREAD

**Issue by jackkelly13** [adobe-apiplatform/user-sync.py#683]
When running an Adobe Sync task in a Windows 2016 server, I occasionally get the result "The operator or administrator has refused the request. (0x800710E0)

Today, I received a new error:

"UMAPI timeout...service unavailable (code 429 on try 1)

**Comment by Luci2015** [comment]
Could be that one task was already running and a new one got triggered -> "The opperator.." error might be telling you that.
You may be running the UST too often.
It should be run at intervals > 2 hours in between. If the task takes a longer time (say 5 hours) to complete, you will, of course, set it to run at intervals higher than that.

**Comment by jackkelly13** [comment]
Thank you for the comment. That makes sense in regards to the UMAPI timeout, but is that also in reference to the request refusal error?

**Comment by adorton-adobe** [comment]
Can you please post a screen shot of the operator error? Is it coming from Windows, or is it logged in the sync tool?

**Comment by adorton-adobe** [comment]
The error appears to be coming from Windows Task Manager and may be related to file permissions:

https://stackoverflow.com/questions/36281197/the-operator-or-administrator-has-refused-the-request-task-scheduler

**Comment by adorton-adobe** [comment]
Closing this as there hasn't been any recent activity. Please re-open it if this issue isn't resolved.
