### ISSUE TITLE
Is there any plan to support AAD using GraphQL?

### ISSUE THREAD

**Issue by Hojune-MS** [adobe-apiplatform/user-sync.py#687]
We would love to try this solution out but as part of tenant of such a big organization. Installing AAD DS in our subscription seems to be nearly impossible for us.

Azure AD has a GraphQL API that we can use to the user information and group information.

Is there any chance you will support this in the future natively?

Thanks

**Comment by adorton-adobe** [comment]
We don't have any plans to support GraphQL in Azure AD. The admin console natively supports Azure AD sync using SCIM, no UST required:

https://helpx.adobe.com/enterprise/admin-guide.html/enterprise/using/add-azure-sync.ug.html
