### ISSUE TITLE
[Sign Sync]privacy-policy admin can be granted?

### ISSUE THREAD

**Issue by konno-adobe** [adobe-apiplatform/user-sync.py#691]
Does anyone know if privacy-policy admin can be granted?
I want to use the Sign Sync function of User Sync and assign privacy-policy admin, but as far as I can see in the manual, there is no option for privacy-policy admin and only account admin and group admin can be found.
https://adobe-apiplatform.github.io/user-sync.py/en/success-guide/sync_adobe_sign.html#configuring-the-connector-1

**Comment by adorton-adobe** [comment]
The Sign API does not provide a way to manage privacy admin status.

https://secure.na1.adobesign.com/public/docs/restapi/v5#!/users/modifyUser

![image](https://user-images.githubusercontent.com/25495410/112233746-930e2b00-8c00-11eb-842b-5d97bf4c91b6.png)
