### ISSUE TITLE
User-Sync (2.6.2) is failing however User-Sync (2.6.0) is working

### ISSUE THREAD

**Issue by AbhishekGuptaACN** [adobe-apiplatform/user-sync.py#692]
**Description**
We tried to upgrade the adobe sync tool from version 2.6.0 to 2.6.2 but the sync is failing. However it is perfectly working in 2.6.0 version.

**Steps to reproduce**
* We have replaced the sync file with the new one and tried the run.
* Command-line- we used command line as well as powershell but both failed in the new version- "user-sync.exe --process-groups --adobe-only-user-action remove --update-user-info"
* Error from 2.6.2 version:
2021-03-25 10:31:06 11940 DEBUG umapi - umapi: creating connection for org 6FE936A5559694837F000101@AdobeOrg at endpoint https://usermanagement.adobe.io/v2/usermanagement
2021-03-25 10:31:06 11940 DEBUG urllib3.connectionpool - Starting new HTTPS connection (1): ims-na1.adobelogin.com:443
2021-03-25 10:31:06 11940 CRITICAL main - Connection to org 6FE936A5559694837F000101@AdobeOrg at endpoint https://usermanagement.adobe.io/v2/usermanagement failed: HTTPSConnectionPool(host='ims-na1.adobelogin.com', port=443): Max retries exceeded with url: /ims/exchange/jwt (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))
2021-03-25 10:31:06 11940 INFO main - ========== End Run (User Sync version: 2.6.2) (TEST MODE) (Total time: 0:00:01) 

**Expected behavior**
Sync tool should work for new version as well.

**Screenshots**

**Environment**
Windows server 2016.

**Comment by adorton-adobe** [comment]
It looks like the UMAPI client is unable to connect to the identity endpoint to get and API token. We haven't make any changes to `umapi-client.py` recently that would impact that connection:

https://github.com/adobe-apiplatform/umapi-client.py/blob/v2/.changelog/changelog.md

I have a few questions:

1. Does this happen every time you run 2.6.2?
2. Have you made any changes to your UST config files?
3. Have you tried running 2.6.0 since upgrading to 2.6.2? If so, does it work, or are you getting the same error?
4. Have you tried 2.6.1? If so, are you getting the error there?
5. Have there been any changes to the network or operating environment?

**Comment by AbhishekGuptaACN** [comment]
Hi Andrew,

Thanks for your response.

Please find my reply below:

Abhishek


From: Andrew Dorton ***@***.***>
Sent: Thursday, April 1, 2021 1:38 AM
To: adobe-apiplatform/user-sync.py ***@***.***>
Cc: Gupta, Abhishek ae ***@***.***>; Author ***@***.***>
Subject: [External] Re: [adobe-apiplatform/user-sync.py] User-Sync (2.6.2) is failing however User-Sync (2.6.0) is working (#692)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


It looks like the UMAPI client is unable to connect to the identity endpoint to get and API token. We haven't make any changes to umapi-client.py recently that would impact that connection:

https://github.com/adobe-apiplatform/umapi-client.py/blob/v2/.changelog/changelog.md<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_adobe-2Dapiplatform_umapi-2Dclient.py_blob_v2_.changelog_changelog.md&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=HIoCx4QzESNQQuDWnz8BjjpJSKuA1ilyWJdBwoWdFvw&m=LTELMAH7wU1S6-krx63c4s7Ih4xoJX4V73HNpcckKy0&s=phbRgGHeuh0PeDbCty6BUG7q1-Nh4luNDwxl59D_UkA&e=>

I have a few questions:

  1.  Does this happen every time you run 2.6.2? -> Yes
  2.  Have you made any changes to your UST config files? -> NO,  there is no change done. We only replaced the sync file of new version. We even get it checked with adobe engineers.
  3.  Have you tried running 2.6.0 since upgrading to 2.6.2? If so, does it work, or are you getting the same error? -> in 2.6.0 there is no error. Even if I revert the settings from 2.6.2 to 2.6.0,  there is no issue. For 2.6.0, it works every time.
  4.  Have you tried 2.6.1? If so, are you getting the error there?-> no we did not try 2.6.1.
  5.  Have there been any changes to the network or operating environment?-> no changes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_adobe-2Dapiplatform_user-2Dsync.py_issues_692-23issuecomment-2D811424797&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=HIoCx4QzESNQQuDWnz8BjjpJSKuA1ilyWJdBwoWdFvw&m=LTELMAH7wU1S6-krx63c4s7Ih4xoJX4V73HNpcckKy0&s=2csX39YgRmfdNNX2wuAlV_2YJwtxGAOR2ehmOs35iOM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATPJHRTPRG55X4UV4FQWRO3TGN6KRANCNFSM42EXVXKA&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=HIoCx4QzESNQQuDWnz8BjjpJSKuA1ilyWJdBwoWdFvw&m=LTELMAH7wU1S6-krx63c4s7Ih4xoJX4V73HNpcckKy0&s=EmKGTxKsIumpsjv427sRktnQPqmp6iZObb4ejVxPn8M&e=>.

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by Luci2015** [comment]
-> on the same machine where you have UST, can you please  connect in the browser to "https://ims-na1.adobelogin.com" and click the 'lock' icon next to the URL and then View certificate -> Certificate Path and take a screenshot of that window (add it here)?
-> can you please type 'set' in command line and look in the list for any of these env variables: http_proxy, https_proxy, requests_ca_bundle; is any of these present?
-> if you move the entire UST folder on a different computer in your network, that still has access to your LDAP, and run UST in command prompt via "user-sync.exe -t" are you obtaining same error? (remove the UST folder after this test)

**Comment by AbhishekGuptaACN** [comment]
Hi,

Here you go.


-> on the same machine where you have UST, can you please connect in the browser to "https://ims-na1.adobelogin.com<https://urldefense.proofpoint.com/v2/url?u=https-3A__ims-2Dna1.adobelogin.com&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=HIoCx4QzESNQQuDWnz8BjjpJSKuA1ilyWJdBwoWdFvw&m=H4KVFDLuzTrr2R8VJIV5MPB3mMUCjiiJG8G12gYv3BU&s=r1nMmx6XfsU2KqF7xsJavuCjDp1CdqBny66iVk2mfBg&e=>" and click the 'lock' icon next to the URL and then View certificate -> Certificate Path and take a screenshot of that window (add it here)?

***@***.***D72706.BD766920]

-> can you please type 'set' in command line and look in the list for any of these env variables: http_proxy, https_proxy, requests_ca_bundle; is any of these present?-> None of them present
-> if you move the entire UST folder on a different computer in your network, that still has access to your LDAP, and run UST in command prompt via "user-sync.exe -t" are you obtaining same error? (remove the UST folder after this test) -> we don’t have any other server  but I will try .

Abhishek

From: Lucian ***@***.***>
Sent: Thursday, April 1, 2021 1:28 PM
To: adobe-apiplatform/user-sync.py ***@***.***>
Cc: Gupta, Abhishek ae ***@***.***>; Author ***@***.***>
Subject: [External] Re: [adobe-apiplatform/user-sync.py] User-Sync (2.6.2) is failing however User-Sync (2.6.0) is working (#692)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


-> on the same machine where you have UST, can you please connect in the browser to "https://ims-na1.adobelogin.com<https://urldefense.proofpoint.com/v2/url?u=https-3A__ims-2Dna1.adobelogin.com&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=HIoCx4QzESNQQuDWnz8BjjpJSKuA1ilyWJdBwoWdFvw&m=H4KVFDLuzTrr2R8VJIV5MPB3mMUCjiiJG8G12gYv3BU&s=r1nMmx6XfsU2KqF7xsJavuCjDp1CdqBny66iVk2mfBg&e=>" and click the 'lock' icon next to the URL and then View certificate -> Certificate Path and take a screenshot of that window (add it here)?
-> can you please type 'set' in command line and look in the list for any of these env variables: http_proxy, https_proxy, requests_ca_bundle; is any of these present?
-> if you move the entire UST folder on a different computer in your network, that still has access to your LDAP, and run UST in command prompt via "user-sync.exe -t" are you obtaining same error? (remove the UST folder after this test)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_adobe-2Dapiplatform_user-2Dsync.py_issues_692-23issuecomment-2D811724595&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=HIoCx4QzESNQQuDWnz8BjjpJSKuA1ilyWJdBwoWdFvw&m=H4KVFDLuzTrr2R8VJIV5MPB3mMUCjiiJG8G12gYv3BU&s=Ke0_ZnW2Vf0zRcCnmqAGAgt4BgnxSwpxN7Ba8LVHDpY&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATPJHRXD4RFYXB5ZHPYZ2KLTGQRSHANCNFSM42EXVXKA&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=HIoCx4QzESNQQuDWnz8BjjpJSKuA1ilyWJdBwoWdFvw&m=H4KVFDLuzTrr2R8VJIV5MPB3mMUCjiiJG8G12gYv3BU&s=niGk8JzizWDvkiN35cN4_n7P0rTDthdiH-WQlSQI_AA&e=>.

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by AbhishekGuptaACN** [comment]
I tried in different machine and got same issue. 2.6.0 is working but 2.6.2 not working with the same error.

**Comment by Luci2015** [comment]
The img did not went through. Can you please attach it to the open case you have wih Cosmin?
Also, I understood from him that you do have your traffic proxyied, but no SSL inspection happens.
I was wondering if we could get the proxy **_do_** the SSL inspection for the 2 endpoints and then we have the tool point to your proxy's root CA cert, to make it trusted. This way we get the proxy deal the handshake part.

**Comment by AbhishekGuptaACN** [comment]
![Uploading cert.PNG…]()

**Comment by AbhishekGuptaACN** [comment]
Can you please write me in detail of what shall i request  from network team?

**Comment by AbhishekGuptaACN** [comment]
additionally, i tested with 2.6.1 and it is also working properly without any issue.

**Comment by adorton-adobe** [comment]
I'm not sure what could be happening here. The `ssl_verify` change we implemented in v2.16 of `umapi-client.py` could be an issue, but that release was made about a month after UST v.2.6.2, so the UST 2.6.2 release would not include it.

@AbhishekGuptaACN my guess is the network your UST server runs in is doing some kind of SSL inspection. Perhaps there was an update to a library or dependency in that build that affects how SSL connections are managed. I did find that the error you reported may be related to TLS 1.0 compatibility. Perhaps, if your network is doing SSL inspection, it doesn't support TLS 1.2.

The next release of the UST will ship with an updated umapi-client that will support disabling SSL verification for the identity endpoint. In the meantime, I recommend running UST 2.6.1.

**Comment by AbhishekGuptaACN** [comment]
Thanks Andrew for update.

Abhishek

From: Andrew Dorton ***@***.***>
Sent: Thursday, April 1, 2021 7:57 PM
To: adobe-apiplatform/user-sync.py ***@***.***>
Cc: Gupta, Abhishek ae ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [adobe-apiplatform/user-sync.py] User-Sync (2.6.2) is failing however User-Sync (2.6.0) is working (#692)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


I'm not sure what could be happening here. The ssl_verify change we implemented in v2.16 of umapi-client.py could be an issue, but that release was made about a month after UST v.2.6.2, so the UST 2.6.2 release would not include it.

@AbhishekGuptaACN<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_AbhishekGuptaACN&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=HIoCx4QzESNQQuDWnz8BjjpJSKuA1ilyWJdBwoWdFvw&m=czlEOsvjqIQxSzLQLuadACs0SdWP73-AS20wXPgIpfw&s=tjAyrmT_Zyuy9AL64xbdpFw4dnjKyq-vW_He13S72sk&e=> my guess is the network your UST server runs in is doing some kind of SSL inspection. Perhaps there was an update to a library or dependency in that build that affects how SSL connections are managed. I did find that the error you reported may be related to TLS 1.0 compatibility. Perhaps, if your network is doing SSL inspection, it doesn't support TLS 1.2.

The next release of the UST will ship with an updated umapi-client that will support disabling SSL verification for the identity endpoint. In the meantime, I recommend running UST 2.6.1.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_adobe-2Dapiplatform_user-2Dsync.py_issues_692-23issuecomment-2D811945785&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=HIoCx4QzESNQQuDWnz8BjjpJSKuA1ilyWJdBwoWdFvw&m=czlEOsvjqIQxSzLQLuadACs0SdWP73-AS20wXPgIpfw&s=l2mzqLU0zjpX1eRLjiMWV2BBU52JABXr9W56jW8NkOs&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATPJHRRZJG5F7NMJG4IHI6DTGR7D5ANCNFSM42EXVXKA&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=HIoCx4QzESNQQuDWnz8BjjpJSKuA1ilyWJdBwoWdFvw&m=czlEOsvjqIQxSzLQLuadACs0SdWP73-AS20wXPgIpfw&s=OBmBYmJICUxh7ZMphO2jmmHyJe_5wslxVBJvb2eY4T4&e=>.

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by AbhishekGuptaACN** [comment]
Hi, @adorton-adobe , @cbalanoiu , @dscoleman 

The issue did not go away even with the new release. 2.6.0 and 2.6.1 is working but rest of the versions are not working. when i tried with the latest one 2.6.5, i have got the below errors:

**error 1 at the start of the script:**
.\user-sync.exe : user_sync\config.py:981: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer 
size will be used
At C:\AdobeUserSyncTool\run-sync.ps1:29 char:2
+  .\user-sync.exe --process-groups --adobe-only-user-action remove --u ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (user_sync\confi...ze will be used:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**error 2 at the end**

CRITICAL main - Connection to org XXXXXXXX@AdobeOrg at endpoint https://usermanagement.adobe.io/v2/usermanagement failed: HTTPSConnectionPool(host='ims-na1.adobelogin.com', port=443): Max retries exceeded with url: /ims/exchange/jwt (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
2021-09-20 14:33:34 10828 INFO main - ========== End Run (User Sync version: 2.6.5) (TEST MODE) (Total time: 0:00:01)

**Comment by adorton-adobe** [comment]
@AbhishekGuptaACN - I may have a solution. Will you please try this build and let me know if it works?

[ust-2.6.5-sslfix.zip](https://github.com/adobe-apiplatform/user-sync.py/files/7197362/ust-2.6.5-sslfix.zip)

**Comment by adorton-adobe** [comment]
This is what I think is happening based on the information I have:

* Your network is most likely proxying outgoing SSL traffic in a way that is causing an SSL failure for the umapi-client.
* There is either a trust-chain problem with this network service or it doesn't implement SSL properly. Either way the client is seeing an SSL protocol violation.
* There was likely an update to a umapi-client dependency (likely either `cryptography` or `requests`) between UST 2.6.1 and 2.6.4 that forces an error when this violation occurs.

The best solution is for you to work with your network security team. Have them take a look at the issue and see why the SSL violation is occurring. There is unfortunately nothing we can do from our end. We can't downgrade to a potentially less-secure SSL library.

We offer a workaround that may help you in the meantime. UST 2.6.4 applies the `server.ssl_verify` (in `connector-umapi.yml`) option to our identity endpoint. This option bypasses SSL verification to any Adobe endpoint (it does not apply to third-party endpoints the UST may talk to such as Okta). If you want to try this, make sure you are on 2.6.4 or above and set `ssl_verify` in `connector-umapi.yml` to `False`.

```yaml
server:
  ssl_verify: False
```

Note that disabling SSL verification technically makes the sync tool less secure, so please use this option at your own risk. The best way to fix this is at the network level.

I'm closing this since we seem to have our best resolution. Let me know if it doesn't work with SSL verification disabled.

**Comment by AbhishekGuptaACN** [comment]
@adorton-adobe Hi, same error

 Connection to org 6FE936A5559694837F000101@AdobeOrg at endpoint https://usermanagement.adobe.io/v2/usermanagement failed: HTTPSConnectionPool(host='ims-na1.adobelogin.com', port=443): Max retries exceeded with url: /ims/exchange/jwt (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
2021-09-20 20:32:12 11348 INFO main - ========== End Run (User Sync version: 2.6.5-sslfix) (Total time: 0:00:01)

**Comment by adorton-adobe** [comment]
In that case, the best advice I can offer is to work with your network security team to try to figure out why the SSL error is occurring. Perhaps they can disable SSL proxying for the UMAPI. If so, they will need to allow the following hosts:

ims-na1.adobelogin.com
usermanagement.adobe.io

If they can't resolve the issue, then unfortunately you will need to stay on UST 2.6.1.
