### ISSUE TITLE
Post-Sync Sign connector does not work with Users in Multiple Groups (UMG), removes Default Group

### ISSUE THREAD

**Issue by TXST-ITAC-SAAS** [adobe-apiplatform/user-sync.py#705]
**Description**
Whilst there are 2 issues here, I'm logging a single issue as I believe they share a single root cause.

(1) At present the post-sync connector appears to not support the generally available feature Users in Multiple Groups (UMG) feature in Sign. 

(2) It also does not respect the Adobe Sign Account Global setting "Group assignment removes a user from the default group if it is their primary" when the setting is disabled.

**Steps to reproduce**

1. Enable UMG in Adobe Sign
2. Create 2 groups in Admin Console with Sign product profile
3. Enable post-sync connector
4. Configure group names in post-sync
5. Add users to first group
6. Run user_sync.exe (_Creates users in Admin Console_)
7. Run user_sync.exe again (_This "syncs" the 1st group, but moves the user, see "Current Behavior" screenshot_)
8. Add users to second group
9. Run user_sync.exe one or more times (_Users added to second group in Admin Console, no change to Sign_)

**Expected behavior**
Append new group membership to user in Sign, and respect account setting for Default Group.

**Screenshots**
Setting in Account Settings | Global Settings:
![sign-settings-umg](https://user-images.githubusercontent.com/79516845/126223776-ccd956d3-87b0-4a21-b252-5b5eb584bedd.png)

Expected Result (After adding 1st Group):
![expected-behavior](https://user-images.githubusercontent.com/79516845/126224090-52d8ad91-db56-41a4-afa1-36518a4e321e.png)
Expected Result (After adding 2nd Group):
![expected-behavior-2](https://user-images.githubusercontent.com/79516845/126224385-bed17ef3-9f4d-42d0-bcc3-40dea39fb8d0.png)

Current Behavior:
![experienced-behavior](https://user-images.githubusercontent.com/79516845/126224093-5b1c813e-82c6-40e9-b53e-950e77ad0fef.png)

**Environment**
 - UST version: 2.6.2
 - OS type and version: Windows pre-built
 - Any other relevant info: Adobe Sign Enterprise with UMG Enabled

**Comment by vossen-adobe** [comment]
We do not yet support UMG functionality because of API limitations - however, we do expect to support this in a future release.  @adorton-adobe

**Comment by mariakord** [comment]
@vossen-adobe Hi, hope you're well. Just checking if there are any updates on this as we are getting bigger Adobe Sign customers who need the UST to work with the Users in multiple groups functionality. Thank you!

**Comment by adorton-adobe** [comment]
UMG is on the roadmap, but we do not have a definite release date.
