### ISSUE TITLE
Unexpected LDAP failure reading group members: character ' ' not allowed in attribute type

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#725]
**Description**
Error reading group members from oracle LDAP gives the error : `Unexpected LDAP failure reading group members: character ' ' not allowed in attribute type`
This is the space char that the error refers to.

**Steps to reproduce**
the ldap setup:
```
username: "uid=async,ou=Special Users,dc=domain,dc=local"
password: "thepasshere"
host: "ldap://some_IP_here"
base_dn: "dc=domain,dc=local"
```

Since this error was seen before in AD connections where the base_dn with spaces inside the value, such as: `base_dn: "dc=domain, dc=local"`, I tried to fix the username value so that the space between `Special Users` be escaped, such as:
`username: "uid=adobesync,ou=Special\ Users,dc=domain,dc=local"`

The tool run OK for a couple of groups, then fails with same error:
`Unexpected LDAP failure reading group members: character ' ' not allowed in attribute type`

Another test was made with an username value that had no space char in the DN; the tool fails to read all members of all groups, just like in the escaped space workaround.

This does not happen in 2.3; I'm suspecting an update of the ldap3 package and also I suspect it is also linked to the data extracted from the ldap, since all that went in had no space.

**Expected behavior**
no error

**Environment**
 - UST version: 2.6.2
 - OS type and version: Windows
 - Any other relevant info: oracle LDAP

**Comment by vossen-adobe** [comment]
ldap3 has validation for this here:
https://github.com/cannatag/ldap3/blob/dev/ldap3/utils/dn.py#L194

Im not sure we can do anything about this

![image](https://user-images.githubusercontent.com/37643772/131419920-61ddbe35-8934-4743-934a-13729f584f10.png)

**Comment by adorton-adobe** [comment]
Unfortunately, I don't know if there is much we can do here. We can't revert to `python-ldap` since several new features depend on `ldap3`. If the customer can't find a reasonable workaround, they may need to develop their own extraction process to put users into a CSV to input into the sync tool.

@Luci2015 - you may want to raise this as a potential bug for the `ldap3` maintainers. It seems like this should be supported, especially if `python-ldap` supports it.

**Comment by Luci2015** [comment]
this was mainly raised for visibility, ldap3 changed their logic as per the RFC, so not expecting a roll-back
I am having issues replicating in openLDAP as all results come back as expected :|
