### ISSUE TITLE
None-type commands

### ISSUE THREAD

**Issue by adorton-adobe** [adobe-apiplatform/user-sync.py#730]
**Description**
Certain circumstances cause `rules.execute_commands()` to process `None`-type objects in the commands list. This can, for example, happen when a user has a blank or invalid country code.

**Steps to reproduce**
* Sync a user with a blank country code (`c`) attribute
* Do not define default country code in `user-sync-config.yml`

**Expected behavior**
`None` entries should be filtered from `command_list` before processing.

**Environment**
 - UST version: v2.6.4
 - OS type and version: any

**Comment by Luci2015** [comment]
IIRC, empty country code (c) means the default_country_code from the user-sync-config would be picked up.
In case the country code is present but not in the ISO list, then the API would return an error for the specific account.
Has ths behaviour changed?

**Comment by adorton-adobe** [comment]
The default country code would also need to be blank (I edited the issue to state this).
```python
        # check whether the country is set in the directory, use default if not
        country = directory_user['country']
        if not country:
            country = self.options['default_country_code']
        if not country:
            if identity_type == user_sync.identity_type.ENTERPRISE_IDENTITY_TYPE:
                # Enterprise users are allowed to have undefined country
                country = 'UD'
            else:
                self.logger.error("User cannot be added without a specified country code: %s", directory_user)
                return None
```

**Comment by adorton-adobe** [comment]
This can also happen when a Federated or Enterprise user is skipped because an Adobe ID with the same email address already exists.

```python
        # check to see if AdobeID exist for FederatedID/EnterpriseID user. Skip user if same email exist.
        if ((identity_type == user_sync.identity_type.FEDERATED_IDENTITY_TYPE or
             identity_type == user_sync.identity_type.ENTERPRISE_IDENTITY_TYPE) and
                self.is_adobeID_email_exist(directory_user['email'])):
            self.logger.warning("Skipping user creation for: %s - AdobeID already exists with %s",
                                self.get_directory_user_key(directory_user), directory_user['email'])
            return None
```

**Comment by vossen-adobe** [comment]
> IIRC, empty country code (c) means the default_country_code from the user-sync-config would be picked up.
> In case the country code is present but not in the ISO list, then the API would return an error for the specific account.
> Has ths behaviour changed?

If the default code is set to blank you can cause this:

![image](https://user-images.githubusercontent.com/37643772/133482524-3c1c440c-5a92-4f65-9371-dd56523a2a52.png)
