### ISSUE TITLE
Getting started with after mapping hook

### ISSUE THREAD

**Issue by cojocarule** [adobe-apiplatform/user-sync.py#736]
Hello, 

I am trying to use an after mappring hook so that when the 'c'(country) attribute read from ldap is 'IM' it is converted to 'US' for the UMAPI post, but seems that the code has no effect, any suggestions?

This is my code in user-sync-config.yml

```
  extension:
    #extended_attributes:
    #  - my-attribute-1
    #  - my-attribute-2
    #extended_adobe_groups:
    #  - my-adobe-group-1
    #  - my-adobe-group-2
    after_mapping_hook: |
        ct = source_attributes.get('c')
        if ct == 'IM':
          target_attributes['country'] = 'US'
```

**Comment by Luci2015** [comment]
AFAIK the 'c' attribute is extracted by default and does not need to be added specifically to extedned attributes, so your code should just work..
Try this setup as well:

```
extended_attributes:
  - c

extended_adobe_groups: []

after_mapping_hook: |
    ct = source_attributes.get('c')
    if ct.lower() == 'im':
        target_attributes['country'] = 'US'
```

**Comment by Luci2015** [comment]
BTW, this has to be added inside the extension-config.yml file not in user-sync-config one.
The user-sync-config.yml just needs to mention that the extention is in use, via this statement:
`extension: extension-config.yml`
--> add this statement under the default_country_code and make sure the extension-config file is next to the rest of the yml files.

**Comment by cojocarule** [comment]
Cool, it's working like this, with your code and separate file. Thanks.

Could this also be used create certain users on the Adobe side with anothe identity_type than the default. 
For example if user-sync-config has set user_identity_type: federatedID but we need to create enterprise EnterpriseID for some users that have a particular domain, can after mapping hook be used to specify the identity type.?

**Comment by adorton-adobe** [comment]
Identity type is fundamental to the UST config and thus can't be changed on a per-user basis. The only options you can change for a user are `username`, `email`, `domain`, `firstname`, `lastname` and `country`. Your best option is to set up a different UST config with the desired identity type and manage enterprise users in a separate group mapping from federated users.

Since the original question was addresses, I'm going to close this issue.
