### ISSUE TITLE
okta version specified in install instructions not latest

### ISSUE THREAD

**Issue by chaplina** [adobe-apiplatform/user-sync.py#743]
The version specified in the install instructions is 0.0.3.1 and was released sometime before 2017.

According to PyPi okta is now at 2.2 and seems to be updated regularly.

Is there any reason why a more recent version cannot be used?

**Comment by adorton-adobe** [comment]
We use a modified fork of the client, so we can't easily upgrade. There are no known issues with the client we use now, so we don't have plans to change or upgrade it.

**Comment by chaplina** [comment]
understood...thanks!
