### ISSUE TITLE
Adobe-side license Override groups blocking User Sync group updates

### ISSUE THREAD

**Issue by Pythagoras888** [adobe-apiplatform/user-sync.py#746]
We have multiple groups in Active Directory, a Licensed Group, and an Unlicensed group.  Those groups are "mapped" in the **user-sync-config.yml** file to mirrored Adobe groups.  Adobe CC accounts are created for members of both mirrored AD and Adobe groups, but only "Licensed Group" auto-assigns a license.  We don't have enough licenses to cover all users, so some job classes don't get Adobe CC by default - but an admin can over-ride them to receive a license.

On the Adobe Cloud side ONLY, there is a third group, "Overrides" group.  If an Adobe user in the "Unlicensed" group needs a license, a technician uses the Adobe Admin console to manually add them to the Adobe "Overrides" group, which also auto-assigns them a license.  Sometimes if the user's account has not yet been provisioned, the technicians must also create their Adobe Cloud user account, and make them a member of the "Overrides" group to assign a license, with the expectation that they will be added to one of the two "mapped" groups later on.

The problem is that for those users who are members of the manually maintained "Overrides" group, for the most part the User Sync never makes them a member of the Licensed or Unlicensed group once they become members of one of those two on-premise AD groups.  We understand that there isn't a basis for removing them from the Adobe Cloud "Overrides" group, that would have to be done manually, but we'd like to see their on-premise AD membership in Licensed or Unlicensed get mirrored to the corresponding Adobe group, which does not seem to be happening.  We understand that we'd still need to periodically remove the "Licensed" group members from the "Overrides" group as a cleanup step to put those users on a pure automated provisioning basis.   We'd leave them in Unlicensed and Overrides of course, since they obviously needed a Override license, but at least we'd know the reason was that their job didn't qualify for a default Adobe CC license to be granted to them.

The way it appears to work now,  once they are members of a "non-mapped" Adobe group, their later added membership in a "mapped" group is getting ignored by User Sync.

We run the default .bat file command string,   "python user-sync.pex --process-groups --users mapped" 

Everything else works fine, we remove blocks of expired unmapped users with no Cloud group memberships occasionally using an exported CSV file that we filter and massage and then Bulk upload to perform user deletes, because there are some AdobeID type accounts, and this issue with Overrides, which makes the risk of losing unmapped but active users too great to include account removes as a step in User Sync.  We're happy just to get our thousands of routine users licensed and de-licensed (which mostly works), but this issue with non-mapped group memberships blocking adding users to a mapped group is a real pain, requiring hundreds of cycles of looking people up and manually adding them to what should be mapped groups.

Can someone suggest an arcane parameter combination, or maybe a new feature that could be added to User Sync so that it will ensure users are added to mapped groups regardless of any memberships in unmapped groups, if that is the underlying dynamic or issue?  Many thanks.

**Comment by adorton-adobe** [comment]
Please post copies of your `user-sync-config.yml` and `connector-ldap.yml` files. Be sure to remove host, username and password from the LDAP connector. You can either upload them here by dragging and dropping the files to the comment box, or email them to me at adorton@adobe.com

**Comment by adorton-adobe** [comment]
Let me know if you still need assistance. Otherwise I will close this issue later this week.

**Comment by adorton-adobe** [comment]
I'm closing this issue. Please re-open if you need further assistance.
