### ISSUE TITLE
Document user_username_format and user_domain_format

### ISSUE THREAD

**Issue by adorton-adobe** [adobe-apiplatform/user-sync.py#76]
I don't see any mention of user_username_format or user_domain_format in the Sync Guide.  I'm helping a customer that uses username-based auth on their federated domain, and we had to search the source code to figure out how to set username and domain on user records.

**Comment by adobeDan** [comment]
Yep, great point.  See also #48: I'm doing work there to add a `user_identity_type_format` so you can have different types of users in your one directory system.  We will need to document this with those others when added.

In general our docs are not very good about how to work with username-based federation.  And there are a lot of bugs about that in the current release, all of which I think are fixed in the v1 branch at this point.

**Comment by adobeDan** [comment]
@phil-levy Can we have @jabogart take a crack at this?

**Comment by phil-levy** [comment]
What is the the problem?  Also why do we want more than one identity type in a directory.  Seems like that would be very problematic for users.  Is this really a multi-domain thing?

**Comment by adobeDan** [comment]
@phil-levy I think you meant your comment for #48.  Happy to discuss there.  For this issue, it's just one of updating the docs to explain how to set up your connector-ldap for the cases where you are doing federated with username-based login.  You have to have attributes for the username and the domain, as well as the email.

**Comment by phil-levy** [comment]
Who knows the answer about  non-email username?  We'd have to gather the information.

**Comment by adobeDan** [comment]
Both Andrew and I know the answer.  You have to set the value of `user_username_format` and (optionally)`user_domain_format` in your connector-ldap.yaml config file.  You set them to a string of the form `'{attrname}'` where the value of the `attrname` attribute is the value to use, or if it's a fixed value (as it often is for domains), then you set the format string to be that value, as in `'domain.com'`.  When reading the directory, the connector will notice that the username field does or does not have an `@` in it, and if it does then it will assume that it's an email-login federated user and take the domain from the email.  if there's no `@` in the username, then it will use the domain value as the domain (so in that case it's not optional that you specify it).  Does that help?

**Comment by adobeDan** [comment]
@phil-levy Can you get to this before you leave on vacation or do you need me to do the doc update?

**Comment by phil-levy** [comment]
I can do.

**Comment by adobeDan** [comment]
Fixed in PR #86 but I screwed up the commit message so it didn't auto-close.
