### ISSUE TITLE
First Name and Last Name is missing when UST reads from a source CSV

### ISSUE THREAD

**Issue by per24238** [adobe-apiplatform/user-sync.py#778]
When UST reads from a source file(CSV), it is creating profiles for SOME Users on Admin console with **Blank** First and Last Name . This only happens for **SOME** users.. 

NOTE: Customer is updating their users in batches over couple of weeks. This issue happened couple of times.  Sometimes the admin has to update the profile(First Name and Last Name) manually and other times do "Edit user details" bulk update.

**Comment by Luci2015** [comment]
if manual update in admin console or via bulk edit works, then it works with UMAPI as well. I suspect something wrong with the csv input. 
without samples this can't be investigated - please have the customer raise a support ticket in admin console and reach out to dev support with a sample csv input /accounts that get created with blank values for first/last name.

**Comment by per24238** [comment]
Hey @Luci2015 , I thought for Admin console embedded services such as csv uploads, UMAPI is not used for creating the user profiles. Please let me know if I am missing something. 
However, I will let the implementation manager know that customer should raise the support ticket(with sample csv data) for this to be resolved.

**Comment by adorton-adobe** [comment]
I'm closing this as we should handle it internally since it requires us to look at customer data.

We'll also need a debug-level log showing the behavior (in addition to the CSV). Feel free to email the CSV and log to me and I'll take a look.
