### ISSUE TITLE
Sign-Sync 2.7.3 error - Unexpected LDAP failure reading group info: session terminated by server

### ISSUE THREAD

**Issue by madumro** [adobe-apiplatform/user-sync.py#782]
**Description**
When syncing users from LDAP to Sign, this error is generated every day when the cache is refreshed:
 "CRITICAL main - Unexpected LDAP failure reading group info: session terminated by server"

**Steps to reproduce**
The error is replicable only when the following circumstances are met:
* the identity source is LDAP
* the number of Sign users is high (over 7000) and retrieving all Sign users lasts for ~2hours
* the Sign-Sync Tool is executed after more than 24 hours from the previous cache refresh
* (If the cache is fresh, the tool runs successfully) 

**Expected behavior**
The tool should run properly, like it does when the cache is fresh

**Environment**
 - UST version: 2.7.3

**Comment by adorton-adobe** [comment]
The length of time taken to live-query all Sign users and groups may have an impact here. What LDAP system are you using?

My guess is the LDAP server isn't configured to handle long-running queries. You may want to try increasing the `search_page_size` in the LDAP config. It should be set to `1000` but try setting it to something higher than the expected number of users (such as `10000`).

**Comment by madumro** [comment]
Changing `search_page_size` didn't help in this case. 
The customer is using AD Function level 2016.

**Comment by madumro** [comment]
I think this could be solved by moving the LDAP extraction immediately after the the LDAP connection. Can this be considered for a future release? Thank you!

**Comment by adorton-adobe** [comment]
Feel free to submit a pull request and we can take a look. Otherwise I would need more detail to look into implementing the requested change.

**Comment by Luci2015** [comment]
I also met the situation and hitting a 10054 error on connecting to the LDAP. will add a PR

**Comment by adorton-adobe** [comment]
fixed by #798
