### ISSUE TITLE
Exclude users in Sign sync

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#804]
**Is your feature request related to a problem? Please describe.**
2 different branches of same Org sync their separate users from different local directories and different domains to same Sign Dashboard.
Once a Sign sync ends, it would reset the other branch's users and vice-versa. 

The previous version of UST would just compare the Admin Console extraction (which could be done only for particular domain users), then compare with the Sign Dashboard.
The 2.7.5 adds an extra `handle_sign_only_users` function which takes a global set action for all the rest of the users, hence the need to exclude at target (Sign) some of the accounts.

**Describe the solution you'd like**
Process could be similar to what exclude users does for Admin Console sync. Regular expressions or group exclusion would work just fine.

**Describe alternatives you've considered**
the branches use exclude keyword in the sign sync to exclude any other account found in Sign and not in their particular directory extraction, including their own, which are sign-only. Possibly this has no impact for GPS, since removing from Admin Console takes away the license and inactivates the account in Sign, but could be of interest for Neptune version.

**Comment by adorton-adobe** [comment]
This is a good idea and I'll keep it in mind. Right now for Sign sync we're focusing on the following:

1. User info updates
2. UMG support
3. Possible group/role mapping enhancements

Let me know if you have any additional info on how you thing the exclusion feature should work.

**Comment by Luci2015** [comment]
I am thinking we could modify the sign config file to accept an 'exclude_users' type of entry that takes in a (list of) regular expression(s) just like we do for the Admin Console sync, and build the code around the exclusion of those accts on Sign side.
Logging should show what account was excluded, by email.

**Comment by adorton-adobe** [comment]
This is implemented in v2.10.0rc4
