### ISSUE TITLE
Sign sync: IndexError list index out of range

### ISSUE THREAD

**Issue by lexcyn** [adobe-apiplatform/user-sync.py#812]
**Description**
I am attempting to set up sign sync in an existing user sync environment. We are using our user sync LDAP connector. Not syncing users and only syncing sign groups via sign sync, since the user-sync will handle users (enterprise sign).

**Steps to reproduce**
Run a user-sync sign-sync
After it finds the users from our test group, it fails with an unhandled exception

**Expected behavior**
Sign sync should synchronize the users to the correct sign groups

**Screenshots**
![2023-03-06_16-49-29](https://user-images.githubusercontent.com/23508813/223243180-c6129ed2-ee65-4937-868d-f2da13ca92fe.png)

**Environment**
 - UST version: 2.8.0
 - OS type and version: Windows Server 2016 (1607.14393.5717)
 - Any other relevant info: User sync is working as expected

**Comment by adorton-adobe** [comment]
Try deleting your cache directory and syncing again.

**Comment by lexcyn** [comment]
> Try deleting your cache directory and syncing again.

Thanks - now I am getting a "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host"

I think I might know what this is though - I assume the sign sync requires a connection back to api.echosign.com? The server I am using only has specific ports open to internet endpoints so I may need to add this one in.

**Comment by adorton-adobe** [comment]
You'll either need that or `adobesign.com`. In order to successfully sync, you will need to allow outgoing HTTPS (port 443) connections to `*.echosign.com` or `*.adobesign.com`.

**Comment by lexcyn** [comment]
> You'll either need that or `adobesign.com`. In order to successfully sync, you will need to allow outgoing HTTPS (port 443) connections to `*.echosign.com` or `*.adobesign.com`.

Thanks - I am just checking as well, I created an integration key but the documentation says integration keys are no longer supported. I assume this is just for API access and sync can still use them, correct?

**Comment by adorton-adobe** [comment]
Integration keys are considered deprecated, but unfortunately Sign's OAuth support does not include server-to-server auth.

**Comment by adorton-adobe** [comment]
This appears to be resolved. Closing.
