### ISSUE TITLE
Document OAuth Credentials

### ISSUE THREAD

**Issue by jbishop-staar** [adobe-apiplatform/user-sync.py#816]
**Description**
JWT for authentication is now deprecated, but documentation does not explain how to setup OAuth credentials

**Expected behavior**
Clear explanation of how to set up OAuth credentials in documentation here: https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/connect_adobe.html

**Comment by adorton-adobe** [comment]
Support for OAuth Server-to-Server will be supported in the next UST release (v2.9.0). We hope to roll the update into a new release candidate soon.

In the meantime, nothing will break with JWT auth in the near term.

As per [the official documentation](https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/migration/), all JWT integrations will continue to work until 1 January 2025. In addition, the console will continue to support the creation of new JWT integrations until about a year from now (1 May 2024).

Please let me know if you have any questions.

**Comment by jbishop-staar** [comment]
Understood, thank you!

**Comment by adorton-adobe** [comment]
With the release of `v2.9.0rc2` we can close this. Just be mindful of #817 until the next release is out.

**Comment by sayerbartlett** [comment]
Is there updated documentation for configuring OAuth? I couldn't find any.

**Comment by BrianBLS** [comment]
https://github.com/adobe-apiplatform/user-sync.py/blob/user-guide-wip/en/user-manual/connect_adobe.md

**Comment by srnewcomb** [comment]
> https://github.com/adobe-apiplatform/user-sync.py/blob/user-guide-wip/en/user-manual/connect_adobe.md

This goes to a "page not found". Has this been updated somewhere?

**Comment by adorton-adobe** [comment]
UST documentation is found here: https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/

The page you're looking for specifically is here: https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/connect_adobe.html

**Comment by davidcam-nwse** [comment]
@adorton-adobe saved my day, thanks for the link update, your link works fine
