### ISSUE TITLE
Unhandled exception when running a test sync - TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by BrianBLS** [adobe-apiplatform/user-sync.py#817]
**Description**
Was using v2.7.3 but had to change because we moved to the oauth credentials. After setting up the config files I am getting  Unhandled exception when running a test sync.

**Steps to reproduce**
Using LDAP
This is the test command:
user-sync.exe -t --users mapped --process-groups --adobe-only-user-action exclude

**Expected behavior**
I expected the users to get read and displayed.

**Screenshots**

![image](https://github.com/adobe-apiplatform/user-sync.py/assets/136511545/13e37cf3-65fd-423f-b9fd-d65c0f5af8ed)

**Environment**
User Sync v 2.9.0rc2
Python 3.9.13
Windows 10.0.14393

**Comment by HaydenRead** [comment]
Same issue here...
Uncommenting **host** in connector-umapi.yml fixed that issue, but then I got further issues (Error contacting UMAPI server)

**Comment by BrianBLS** [comment]
Adding this to the connector-umapi looks to have resolved the issue. I had to comment out the auth_endpoint, it was giving an error.

server:
  host: usermanagement.adobe.io
  endpoint: /v2/usermanagement
  auth_host: ims-na1.adobelogin.com
  #auth_endmpoint: /ims/exchange/jwt
  timeout: 120
  retries: 3

**Comment by adorton-adobe** [comment]
This is resolved in bbe1edb.

For now, add a setting under `server` (doesn't matter which, `timeout` or `retries` is fine).
