### ISSUE TITLE
ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by midnight33233** [adobe-apiplatform/user-sync.py#823]
**Description**
When trying to run the latest build of user-sync I get the following error  

  File "user_sync/app.py", line 28, in <module>
ModuleNotFoundError: No module named 'click'
[1163] Failed to execute script 'app' due to unhandled exception!

**Steps to reproduce**
extract the latest user-sync file to user_sync_tool directory and try to run it.  This has happened with all 2.9.0 builds including pre-builds.  The last version that i have working is 2.7.6

**Environment**
 - UST version: v2.9.0
 - OS type and version: Ubuntu 22.04.2 LTS
 - Any other relevant info: Python version 3.10.12

**Comment by adorton-adobe** [comment]
Which build of the tool are you running exactly? The `jammy` build should work on 22.04 with no issues.

**Comment by adorton-adobe** [comment]
Should be resolved now.

https://github.com/adobe-apiplatform/user-sync.py/releases/tag/v2.9.1

Let me know if you have other issues.
