### ISSUE TITLE
documentation update

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#83]
Please update the pdf and word documentation on page 10
in "Example configurations, under user-sync.config.yml:
 “dashboard" should not contain attribute “user-identity-type”. Should be under "directory"

Thanks!

**Comment by adobeDan** [comment]
I believe we should patch the published docs with this change in advance of the next release.  That will mean changing out the PDF to be one created from the updated doc set.  @phil-levy we should discuss how we want to create the PDF version.
