### ISSUE TITLE
Push strategy generates an error in the latest stable release (2.9.1)

### ISSUE THREAD

**Issue by madumro** [adobe-apiplatform/user-sync.py#838]
**Description**
UST throws an error when trying to use push strategy with the latest releases (2.9.0, 2.9.1, 2.10.1rc):

2024-01-04 13:26:46 8100 CRITICAL main - Unhandled exception
Traceback (most recent call last):
  File "user_sync\app.py", line 461, in run_sync
  File "user_sync\app.py", line 409, in begin_work_umapi
  File "user_sync\engine\umapi.py", line 197, in run
  File "user_sync\engine\umapi.py", line 495, in sync_umapi_users
AttributeError: 'list' object has no attribute 'data'

**Steps to reproduce**
* The issue was signalled by a customer who syncs from a .csv file, but it can be reproduced at synchronization from an ldap source as well.
* Command-line: user-sync.exe -t --strategy push
* Can be reproduced with the default options

**Expected behavior**
The tool should push the changed to Admin Console without errors. 
This is critical for the customer who has over 200,000 students and 25,000 staff and need the push strategy.

**Environment**
 - UST version: All new UST versions with OAuth support

**Comment by Morish24** [comment]
We are also having getting the same error with all latest versions. Can this be fixed.
