### ISSUE TITLE
mix of adobeID and federatedID issue

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#84]
use case:
 - user.1@somedomain.com   is added to adobe.com as Adobe ID and is not part of any Org.
 - my Org has the "somedomain.com" owned now, and I want to add the same e-mail to it as federatedID
 - this user is added to an AD group and I try to sync up with AC running it with **--users group "Adobe Acrobat DC"  --update-user-info --process-groups**   arguments.
Result: This is an *ERROR* with a message like "user not in Org".

On Admin Console side if I search for this user, it is not there.

Expected: user should be added to my Org as federatedID, since the AdobeID is not there either and only one of them can be there using same  e-mail address.

Workaround: I can manually add the user as federatedID into Admin Console. In case there are many I can use bulk upload in Admin Console.

**Comment by adobeDan** [comment]
@Luci2015 Can you confirm what the `user_identity_type` setting was?  Were there other Federated ID users who were correctly created by this run?

**Comment by Luci2015** [comment]
sorry, I forgot to mention that the default value for user type in config is: federatedID

yes, other federatedIDs got created as they only exist as federated.
I have checked a bunch of them and they only exist in backend as "federated ID"

**Comment by adobeDan** [comment]
@Luci2015 Sanitized log is attached to this comment.  If you still have the log in your possession, can you look for all the log messages prior to the error reported for action_39 that have the same email in them?

Also, can you try and repro (or have the customer repro) this situation using the [1.2rc2](https://github.com/adobe-apiplatform/user-sync.py/releases/tag/v1.2rc2) build?  Or is to too sporadic to be reliably reproduced>

**Comment by adobeDan** [comment]
@Luci2015 The latest log you sent me from your customer (run with the 1.2rc1 build) shows no sign of this problem.  Are they still encountering it?

**Comment by adobeDan** [comment]
Haven't heard back, so I'm closing the issue.  @Luci2015 if you get other news feel free to reopen.
