### ISSUE TITLE
UST and OAuth Server-to-Server

### ISSUE THREAD

**Issue by cojocarule** [adobe-apiplatform/user-sync.py#842]
Started the migration to OAuth Server-to-Server using UST v2.9.1
Logs show this entry on every run
`2024-02-20 09:30:02 3524 INFO umapi_client.auth - auth token is missing or expired - refreshing now`  
Working fine after this, connects to UMAPI no other issues. Is it expected?.

**Comment by cbalanoiu** [comment]
Yes, that is expected. If the authToken is missing or expired, a new one is generated.
