### ISSUE TITLE
Include in log which IP addresses are unsuccessful with the LDAPS connection

### ISSUE THREAD

**Issue by mmiddlet** [adobe-apiplatform/user-sync.py#843]
When a connection to a single DNS server or domain controller fails, ideally, the unsuccessful IP addresses should be added to the log. This would be very helpful.

Of course, if a connection to a single DNS server or domain controller fails, ideally the application should have the intelligent logic coded in to attempt to connect to an alternate DNS server or domain controller.

**Comment by adorton-adobe** [comment]
duplicate of #841
