### ISSUE TITLE
Multiple Targets is not working for OKTA configuration

### ISSUE THREAD

**Issue by sacordero** [adobe-apiplatform/user-sync.py#845]
**Description**
The use of Multiple Targets with the Adobe User Sync Tool is not working for OKTA configuration
https://adobe-apiplatform.github.io/user-sync.py/en/user-manual/configuring_user_sync_tool.html#multiple-targets

**Steps to reproduce**
User has the configuration for multiple UMAPI connector files, six in fact.
The sync runs successfully but only the Primary UMAPI connector file is used.  While the other secondary UMAPI connector organizations s are acknowledged and seen in the debug log, there  no action is taken on the users in those organizations.

**Expected behavior**
The secondary UMAPI connector organizations would be processed just like the Primary UMAPI connector organization.

**Screenshots**
![image](https://github.com/adobe-apiplatform/user-sync.py/assets/73367089/89eb4993-852f-4d30-be5d-05e5e89390b5)

**Environment**
 - UST version: 2.9.1
 - OS type and version:  Windows Server 
 - Any other relevant info:

**Comment by adorton-adobe** [comment]
@sacordero have you tested this config with any other identity sources?

**Comment by sacordero** [comment]
@adorton-adobe No, I have not, but there was another customer that had a similar issue connecting to a Secondary source and was also getting 0 actions and no errors  reported about the same time.

**Comment by adorton-adobe** [comment]
Does this other customer also use the Okta connector?

**Comment by sacordero** [comment]
Unsure,  the agent who had the case did not state what the exact configuration was in the internal Slack channel conversation.

**Comment by adorton-adobe** [comment]
I unfortunately can't investigate further without more info. Please re-open if you can give me a better idea of how the customer's UST is configured.
