### ISSUE TITLE
cannot connect to Adobe Server ims-na1.adobelogin.com

### ISSUE THREAD

**Issue by tFaiT** [adobe-apiplatform/user-sync.py#847]
Hi

When running Adobe User Sync Tool, the tool suddenly cannot connect to Adobe Server. 

Error message:
2024-04-10 09:37:52 5460 
CRITICAL main - Connection to org 9A44470757C6A88C7F000101@AdobeOrg at endpoint https://usermanagement.adobe.io/v2/usermanagement failed: 
HTTPSConnectionPool(host='ims-na1.adobelogin.com', port=443): Max retries exceeded with url: /ims/exchange/jwt 
(Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000029B63EF62E8>: 
Failed to establish a new connection: 
[WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time,
 or established connection failed because connected host has failed to respond',))

- We are not using Proxy Server
- Firewall side: there is no any blocking, log picture is attached
![ADFS firewall log](https://github.com/adobe-apiplatform/user-sync.py/assets/123863954/ffa2c5d1-02b7-477f-86bc-2255c8c026a1)
- Refer to https://github.com/adobe-apiplatform/user-sync.py/issues/544, we don't have Proxy, so HTTP_PROXY and HTTPS_PROXY env doesn't need to set 

Can you provide suggestion to solve the problem ?

Thanks
Philip

**Comment by adorton-adobe** [comment]
This is a network issue and falls outside the scope of UST support. I recommend trying a JWT exchange using Postman or cURL or something similar. Or better yet, switch to OAuth Server to Server since JWT is deprecated and you can get a cURL command for token acquisition that you can use to test the connection.
