### ISSUE TITLE
After Mapping Hook with Child Console

### ISSUE THREAD

**Issue by ChristopherKDau** [adobe-apiplatform/user-sync.py#849]
We recently migrated over to Global Admin Console to be able and create child organizations. I was able to migrate the users over from the parent console to the child console and got the child organization to sync with the user groups, but the after mapping hooking is not applying like how it's with the parent console.

For the after mapping hook, we list out what is considered single app and all apps. If a user has an all apps license, the after mapping hook would remove the user from the single app license. This is not happening after we migrated the user over to the child organization. Am I missing a config file or need to update a setting in a config file?

[extension-config.txt](https://github.com/adobe-apiplatform/user-sync.py/files/15070647/extension-config.txt)
[user-sync-config.txt](https://github.com/adobe-apiplatform/user-sync.py/files/15070648/user-sync-config.txt)

**Comment by adorton-adobe** [comment]
In order for me to look into this, I need to know more about your UMAPI connector config structure. Your `adobe_users.connectors.umapi` setting is empty in the sync config that you provided.

**Comment by adorton-adobe** [comment]
Since I haven't heard back from you or received the information I requested, I will close this issue.
