### ISSUE TITLE
please change the wording for a log line

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/user-sync.py#857]
**Is your feature request related to a problem? Please describe.**
This line in the log "umapi_client.auth - auth token is missing or expired - refreshing now" is a support case generator. We've been asked a lot about it, and, although we can explain it, it's better if it did not raise questions in the first place

**Describe the solution you'd like**
Please rephrase this log line so that it just says something like "obtaining an access token" or similar.

**Comment by adorton-adobe** [comment]
This should be raised on the UMAPI client repo
