### ISSUE TITLE
UST Upgrade to OAuth

### ISSUE THREAD

**Issue by Charlie-New** [adobe-apiplatform/user-sync.py#858]
We're in the process of moving from the JWT to OAuth setup and have setup the new credential on the project, we've downloaded the latest sync tool and set it up for testing but the authentication still uses JWT. The umapi connector config file doesnt specify an authentication type in there, does it need to be specified or will it auto negotiate to OAuth?

Windows Server 2019
user-sync-v2.10.0-win64

**Comment by adorton-adobe** [comment]
oauth is set in the example config file: https://github.com/adobe-apiplatform/user-sync.py/blob/v2/examples/config%20files%20-%20basic/connector-umapi.yml

**Comment by Charlie-New** [comment]
Ok thanks, have updated the config file with the oauth setup, the test connections keep failing with UMAPI connection errors, is there anything else that would need updating? Apologies for some of the newb questions, been thrown this last minute
![UMAPI](https://github.com/user-attachments/assets/5cdaf2ac-0bd5-4038-95a9-d20b897914b0)
