### ISSUE TITLE
Create more comprehensive test environment and better end-to-end tests

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#89]
- Create the ability to mock UMAPI call results so that manually created results can be returned from UMAPI for specific tests.

- Create the ability to mock directory call results so that manually created results can be returned from directory query calls.

- It will probably also be necessary to mock authentication and access calls.

- Create some tests using these capabilities:
     - Basic create function where directory returns some users and Adobe org has no users.  Check that expected user create and add to groups are called.
    - Basic update function where directory returns some users already in Adobe but group memberships and some fields are different.
    - Basic remove function where Adobe returns some users not in the directory and check actions run based on different removal options --remove-nonexistent-users, --delete-nonexistent-users, --remove-entitlements-for-nonexistent-users, --generate-remove-list
    - Cover enterprise and federated users

Think about using record and playback with smart compare as a mechanism.

**Comment by adorton-adobe** [comment]
I've rebased v2 onto `feature/test-framework` in my fork so I can develop some group sync tests.  I'll submit a PR in case you want to merge it here.

**Comment by adobeDan** [comment]
@adorton-adobe OK, thanks for the heads up, here's one for you: I'm doing a ton of rework of the app startup/arg parsing/configuration reading code as part of the work on #299, so you and @bhunut-adobe probably will have to do a careful merge of those changes into your forks that may have also made changes.  I expect to be done with these changes by the end of the weekend, so if you can hold off making more changes in those areas until then, it might save you time. :)
