### ISSUE TITLE
overhaul of names and usage of config settings and command-line args

### ISSUE THREAD

**Issue by adobeDan** [adobe-apiplatform/user-sync.py#95]
The "Enterprise Dashboard" has been rebranded to the "Enterprise Admin Console" everywhere but, apparently, in User Sync.  While this would be a rather widespread change, affecting not only the code but also the configuration options and configuration file names, and while it would *not* be backward compatible, it's one that I believe we should make sooner rather than later.

Question: if we did this change, should we maybe bump the major version number?  After all, it is backwards-incompatible, and we have been talking for quite a while about the "2.0" release of user-sync.  I'm thinking, what with all the features in this 1.2 release, we should maybe rename it the 2.0 release and do the rename...

**Comment by adobeDan** [comment]
@phil-levy Need you to look at this before you go on vacation.

**Comment by phil-levy** [comment]
I thought it was rebranded to "Admin Console" to cover more than enterprise and as far as I know that is the term we use throughout the documentation.

"dashboard" is used in the configuration in a couple of places.  I don't think it is worth the time, expense, and disruption to make this change but if Neal wants to I have no objection.  We could make it compatible by recognizing both tags so it may just be one place.

I would not make changes in the code that are not manifested externally.

**Comment by adobeDan** [comment]
Ok I will check with Neal. Good point about accepting both forms for backward compatibility. 

It's actually a very easy global replace at the code level, because they are both distinctive terms.

**Comment by NealMirchAdobe** [comment]
If possible, it would be best to replace any reference of "Enterprise Dashboard" with "Admin Console".  Accepting both would be crafty!

**Comment by adobeDan** [comment]
@phil-levy @NealMirchAdobe I don't think we have enough customers yet that we need to be overly concerned with backward compatibility.  As long as we can give simple, global search/replace instructions that go along with a release, I think we have few enough users that we can just put it in the release notes to update their configs/scripts and we can have AGS work with the few existing customers to help them port.

@adorton-adobe @bhunut-adobe what do you think?

**Comment by adorton-adobe** [comment]
Seems reasonable to me.  I ran into this earlier today on a call.  It wasn't difficult to figure out which keys needed to be renamed in the config.

**Comment by adobeDan** [comment]
Sorry, but I disagree strongly.  We already have compatibility problems with the official rebranding of the "Enterprise Dashboard" to "Admin Console".  See @NealMirchAdobe's comment from a week ago.  Pretending that didn't happen is not a solution.

**Comment by jameslockman** [comment]
under the hood, Adobe Experience Manager is still CQ. We still refer customers to documentation on Macromedia and Omniture domains. While this would be brand compliant, I am not certain that we get tremendous benefit from the change. I do agree that if we do it, we should do a major version number, since there will be deep impact on the config files, though.

**Comment by adobeDan** [comment]
@jameslockman There is no config file impact if we continue to accept `dashboard`.  I think that's the obvious thing to do, here: accept both and have the docs refer to console.

**Comment by jameslockman** [comment]
Then let's continue to accept Dashboard and encourage new customers to use console.

**Comment by adobeDan** [comment]
OK, after a lot of conversation, we have decided to do a complete overhaul of the existing names and usage of many configuration settings and command-line arguments.  There are many reasons for this, including but not limited to (in no particular order):
* the level of flexibility/complexity built into the current naming/usage conventions is both unnecessary and impossible to document properly; so we are applying the "the simplest possible solution is the correct one" logic to them.
* we want to eliminate automated searches for config files other than the main config file.  They are confusing and unexpected.
* we want to prioritize and simplify the primary use case for user sync, which is that there is a single source of Adobe-side user information (for both user accounts and the product configs/user groups that contain them), aka a "single organization".
* the current syntax for mixing configuration data for a connector between the top-level config file and a dedicated config file is incredibly confusing (both as a user and a code maintainer) and also incredibly unnecessary.  If you want to separate the credentials from other configuration, fine, but then put them into two files rather than one.
* we want to avoid usage of Adobe product names such as "dashboard" and "console".
* we want to avoid the usage of terms customers may not use, such as "organization".
* we want to avoid the use of multiple command-line arguments which interfere with each other.
* we want to do this overhaul, which is needed, ASAP so as to minimize the number of affected users.

Because this is such a big overhaul and incompatible with existing configuration, we are renaming this next release (which also has a lot of bug fixes and new features and hopefully great documentation) to be v2.0.  I will be posting the proposed new scheme in my next comment, and would love to get feedback from everyone as soon as possible.  I am expecting to push a commit which implements this some time today so that we can generate a 2.0rc1 build as soon as possible which uses these conventions.

**Comment by adorton-adobe** [comment]
It might be premature to ask this, but is there a plan to support 1.X for a period of time in parallel to 2.0?  By support, I'm primarily thinking about bug fixes, updates to deal with API changes, etc.

**Comment by adobeDan** [comment]
Proposed new naming/usage conventions are in this comment.  Only changes are documented; anything not mentioned here stays the same as it is today.

## General nomenclature changes

* Wherever we used the word "dashboard" as an adjective describing something on the Adobe side we will now use the term "Adobe".  We will continue to use "directory" as an adjective describing something on the customer side.
* Wherever we used the words "nonexistent user" or "unmatched user", we will now use the words "adobe-only user".
* We will no longer use terms like "owning" or "accessor" or "organization".  Instead, what used to be called the "owning organization" will be called the "(primary) source of user accounts and entitlements" for Adobe users.  Similarly, what used to be called an "accessor organization" will be called an "additional source of entitlements" for Adobe users.


## Command-line Arguments

* There is a new arg `--adobe-only-user-action` which replaces all of: `--delete-unmatched-users`, `--remove-unmatched-users`, `--remove-entitlements-for-unmatched-users`, and `--generate-remove-list`.  This new arg, which is itself optional, takes one or two additional arguments, as follows:
  * `--adobe-only-user-action preserve` (default if not specified).  Leaves Adobe-only users intact on the Adobe side, updating their groups as usual if `--process-groups` is specified.
  * `--adobe-only-user-action write-file` _pathname_.  The same as `preserve`, but additionally writes the list of Adobe-only users to a file for use later with the `--adobe-only-user-list` argument.
  * `--adobe-only-user-action delete`.  Deletes Adobe-only users completely, including (for Enterprise ID and Federated ID) any stored content they had in Adobe services.
  * `--adobe-only-user-action remove`.  Removes Adobe-only users from the Adobe side, but leaves their stored content intact for later recovery by organization administrators.
  * `--adobe-only-user-action remove-entitlements`.  Leaves Adobe-only users intact on the Adobe side, but removes their membership in any product configurations or user groups.

* There is a new argument `--adobe-only-user-list` _pathname_ that replaces the `--remove-list` argument.  The name file contains a list of Adobe-only users who are to be acted upon according to the `--adobe-only-user-action` argument (whose value must be one of `delete`, `remove`, or `remove-entitlements`). When the `--adobe-only-user-list` argument is used, only the users in the file are processed; the customer-side directory is never accessed and none of the arguments related to reading or processing the directory are allowed.

## Configuration Parameters

* As per the general changes, the section formerly called `dashboard` is renamed to `adobe_users` and the section formerly called `directory` is renamed to `directory_users`.
* There is a new `connectors` section under `adobe_users` which is parallel to the one under `directory_users`. The only protocol key allowed under `adobe_users` is `umapi`, and typically there is only one umapi connector in use, so typically the `connectors` section under `adobe_users` looks like this:

``` yaml
adobe_users:
  connectors:
    umapi: adobe-user-config.yml
```
* In the rare cases that user sync is connecting through multiple UMAPI connectors--a primary which is used to manage both users and entitlements, and one or more secondaries which are used to manage entitlements only---then the UMAPI configuration files are put into a list under the `umapi` key, and each secondary config file is keyed with its prefix as used in the group-mapping table, like this:

``` yaml
adobe_users:
  connectors:
    umapi:
      - adobe-user-config.yml
      - org1: org1-config.yml
      - org2: org2-config.yml
      - org3: org3-config.yml
```
* In general, any protocol entry in a `connectors` section can have either a single path value (which is interpreted relative to the containing file) or a list of path values (also interpreted relative to the containing file). If a dictionary is found where a path is expected, the dictionary's values are instead interpreted as paths (relative to the containing file).  This represents a change from the current allowed configuration syntax, because currently we allow intermixing settings dictionaries with config file pathnames.
* There are no more default values for any type of connector configuration file.  All connector configuration files must be specified explicitly.  Only the main user-sync config file is searched for using a default pathname.
* As per the general changes, the `groups` mapping under the `directory_users` section will be a list of dictionaries, each of which has a `directory_group` key and an `adobe_groups` key.  The value of the directory group key must be a string naming a group in the customer directory; the value of the `adobe_groups` key must be a list, each of whose entries is a string naming an Adobe product config or user group. (A string designates a product config or user group from a secondary UMAPI connection by using a prefix consisting of the `umapi` key for that connection and two colons, as in `org1::group1`.)  For example, given the extended `umapi` connector section above, the following group mapping might be used:
```yaml
  groups:
    - directory_group: base
      adobe_groups:
        - "group"
    - directory_group: extended1
      adobe_groups:
        - "org1::group"
    - directory_group: extended2
      adobe_groups:
        - "org2::group"
    - directory_group: extended3
      adobe_groups:
        - "org3::group"
```
* As per the general changes, the `extended_dashboard_groups` setting under `extensions` is renamed to `extended_adobe_groups`.
* There is now only one `limits` setting allowed (and required): `max_adobe_only_users`.  If more than this many Adobe-only users are found, then no changes are made to any Adobe-only users in the current run, including any changes to those users from `--process-groups`.  (If the `adobe-only-users-action` was specified as `write-file`, the Adobe-only users are always written to the given file, even when this limit is exceeded.)

**Comment by adobeDan** [comment]
@adorton-adobe I'm not sure what kind of support you are hoping for existing users to get for v1.x, given that we believe v2.0 can be used to do everything that v1.x is being used to do, but here goes:

* We will certainly provide 1.x users with support for updating their configuration files and invocation scripts.
* If a 1.x user is doing something that we agree cannot be done with 2.x, then we will add that feature to a future release of 2.x, and we will provide bug fix support for the 1.x user until 2.x has the needed feature.

Is that what you were hoping for?

**Comment by phil-levy** [comment]
Yes, and mostly the support for 1.x is "if you are having a problem with 1.x, move to 2.0".  I don't see us making additional releases on 1.x given how few users are on it.

**Comment by phil-levy** [comment]
@adobeDan this looks very good to me and covers all of the items we have discussed.  Is accessor_config_filename_format and the notion that there is a required convention for the additional source of entitlements gone?  This is a config item that would be removed.

**Comment by adobeDan** [comment]
@phil-levy Yes, that's one of the (many) options that provide default filenames that are searched for.  I tried to cover them all in that one remark about "There are no more default values..." but I will amplify that to make it completely clear.

**Comment by phil-levy** [comment]
If you can list the items removed that would be helpful to make sure we take them out of the documentation.

**Comment by adobeDan** [comment]
I am preparing a sample configuration file that has all the allowed settings in it, so we can stare at them.  Out of that work, Phil and I are settling on "adobe_group" as the conjoined term for "product configuration and/or user_group".  This has led to a very small update to the naming conventions, documented above.

**Comment by adobeDan** [comment]
To support using User Sync incrementally, we are adding `--adobe-only-user-action exclude`, which excludes all unmatched users from any updates (same effect as setting the configuration option `max_adobe_only_users: 0`, but it only applies to the current run.

**Comment by adobeDan** [comment]
To simplify the command line and the documentation, we are removing the unnecessary `--source-filter` command-line argument.

**Comment by adobeDan** [comment]
I've finished the rewrite of the main sample `1 user-sync-config.yml` file, and am starting on the code changes to implement this issue.  I've attached the [sample file here](https://github.com/adobe-apiplatform/user-sync.py/files/884159/user-sync-config.yml.txt) for review.

**Comment by adobeDan** [comment]
I've finished the rewrite of the sample `3 connector-ldap.yml` and `4 connector-csv.yml` files.  I've attached them here for review, or see the issue95 branch at 58c1226 or later.

**Comment by phil-levy** [comment]
Are you changing the name of adobe-user-config.yml?  I thought we had agreed that would be the name.

**Comment by adobeDan** [comment]
Yes,`adobe-users-config.yml` changes to `umapi-config.yml` to match all other connectors.  Plus, as per our discussion, the `extensions` parameter is changed to `extension` (singular) and moves into the `directory_users` section and now names the file in which the extension is found.  All the extension settings move to that file, except for `context` which is dropped.

**Comment by adobeDan** [comment]
@phil-levy I get why we have the sub-config files be interpreted relative to the main config file, but I don't get why we do that with the `log_file_directory` setting.  Shouldn't that be relative to the process working directory, the way that command-line arguments are?  It seems to me that the common case is that a user will want his logs and inputs output together, and all his config files together, but not necessarily have his logs and inputs and outputs in the same place as his configs.

**Comment by phil-levy** [comment]
The reasoning is that the user may be running several sync jobs with several config files.  They can invoke them from the same working directory and point the tool using --config-filename to the config file for each job (which are in different folders).  That effectively allows you to locate the nexus of files for each job together and you don't have to edit the config file to move the logs.  This is documented in the training slides, Scenario 7.

Having logs relative to cwd can also be problematic because the invocation can come from different contexts (shell, cron, etc.) which sometimes have different cwds.  Having the logs relative to the config file seemed like a good way to enable the configuration to get consistency in log location.

**Comment by adobeDan** [comment]
Ah, right, makes perfect sense.  Thanks for the explanation!

**Comment by adobeDan** [comment]
@phil-levy @bhunut-adobe @adorton-adobe @jameslockman @ianmak @ensembledeanw @chesterl86 OK this is a long status report with an IMPORTANT REQUEST at the bottom.  Even if you skip the report please read the important request!

* As of 6am this morning I got what I believe are all the new arguments and configuration syntax working.  I can now run all of my live issue tests (once I convert their config files and invocations) and the functionality seems quite good, at least as stable as 1.2.
* I fixed a number of things on the way here, such as #121 and #118 (which required umapi-client changes as well).  #121 and #95 will stay open for another day or so until I confirm.
* I have now created an r1 branch which has the 1.1.1 release with docs on it; that's the backward-compatible branch that we will fix bugs in if we absolutely have to.
* I have now created a v2 branch which has all the latest work checked into it.  **All work going forward should now be based on the v2 branch**, and the v1 branch will be deleted shortly.  I am keeping my issue95 branch as my working branch while I do final testing (and build new tests, see below); then it will close when I merge final fixes into v2.
* I am hoping @phil-levy, who has been doing a bunch of doc updates, will rebase his doc updates onto v2 in his local branch and then submit them in a pull request.  (Phil, once you merge v2 into your branch, you will be able to test what you are putting in the docs, and also look for and change any error message wording/etc. that you want.)
* The old Nosetests are completely broken, and now that I look carefully it's pretty clear that many of them need to be thrown away, because what they were really testing was the code paths in various config and setup functions rather than the actual reading and effect of arguments and configuration files.  So on Monday I'm hoping to build a new, smaller set of basic Nosetests while I do cleanup, and then we will be ready to release a v2rc1 on Tuesday.

**MOST IMPORTANT**:  Please everyone pull down the v2 branch and start updating your live tests to use the new config file format and argument invocations and make sure that everything is working the way it's supposed to.
